LPS-165005 | LPS-165006 | LPS-165009 | LPS-165010
liferay-objects/liferay-portal pull request #1202
Opened 2022-10-13 20:59 UTC by mateussgn

Related issue: https://issues.liferay.com/browse/LPS-165005

2022-10-13 20:59 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-10-13 21:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/763/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/763/jenkins-report.html">here</a>.</b></p>

2022-10-13 21:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1dcf56d8a945ed677d6db6110a7f54c822adc852">1dcf56d8a945ed677d6db6110a7f54c822adc852</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussgn/liferay-portal/tree/LPS-165005">LPS-165005</a><br/>Branch GIT ID: <a href="https://github.com/mateussgn/liferay-portal/commit/c980d98e113252f09f11b00e7fc5c3d2a9ba6c84">c980d98e113252f09f11b00e7fc5c3d2a9ba6c84</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/763/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/763/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/list-type/list-type-service/build.gradle expected:&lt;...mpileOnly project(":[apps:static:portal:portal-upgrade-api")
     [java]   compileOnly project(":core:petra:petra-lang")
     [java]   compileOnly project(":core:petra:petra-sql-dsl-api")
     [java]   compileOnly project(":core:petra:petra-string]")
     [java] \}&gt; but was:&lt;...mpileOnly project(":[core:petra:petra-lang")
     [java]   compileOnly project(":core:petra:petra-sql-dsl-api")
     [java]   compileOnly project(":core:petra:petra-string")
     [java]   compileOnly project(":apps:static:portal:portal-upgrade-api]")
     [java] \}&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 59.318 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-39/job/test-portal-source-format/763//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221013140213589.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221013140213589.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2077003372.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1200209382
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 167ms
[junitreport] Deleting: /tmp/null1200209382
     [echo] A report with all the test results can be found at test-results/html/index.html.</pre></details></html>

2022-10-13 21:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/763/">test-portal-source-format#763</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/763/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/1202">liferay-objects#1202</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2006138843">[master] ci:test:sf - mateussgn &gt; liferay-objects - PR#1202 - 2022-10-13[13:59:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/2298/">publish-testray-report#2298</a><br/></div></div>

2022-10-13 21:09 UTC, mateussgn commented
ci:test:sf

2022-10-13 21:11 UTC, mateussgn commented
ci:test:relevant

2022-10-13 21:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3346/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3346/jenkins-report.html">here</a>.</b></p>

2022-10-13 21:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5001/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5001/jenkins-report.html">here</a>.</b></p>

2022-10-13 21:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1dcf56d8a945ed677d6db6110a7f54c822adc852">1dcf56d8a945ed677d6db6110a7f54c822adc852</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussgn/liferay-portal/tree/LPS-165005">LPS-165005</a><br/>Branch GIT ID: <a href="https://github.com/mateussgn/liferay-portal/commit/1f004affb4025bd17b04f5cc52b577a282205957">1f004affb4025bd17b04f5cc52b577a282205957</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3346/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3346/jenkins-report.html">here</a>.</h5><pre>     [exec] 
     [exec]     apps/object/object-js-components-web/types
     [exec] 
     [exec] Please commit them.
     [exec] 
     [exec] M modules/apps/object/object-js-components-web/types/src/main/resources/META-INF/resources/utils/api.d.ts
     [exec] 
     [exec] Generating types (25 of 25): @liferay/object-web
     [exec] 
     [exec] ***************
     [exec] *** WARNING ***
     [exec] ***************
     [exec] 
     [exec] Out-of-date TypeScript build artifacts at:
     [exec] 
     [exec]     apps/object/object-web/types
     [exec] 
     [exec] Please commit them.
     [exec] 
     [exec] M modules/apps/object/object-web/types/src/main/resources/META-INF/resources/js/components/ObjectField/useObjectFieldForm.d.ts
     [exec] 
     [exec] Preflight check failed:
     [exec] checkTypeScriptTypeArtifacts() failed: Error: Type generation was successful but 2 projects were out of date. Please commit updated versions of the artifacts in the projects listed above.
     [exec] 
     [exec] Prettier checked 7 files
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2022-10-13 21:14:53.844.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2022-10-13 21:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3346/">test-portal-source-format#3346</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3346/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/1202">liferay-objects#1202</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2006152287">[master] ci:test:sf - mateussgn &gt; liferay-objects - PR#1202 - 2022-10-13[14:10:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/12412/">publish-testray-report#12412</a><br/></div></div>

2022-10-13 21:42 UTC, murilostodolni commented
Just starting reviewing :)

2022-10-14 13:27 UTC, carolmariaabb requested changes
@murilostodolni @mateussgn Great job 🥳 

Please see my comments below.

In addition, could you ask someone to review the FE code? Also, don't we need to create a feature flag at least in the FE code?

Thanks!

2022-10-14 13:27 UTC, carolmariaabb commented on modules/apps/list-type/list-type-service/src/main/java/com/liferay/list/type/service/impl/ListTypeDefinitionLocalServiceImpl.java
> +			String externalReferenceCode)
@murilostodolni @mateussgn `String externalReferenceCode` must come before `listTypeDefinitionId`, following the same order from the `service.xml`

2022-10-14 13:27 UTC, carolmariaabb commented on modules/apps/list-type/list-type-service/src/main/java/com/liferay/list/type/service/impl/ListTypeDefinitionServiceImpl.java
> +			String externalReferenceCode)
@murilostodolni @mateussgn `String externalReferenceCode` must come before `listTypeDefinitionId`, following the same order from the `service.xml`

2022-10-14 13:27 UTC, carolmariaabb commented on modules/apps/object/object-admin-rest-api/src/main/java/com/liferay/object/admin/rest/dto/v1_0/util/ObjectFieldUtil.java
> +				return null;
@mateussgn @murilostodolni Let's buy some space here:
```
if (!StringUtil.equals(
		objectField.getBusinessType(),
		ObjectFieldConstants.BUSINESS_TYPE_PICKLIST)) {

	return null;
}

ListTypeDefinition listTypeDefinition =
	ListTypeDefinitionServiceUtil.getListTypeDefinition(
		objectField.getListTypeDefinitionId());

return listTypeDefinition.getExternalReferenceCode();
```

2022-10-14 13:27 UTC, carolmariaabb commented on modules/apps/object/object-admin-rest-api/src/main/java/com/liferay/object/admin/rest/dto/v1_0/util/ObjectFieldUtil.java
> +						ListTypeDefinitionServiceUtil.getListTypeDefinition(
@mateussgn @murilostodolni can we also change to use the `fetchListTypeDefinition` here?

2022-10-14 13:27 UTC, carolmariaabb commented on modules/apps/object/object-admin-rest-api/src/main/java/com/liferay/object/admin/rest/dto/v1_0/util/ObjectFieldUtil.java
> +						ListTypeDefinitionServiceUtil.getListTypeDefinition(
@mateussgn @murilostodolni It would be better if we could avoid using the `Util` (`ListTypeDefinitionServiceUtil`). Is it possible here?

2022-10-14 17:03 UTC, carolmariaabb commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/dto/v1_0/converter/ObjectFieldDTOConverter.java
> +		StringBuilder listTypeDefinitionERC = new StringBuilder();
@murilostodolni let's talk on monday so you can show me this error

2022-10-14 17:28 UTC, murilostodolni commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/dto/v1_0/converter/ObjectFieldDTOConverter.java
> +		StringBuilder listTypeDefinitionERC = new StringBuilder();
@carolmariaabb i set ListTypeDefinitionExternalReferenceCode with this [example](https://github.com/liferay-objects/liferay-portal/pull/1202/commits/aafe48d18ea0685b2bbb21bbf237a88e09d968a4#r995719584) and work! So, it is not necessary create a `String` or `StringBuilder`

2022-10-14 17:59 UTC, murilostodolni commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/resource/v1_0/ObjectFieldResourceImpl.java
> +					objectField.getListTypeDefinitionExternalReferenceCode());
As aligned in Slack, we let's use `fetchListTypeDefinitionByExternalReferenceCode`

2022-10-14 20:18 UTC, mateussgn commented
ci:close

2022-10-14 20:18 UTC, closed without merging

2022-10-14 20:30 UTC, murilostodolni commented
Resent with changes to: https://github.com/liferay-objects/liferay-portal/pull/1216