LPS-185206 Remove FF endpoint to post Notification Queue Entry
liferay-objects/liferay-portal pull request #2204
Opened 2023-06-05 20:50 UTC by pedro-oliveira446

2023-06-05 20:50 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**object**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-06-05 20:59 UTC, pedro-oliveira446 commented
ci:test:sf

2023-06-05 20:59 UTC, pedro-oliveira446 commented
ci:test:relevant

2023-06-05 21:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3990/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3990/jenkins-report.html">here</a>.</b></p>

2023-06-05 21:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPS-185206">LPS-185206</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/f15426cbab5951fae995d022a8de199e0c45c8b2">f15426cbab5951fae995d022a8de199e0c45c8b2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3990/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3990/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-impl/src/portal.properties expected:&lt;...ER1__NUMBER7__NUMBER[]9__NUMBER4__NUMBER8_...&gt; but was:&lt;...ER1__NUMBER7__NUMBER[8__NUMBER8__NUMBER1__NUMBER6_
     [java]     #
     [java]     feature.flag.LPS-178816=false
     [java] 
     [java]     #
     [java]     # Env: LIFERAY_FEATURE_PERIOD_FLAG_PERIOD__UPPERCASEL__UPPERCASEP__UPPERCASES__MINUS__NUMBER1__NUMBER7__NUMBER]9__NUMBER4__NUMBER8_...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:16.276 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:597: Java returned: 1
      [get] Getting: http://test-1-28/job/test-portal-source-format/3990//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230605140302208.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230605140302208.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1586472834.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2006599325
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 181ms
[junitreport] Deleting: /tmp/null2006599325
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 06-05-2023 14:03:04:663 PDT</pre></details></html>

2023-06-05 21:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4334/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4334/jenkins-report.html">here</a>.</b></p>

2023-06-05 21:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3990/">test-portal-source-format#3990</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3990/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2204">liferay-objects#2204</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340676742">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#2204 - 2023-06-05[13:50:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/15173/">publish-testray-report#15173</a><br/></div></div>

2023-06-05 21:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPS-185206">LPS-185206</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/f15426cbab5951fae995d022a8de199e0c45c8b2">f15426cbab5951fae995d022a8de199e0c45c8b2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4334/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4334/jenkins-report.html">here</a>.</h5></details></html>

2023-06-05 21:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4334/">test-portal-source-format#4334</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4334/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2204">liferay-objects#2204</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340676844">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#2204 - 2023-06-05[14:02:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/3838/">publish-testray-report#3838</a><br/></div></div>

2023-06-06 01:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8493/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8493/jenkins-report.html">here</a>.</b></p>

2023-06-06 01:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/2972/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2972/jenkins-report.html">here</a>.</b></p>

2023-06-06 01:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340803479">EE Development Acceptance (master) - 4583 - 2023-06-05[16:42:20]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8493/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8493/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8493/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The sender branch SHA could not be found on <strong><a href="https://github.com/liferay-objects/liferay-portal/pull/2204">pedro-oliveira446/LPS-185206</a></strong>. The sender branch may have been force pushed or deleted after the pull request test was initiated.</p><pre>fatal: Not a valid branch point: 'a9adad1da9e506de3e5243ee13fb51d3771c7456'.</pre></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/8493/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/8493/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/8493/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-06-06 01:26 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340803479">EE Development Acceptance (master) - 4583 - 2023-06-05[16:42:20]</a></p><details><summary><strong>ci:test:object - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/2972/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2972/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/2972/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The sender branch SHA could not be found on <strong><a href="https://github.com/liferay-objects/liferay-portal/pull/2204">pedro-oliveira446/LPS-185206</a></strong>. The sender branch may have been force pushed or deleted after the pull request test was initiated.</p><pre>fatal: Not a valid branch point: 'a9adad1da9e506de3e5243ee13fb51d3771c7456'.</pre></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/2972/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/2972/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/2972/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-06-06 01:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/9929/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9929/jenkins-report.html">here</a>.</b></p>

2023-06-06 01:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/12099/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12099/jenkins-report.html">here</a>.</b></p>

2023-06-06 06:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 286 out of 304 jobs passed in 5 hours 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340803479">EE Development Acceptance (master) - 4583 - 2023-06-05[16:42:20]</a></p><details><summary><strong>ci:test:object - 286 out of 304 jobs PASSED</strong></summary><div><h4>18 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/9929/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227683/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526255/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208840/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/594225/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/509956/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/161572/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/549689/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545291/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519186/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/161573/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226315/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/411541/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/411542/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/661598/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545287/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526252/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/411543/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/661606/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420711/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/635880/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203448/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545294/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/635881/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/661607/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420712/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/601419/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/661599/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/635875/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545288/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208839/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/549686/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203242/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203446/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/411544/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211098/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526253/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/161576/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/551697/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/601416/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/509960/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420710/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134979/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201825/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223012/">functional-tomcat90-mysql57-jdk8/1/17</a [...]

2023-06-06 06:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/9929/">test-portal-acceptance-pullrequest(master)#9929</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9929/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2204">liferay-objects#2204</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2341092530">[master] ci:test:object - pedro-oliveira446 &gt; liferay-objects - PR#2204 - 2023-06-05[18:30:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/23490/">publish-testray-report#23490</a><br/></div></div>

2023-06-06 06:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 28 out of 29 jobs passed</h3><h3>:x: ci:test:relevant - 133 out of 189 jobs passed in 5 hours 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340803479">EE Development Acceptance (master) - 4583 - 2023-06-05[16:42:20]</a></p><details><summary><strong>ci:test:stable - 28 out of 29 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226381/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227722/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211127/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/175482/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205946/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217692/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215734/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208866/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214850/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203493/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/175483/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215735/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226343/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207661/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202557/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203274/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217695/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223044/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/213353/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/161656/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/635960/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/661689/"><strike>modules-integration-mysql57-jdk8_stable/0/2</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226382/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208865/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/545366/">portal-license-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/213357/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/210219/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203494/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208863/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 133 out of 189 jobs PASSED</strong></summary><div><h4>56 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/12099/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226381/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227722/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226384/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205947/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203272/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/201857/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211127/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569778/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li [...]

2023-06-06 11:53 UTC, carolmariaabb requested changes

2023-06-06 11:53 UTC, carolmariaabb commented on modules/apps/notification/notification-rest-impl/src/main/java/com/liferay/notification/rest/internal/resource/v1_0/NotificationQueueEntryResourceImpl.java
@pedro-oliveira446 please remove the empty lines

```
id =
	serviceBuilderNotificationQueueEntry.
		getNotificationQueueEntryId();
recipients = notificationType.toRecipients(
	notificationRecipient.
		getNotificationRecipientSettings());
recipientsSummary = notificationType.getRecipientSummary(
	serviceBuilderNotificationQueueEntry);
```

2023-06-06 14:27 UTC, pedro-oliveira446 commented
ci:test:sf

2023-06-06 14:27 UTC, pedro-oliveira446 commented
ci:test:object

2023-06-06 14:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/1610/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1610/jenkins-report.html">here</a>.</b></p>

2023-06-06 14:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1ced75d3265746da90dec6e1f6060faa17a39fc5">1ced75d3265746da90dec6e1f6060faa17a39fc5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPS-185206">LPS-185206</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/7f9b360979b7768d5ca88796c5620e3c91203b30">7f9b360979b7768d5ca88796c5620e3c91203b30</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1610/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1610/jenkins-report.html">here</a>.</h5></details></html>

2023-06-06 14:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1610/">test-portal-source-format#1610</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1610/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2204">liferay-objects#2204</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2341653230">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#2204 - 2023-06-06[07:28:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/5602/">publish-testray-report#5602</a><br/></div></div>

2023-06-06 15:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3000/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3000/jenkins-report.html">here</a>.</b></p>

2023-06-06 15:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/6752/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6752/jenkins-report.html">here</a>.</b></p>

2023-06-06 18:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 289 out of 304 jobs passed in 3 hours 7 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4586">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1407401_3000</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1ced75d3265746da90dec6e1f6060faa17a39fc5">1ced75d3265746da90dec6e1f6060faa17a39fc5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b1e26f4397111b36aa8e3778179cc11631584b52">b1e26f4397111b36aa8e3778179cc11631584b52</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2341729838">EE Development Acceptance (master) - 4585 - 2023-06-06[04:57:58]</a></p><details><summary><strong>ci:test:object - 289 out of 304 jobs PASSED</strong></summary><div><h4>15 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3000/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228119/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/510723/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223366/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162655/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636941/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636940/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203618/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662742/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/213655/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636942/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207897/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162649/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602422/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162650/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223364/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203616/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/412658/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/210488/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/570751/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569894/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203954/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/594952/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/569895/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203619/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662748/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/421719/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602423/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/210486/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/412659/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215136/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162651/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218845/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662739/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226652/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602424/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/206250/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/570749/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/187220/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/594949/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526927/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/552680/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https:/ [...]

2023-06-06 19:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3000/">test-portal-acceptance-pullrequest(master)#3000</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3000/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2204">liferay-objects#2204</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2341934181">[master] ci:test:object - pedro-oliveira446 &gt; liferay-objects - PR#2204 - 2023-06-06[08:47:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/5619/">publish-testray-report#5619</a><br/></div></div>

2023-06-06 19:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 29 out of 29 jobs passed</h3><h3>:x: ci:test:relevant - 135 out of 189 jobs passed in 3 hours 23 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4586">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1307401_6752</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1ced75d3265746da90dec6e1f6060faa17a39fc5">1ced75d3265746da90dec6e1f6060faa17a39fc5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b1e26f4397111b36aa8e3778179cc11631584b52">b1e26f4397111b36aa8e3778179cc11631584b52</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2341729838">EE Development Acceptance (master) - 4585 - 2023-06-06[04:57:58]</a></p><details><summary><strong>ci:test:stable - 29 out of 29 jobs PASSED</strong></summary><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 135 out of 189 jobs PASSED</strong></summary><div><h4>54 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/6752/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209157/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202808/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203641/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209159/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/546143/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/213673/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/210499/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218861/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223384/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/662794/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211413/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203636/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/209160/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217970/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/0/1</strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/206267/">functional-tomcat90-mysql57-chrome100-jdk8/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/510757/">functional-tomcat90-mysql57-chrome100-jdk8/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162703/">functional-tomcat90-mysql57-chrome100-jdk8/0/4</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/210497/">functional-tomcat90-mysql57-chrome100-jdk8/0/5</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/213675/">functional-tomcat90-mysql57-chrome100-jdk8/0/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/223383/">functional-tomcat90-mysql57-chrome100-jdk8/0/7</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218859/">functional-tomcat90-mysql57-chrome100-jdk8/0/8</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211412/">functional-tomcat90-mysql57-chrome100-jdk8/0/9</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228135/">functional-tomcat90-mysql57-chrome100-jdk8/0/10</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203975/">functional-tomcat90-mysql57-chrome100-jdk8/0/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162704/">functional-tomcat90-mysql57-chrome100-jdk8/0/12</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/213676/">functional-tomcat90-mysql57-chrome100-jdk8/0/13</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/203640/">functional-tomcat90-mysql57-chrome100-jdk8/0/14</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526962/">functional-tomcat90-mysql57-chrome100-jdk8/0/15</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/412716/">functional-tomcat90-mysql57-chrome100-jdk8/0/16</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202807/">functional-tomcat90-mysql57-chrome100-jdk8/0/17</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/594978/">functional-tomcat90-mysql57-chrome100-jdk8/0/18</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/510758/">functional-tomcat90-mysql57-chrome100-jdk8/0/19</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/228134/">functional-tomcat90-mysql57-chrome100-jdk8/0/20</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/ [...]

2023-06-06 19:21 UTC, murilostodolni approved these changes
LGTM 🎉

2023-06-06 20:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/6752/">test-portal-acceptance-pullrequest(master)#6752</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6752/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2204">liferay-objects#2204</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2342109595">[master] ci:test:relevant - pedro-oliveira446 &gt; liferay-objects - PR#2204 - 2023-06-06[08:53:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/16973/">publish-testray-report#16973</a><br/></div></div>

2023-06-07 12:06 UTC, carolmariaabb approved these changes
LGTM!

2023-06-07 21:30 UTC, pedro-oliveira446 commented
ci:forward:force

2023-06-07 21:30 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-07 21:30 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2023-06-07 21:31 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/395//consoleFull)

2023-06-07 21:32 UTC, closed without merging

2023-06-07 21:32 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/135977
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/395//consoleFull)