LPS-192669 Accounts cannot be deleted if the Account Object has a relationship with an inactive Object
liferay-objects/liferay-portal pull request #2417
Opened 2023-08-07 23:20 UTC by mbowerman

Ticket: [LPS-192669](https://liferay.atlassian.net/browse/LPS-192669)

See [PTR-4182](https://liferay.atlassian.net/browse/PTR-4182) for further context. This seems to be the solution that was decided upon in that PTR.

2023-08-07 23:20 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**object**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-08-07 23:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/4877/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4877/jenkins-report.html">here</a>.</b></p>

2023-08-07 23:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1303/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1303/jenkins-report.html">here</a>.</b></p>

2023-08-07 23:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/2457/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2457/jenkins-report.html">here</a>.</b></p>

2023-08-07 23:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/43a8fc59fac7ddba761602493e22d04eec7b94d4">43a8fc59fac7ddba761602493e22d04eec7b94d4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mbowerman/liferay-portal/tree/LPS-192669">LPS-192669</a><br/>Branch GIT ID: <a href="https://github.com/mbowerman/liferay-portal/commit/1680f95fad7b5ee59281409bdf5cfdaeb69e495f">1680f95fad7b5ee59281409bdf5cfdaeb69e495f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2457/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2457/jenkins-report.html">here</a>.</h5></details></html>

2023-08-07 23:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2457/">test-portal-source-format#2457</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2457/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2417">liferay-objects#2417</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2401258905">[master] ci:test:sf - mbowerman &gt; liferay-objects - PR#2417 - 2023-08-07[16:21:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/9066/">publish-testray-report#9066</a><br/></div></div>

2023-08-07 23:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/43a8fc59fac7ddba761602493e22d04eec7b94d4">43a8fc59fac7ddba761602493e22d04eec7b94d4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/43a8fc59fac7ddba761602493e22d04eec7b94d4">43a8fc59fac7ddba761602493e22d04eec7b94d4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2400442611">EE Development Acceptance (master) - 4730 - 2023-08-04[12:39:32]</a></p><details><summary><strong>ci:test:object - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/4877/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4877/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/4877/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] * Where:
     [exec] Build file '/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-faro/build.gradle' line: 64
     [exec] 
     [exec] * What went wrong:
     [exec] A problem occurred evaluating project ':dxp:apps:osb:osb-faro'.
     [exec] &gt; Could not set unknown property 'portBindings' for task ':dxp:apps:osb:osb-faro:createDocker' of type com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':dxp:apps:osb:osb-faro'.
     [exec]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory\$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
     [exec]   at org.gradle.configuration.DefaultScriptPluginFactory\$ScriptPluginImpl.lambda\$apply\$0(DefaultScriptPluginFactory.java:133)
     [exec]   at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
     [exec]   at org.gradle.configuration.DefaultScriptPluginFactory\$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
     [exec]   at org.gradle.configuration.BuildOperationScriptPlugin\$1.run(BuildOperationScriptPlugin.java:65)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner\$1.execute(DefaultBuildOperationRunner.java:29)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner\$1.execute(DefaultBuildOperationRunner.java:26)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner\$3.execute(DefaultBuildOperationRunner.java:75)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner\$3.execute(DefaultBuildOperationRunner.java:68)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda\$run\$1(DefaultBuildOperationExecutor.java:71)
     [exec]   at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/4877/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/4877/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/4877/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-08-07 23:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/4877/">test-portal-acceptance-pullrequest(master)#4877</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4877/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2417">liferay-objects#2417</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2401265052">[master] ci:test:object - mbowerman &gt; liferay-objects - PR#2417 - 2023-08-07[16:20:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/9069/">publish-testray-report#9069</a><br/></div></div>

2023-08-07 23:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 26 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/43a8fc59fac7ddba761602493e22d04eec7b94d4">43a8fc59fac7ddba761602493e22d04eec7b94d4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/43a8fc59fac7ddba761602493e22d04eec7b94d4">43a8fc59fac7ddba761602493e22d04eec7b94d4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2400442611">EE Development Acceptance (master) - 4730 - 2023-08-04[12:39:32]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1303/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1303/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1303/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] * Where:
     [exec] Build file '/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-faro/build.gradle' line: 64
     [exec] 
     [exec] * What went wrong:
     [exec] A problem occurred evaluating project ':dxp:apps:osb:osb-faro'.
     [exec] &gt; Could not set unknown property 'portBindings' for task ':dxp:apps:osb:osb-faro:createDocker' of type com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':dxp:apps:osb:osb-faro'.
     [exec]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory\$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
     [exec]   at org.gradle.configuration.DefaultScriptPluginFactory\$ScriptPluginImpl.lambda\$apply\$0(DefaultScriptPluginFactory.java:133)
     [exec]   at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
     [exec]   at org.gradle.configuration.DefaultScriptPluginFactory\$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
     [exec]   at org.gradle.configuration.BuildOperationScriptPlugin\$1.run(BuildOperationScriptPlugin.java:65)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner\$1.execute(DefaultBuildOperationRunner.java:29)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner\$1.execute(DefaultBuildOperationRunner.java:26)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner\$3.execute(DefaultBuildOperationRunner.java:75)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner\$3.execute(DefaultBuildOperationRunner.java:68)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
     [exec]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda\$run\$1(DefaultBuildOperationExecutor.java:71)
     [exec]   at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/1303/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/1303/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/1303/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-08-07 23:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1303/">test-portal-acceptance-pullrequest(master)#1303</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1303/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2417">liferay-objects#2417</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2401266609">[master] ci:test:relevant - mbowerman &gt; liferay-objects - PR#2417 - 2023-08-07[16:21:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/25941/">publish-testray-report#25941</a><br/></div></div>

2023-08-08 14:14 UTC, pedro-oliveira446 requested changes
Hi @mbowerman,

we cannot remain all the services of an inactive definiton deployed, this would cause it to be displayed in places it shouldn't be. I believe the best solution would be to remain deployed only the interface we need (ObjectRelatedModelsProvider). 

Should you have any inquiries, please feel free to reach out to us. Thanks!

2023-08-08 15:02 UTC, closed without merging

2023-08-08 15:36 UTC, mbowerman commented
Hello @pedro-oliveira446,

Thank you very much for your review. I have sent a new pull request [here](https://github.com/liferay-objects/liferay-portal/pull/2419) to implement the behavior that you described. Could you please check it when you get a chance and see if this is the right approach?