LPS-174238 Error while changing an Object's ERC when the object has a M:M relationship
liferay-objects/liferay-portal pull request #2761
Opened 2023-10-24 21:05 UTC by diogomelo09

2023-10-24 21:05 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-10-24 21:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c4453e08f5b6ce7d553063b4e144bab5615844ce">c4453e08f5b6ce7d553063b4e144bab5615844ce</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/diogomelo09/liferay-portal/tree/LPS-174238">LPS-174238</a><br/>Branch GIT ID: <a href="https://github.com/diogomelo09/liferay-portal/commit/7ac1c607e74af8b680dc00cf14d6f41502dd0fe2">7ac1c607e74af8b680dc00cf14d6f41502dd0fe2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/4540/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/4540/jenkins-report.html">here</a>.</h5></details></html>

2023-10-25 13:02 UTC, marcelabc commented
Hey @cgmonte ,
I'm assigning this PR to you because it is frontend. Feel comfortable assigning to anybody from your squad :+1:

2023-10-30 17:58 UTC, cgmonte requested changes
Hi, Diogo! Please read my comment as a I think that the suggested fix only hides the real problem. Also, the error displayed in the ticket's attached video is different from the one we are fixing here ("setValues is not a function"). Are you sure we a re dealing with the same problem here? The error in the video suggests a back-end bug: "Reverse object definition cannot be deleted".

2023-10-30 17:58 UTC, cgmonte commented on modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ObjectManagementToolbar.tsx
> +				}
Hey @diogomelo09, thanks for working on this! I see that, with this PR, we are preventing `setValues` from being called and the save still works! How can that be? Either that `setValues` is useless or something that should be set is not being set. The real investigation here is to find out why `setValues` is undefined when the user navigates to tab other then "Details". And also evaluate if the implications of not executing this `setValues`.

2023-11-27 13:03 UTC, alinedoleron commented
I'm closing this PR since this ticket was discarted.
https://liferay.atlassian.net/browse/LPS-174238

2023-11-27 13:03 UTC, closed without merging