LPS-195674 Display date object fields without time
liferay-objects/liferay-portal pull request #2873
Opened 2023-11-21 17:39 UTC by guilhermedcamacho

2023-11-21 17:39 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-21 17:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/6390/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6390/jenkins-report.html">here</a>.</b></p>

2023-11-21 17:48 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c713bcbc1d4e7126ab305e00e9183da9f9c2ff3">7c713bcbc1d4e7126ab305e00e9183da9f9c2ff3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guilhermedcamacho/liferay-portal/tree/LPS-195674">LPS-195674</a><br/>Branch GIT ID: <a href="https://github.com/guilhermedcamacho/liferay-portal/commit/bc54e71fdb338b6efa965c3e586694c5a18da7a3">bc54e71fdb338b6efa965c3e586694c5a18da7a3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6390/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6390/jenkins-report.html">here</a>.</h5></details></html>

2023-11-21 17:52 UTC, guilhermedcamacho commented
ci:test:sf

2023-11-21 17:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6390/">test-portal-source-format#6390</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6390/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2873">liferay-objects#2873</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462953039">[master] ci:test:sf - guilhermedcamacho &gt; liferay-objects - PR#2873 - 2023-11-21[09:40:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/4076/">publish-testray-report#4076</a><br/></div></div>

2023-11-21 17:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c713bcbc1d4e7126ab305e00e9183da9f9c2ff3">7c713bcbc1d4e7126ab305e00e9183da9f9c2ff3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guilhermedcamacho/liferay-portal/tree/LPS-195674">LPS-195674</a><br/>Branch GIT ID: <a href="https://github.com/guilhermedcamacho/liferay-portal/commit/f8c863ac35b38d25cf8db9ce0b01515560f79ec1">f8c863ac35b38d25cf8db9ce0b01515560f79ec1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4687/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4687/jenkins-report.html">here</a>.</h5></details></html>

2023-11-21 17:56 UTC, guilhermedcamacho commented
ci:test:relevant

2023-11-21 17:57 UTC, guilhermedcamacho commented
ci:test:object

2023-11-21 18:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4687/">test-portal-source-format#4687</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4687/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2873">liferay-objects#2873</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2462955035">[master] ci:test:sf - guilhermedcamacho &gt; liferay-objects - PR#2873 - 2023-11-21[09:52:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/17364/">publish-testray-report#17364</a><br/></div></div>

2023-11-21 19:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7554/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7554/jenkins-report.html">here</a>.</b></p>

2023-11-21 19:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8473/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8473/jenkins-report.html">here</a>.</b></p>

2023-11-21 22:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 395 out of 434 jobs passed in 3 hours 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c713bcbc1d4e7126ab305e00e9183da9f9c2ff3">7c713bcbc1d4e7126ab305e00e9183da9f9c2ff3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8bde4e6b402e6873fa80b7a69e0fca6c00bfe570">8bde4e6b402e6873fa80b7a69e0fca6c00bfe570</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463071585">EE Development Acceptance (master) - 180 - 2023-11-21[08:41:42]</a></p><details><summary><strong>ci:test:object - 395 out of 434 jobs PASSED</strong></summary><div><h4>39 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8473/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/782967/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/937063/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/782965/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/838488/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/268902/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/832748/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/782963/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/674740/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/948944/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314736/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792113/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/285364/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/937061/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/705644/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/948948/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/838493/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/864683/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/820435/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792115/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313204/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458809/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/782966/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/674743/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/746310/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/948947/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/730551/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/832751/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458810/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/285366/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328699/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314742/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792122/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/705652/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304104/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458821/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/948955/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/832758/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/832747/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792126/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/768487/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/782980/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458831/">functional-tomcat90-mysql57-jdk8/2/13</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302048/">functional-tomcat90-mysql57-jdk8/2/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/705657/">functional-tomcat90-mysql57-jdk8/2/15</a></li><li><a href=" [...]

2023-11-21 23:20 UTC, MarinhoFeliphe requested changes

2023-11-21 23:20 UTC, MarinhoFeliphe commented on modules/apps/notification/notification-test/src/testIntegration/java/com/liferay/notification/internal/type/test/BaseNotificationTypeTest.java
> +			LocaleUtil.getDefault(), null, BaseNotificationTypeTest.user1);
Hey @guilhermedcamacho, can we replace `BaseNotificationTypeTest.user1` with `user1`?

2023-11-21 23:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 4 hours 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c713bcbc1d4e7126ab305e00e9183da9f9c2ff3">7c713bcbc1d4e7126ab305e00e9183da9f9c2ff3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8bde4e6b402e6873fa80b7a69e0fca6c00bfe570">8bde4e6b402e6873fa80b7a69e0fca6c00bfe570</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463071585">EE Development Acceptance (master) - 180 - 2023-11-21[08:41:42]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7554/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7554/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7554/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/7554/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/7554/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/7554/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-11-22 00:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7554/">test-portal-acceptance-pullrequest(master)#7554</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7554/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2873">liferay-objects#2873</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463184681">[master] ci:test:relevant - guilhermedcamacho &gt; liferay-objects - PR#2873 - 2023-11-21[11:47:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/14465/">publish-testray-report#14465</a><br/></div></div>

2023-11-22 17:15 UTC, guilhermedcamacho commented
ci:test:sf

2023-11-22 17:16 UTC, guilhermedcamacho commented
ci:test:relevant

2023-11-22 17:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6100/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6100/jenkins-report.html">here</a>.</b></p>

2023-11-22 17:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38131bd1c68de68ae139a595824a7acdf2191b2c">38131bd1c68de68ae139a595824a7acdf2191b2c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/guilhermedcamacho/liferay-portal/tree/LPS-195674">LPS-195674</a><br/>Branch GIT ID: <a href="https://github.com/guilhermedcamacho/liferay-portal/commit/ab329e6d3590557db9c0bbb093612ceffa721b12">ab329e6d3590557db9c0bbb093612ceffa721b12</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6100/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6100/jenkins-report.html">here</a>.</h5></details></html>

2023-11-22 17:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6100/">test-portal-source-format#6100</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6100/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2873">liferay-objects#2873</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463604366">[master] ci:test:sf - guilhermedcamacho &gt; liferay-objects - PR#2873 - 2023-11-22[09:15:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/23328/">publish-testray-report#23328</a><br/></div></div>

2023-11-22 19:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4333/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4333/jenkins-report.html">here</a>.</b></p>

2023-11-22 22:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 31 out of 31 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 246 out of 257 jobs passed in 3 hours 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38131bd1c68de68ae139a595824a7acdf2191b2c">38131bd1c68de68ae139a595824a7acdf2191b2c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38131bd1c68de68ae139a595824a7acdf2191b2c">38131bd1c68de68ae139a595824a7acdf2191b2c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463745346">EE Development Acceptance (master) - 185 - 2023-11-22[08:42:54]</a></p><details><summary><strong>ci:test:stable - 31 out of 31 jobs PASSED</strong></summary><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 245 out of 257 jobs PASSED</strong></summary><div><h4>12 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4333/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770180/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/938769/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/329563/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305993/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/834181/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770182/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304716/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/318319/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/270783/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/840109/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/821827/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314219/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/299363/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/675896/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/767255/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334022/">functional-tomcat90-mysql57-chrome100-jdk8/1/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731995/">functional-tomcat90-mysql57-chrome100-jdk8/1/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/840100/">functional-tomcat90-mysql57-chrome100-jdk8/1/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/784554/">functional-tomcat90-mysql57-chrome100-jdk8/1/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770181/">functional-tomcat90-mysql57-chrome100-jdk8/1/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/784553/">functional-tomcat90-mysql57-chrome100-jdk8/1/5</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302720/">functional-tomcat90-mysql57-chrome100-jdk8/1/6</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352257/">functional-tomcat90-mysql57-chrome100-jdk8/1/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/821828/">functional-tomcat90-mysql57-chrome100-jdk8/1/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/767253/">functional-tomcat90-mysql57-chrome100-jdk8/1/9</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352261/">functional-tomcat90-mysql57-chrome100-jdk8/1/10</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269707/">functional-tomcat90-mysql57-chrome100-jdk8/1/11</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/329565/">functional-tomcat90-mysql57-chrome100-jdk8/1/12</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/331797/">functional-tomcat90-mysql57-chrome100-jdk8/1/13</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304714/">functional-tomcat90-mysql57-chrome100-jdk8/1/14</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/306538/">functional-tomcat90-mysql57-chrome100-jdk8/1/15</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/305992/">functional-tomcat90-mysql57-chrome100-jdk8/1/16</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352262/">functional-tomcat90-mysql57-chrome100-jdk8/1/17</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/784562/">functional-tomcat90-mysql57-chrome100-jdk8/1/18</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314217/">functional-tomcat90-mysql57-chrome100-jdk8/1/19</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/732001/">functional-tomcat90-mysql57-chrome100-jdk8/ [...]

2023-11-22 22:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4333/">test-portal-acceptance-pullrequest(master)#4333</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4333/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2873">liferay-objects#2873</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463820978">[master] ci:test:relevant - guilhermedcamacho &gt; liferay-objects - PR#2873 - 2023-11-22[11:10:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8667/">publish-testray-report#8667</a><br/></div></div>

2023-11-22 22:39 UTC, guilhermedcamacho commented
ci:forward

2023-11-22 22:39 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-11-22 22:39 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`
- `ci:test:stable`

2023-11-22 22:45 UTC, guilhermedcamacho commented
ci:stop

2023-11-22 22:46 UTC, guilhermedcamacho commented
Manually forwarded to [brianchandotcom#144227](https://github.com/brianchandotcom/liferay-portal/pull/144227)

2023-11-22 22:46 UTC, closed without merging

2023-11-22 23:03 UTC, guilhermedcamacho commented
ci:help

2023-11-22 23:03 UTC, liferay-continuous-integration commented
## Available CI commands:
#### ci:close
&nbsp;&nbsp;&nbsp;&nbsp;Close the pull request.
#### ci:forward[:force]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request  and forward the pull request to `brianchandotcom` if the required test suites pass for `ci:forward` or complete for `ci:forward:force`.
#### ci:merge[:force]
&nbsp;&nbsp;&nbsp;&nbsp;Merge in the changes from the subrepo. All tests must pass before this command will successfully run. Optionally use the force flag to bypass failed tests.
#### ci:reevaluate:[buildID]
&nbsp;&nbsp;&nbsp;&nbsp;Reevaluate the pull request result from a generated build ID.
#### ci:reopen
&nbsp;&nbsp;&nbsp;&nbsp;Reopen the pull request.
#### ci:stop[:suite]
&nbsp;&nbsp;&nbsp;&nbsp;Stop all currrently running tests. Optionally specify the name of the test suite.
#### ci:test[:suite][:SHA|nocompile|norebase|gist-SHA]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request. Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.
<details><summary><strong>Available test suites:</strong></summary>

- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional-db-partition** - Test acceptance functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-release** - Compile a release bundle and execute acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accessibility** - Test all accessibility tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accessibility-menu** - Test all accessibility menu tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**account** - Test Account tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - Test Analytics Cloud tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-acceptance** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-integration** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-quarantine** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**app-servers** - Test Deployments on App Servers.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test Calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clay** - Test Clay component tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**comment** - Test Comment tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-database** - Test only Commerce Database tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es8-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 8 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-integration** - Test only Commerce integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-upgrade** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**configuration-framework** - Test Configuration Framework component tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**continuous-integration** - Test Continuous Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**cookies** - Test Cookie Preferences tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine-db-partition** - Test Data Engine functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration** - Test only Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration-functional** - Test only functional Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**db-partition** - Test Database Partitioning functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**digital-signature** - Test Digital Signature tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document-antivirus** - Test Antivirus against DM.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test Drools tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-accessibility** - Test Echo (WCM) team accessibility tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-analytics-cloud** - Test segmentation and personalization with Analytics Cloud.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-db-partition** - Test Echo (WCM) team acceptance tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-headless** - Test Echo (WCM) team headless components.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-db-partition** - Test forms functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-functional** - Test only functional forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**friendly-url** - Test Friendly URL tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test all Frontend Infra team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-client-extensions** - Test frontend client extensions tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-data-set** - Test frontend data set tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-dev-exp** - Test frontend developer experience tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-ui** - Test frontend ui tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-walkthrough** - Test frontend walkthrough tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test all headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-builder** - All tests for Headless Builder component.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-builder-functional** - All functional tests for Headless Builder component.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**head [...]

2023-11-22 23:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7578/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7578/jenkins-report.html">here</a>.</b></p>

2023-11-23 01:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 31 out of 31 jobs passed</h3><h3>:x: ci:test:relevant - 244 out of 257 jobs passed in 1 hour 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbb269367a4600f7ac3207c376f2d8865ad8b4e2">cbb269367a4600f7ac3207c376f2d8865ad8b4e2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38131bd1c68de68ae139a595824a7acdf2191b2c">38131bd1c68de68ae139a595824a7acdf2191b2c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463745346">EE Development Acceptance (master) - 185 - 2023-11-22[08:42:54]</a></p><details><summary><strong>ci:test:stable - 31 out of 31 jobs PASSED</strong></summary><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 244 out of 257 jobs PASSED</strong></summary><div><h4>13 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7578/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939316/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/676320/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793778/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/822259/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707732/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/840567/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314521/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/732439/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/840570/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/748338/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/784999/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/767600/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/748327/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/785003/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/676316/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/748328/">functional-tomcat90-mysql57-chrome100-jdk8/1/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/732433/">functional-tomcat90-mysql57-chrome100-jdk8/1/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770701/">functional-tomcat90-mysql57-chrome100-jdk8/1/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/461160/">functional-tomcat90-mysql57-chrome100-jdk8/1/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/461159/">functional-tomcat90-mysql57-chrome100-jdk8/1/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707731/">functional-tomcat90-mysql57-chrome100-jdk8/1/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793773/">functional-tomcat90-mysql57-chrome100-jdk8/1/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950873/">functional-tomcat90-mysql57-chrome100-jdk8/1/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939317/">functional-tomcat90-mysql57-chrome100-jdk8/1/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/785000/">functional-tomcat90-mysql57-chrome100-jdk8/1/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/834638/">functional-tomcat90-mysql57-chrome100-jdk8/1/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/748335/">functional-tomcat90-mysql57-chrome100-jdk8/1/11</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/822256/">functional-tomcat90-mysql57-chrome100-jdk8/1/12</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/461167/">functional-tomcat90-mysql57-chrome100-jdk8/1/13</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/822257/">functional-tomcat90-mysql57-chrome100-jdk8/1/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707739/">functional-tomcat90-mysql57-chrome100-jdk8/1/15</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/822258/">functional-tomcat90-mysql57-chrome100-jdk8/1/16</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950882/">functional-tomcat90-mysql57-chrome100-jdk8/1/17</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793781/">functional-tomcat90-mysql57-chrome100-jdk8/1/18</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/676321/">functional-tomcat90-mysql57-chrome100-jdk8/1/19</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/834636/">functional-tomcat90-mysql57-chrome100-jdk8/1/20</a> [...]

2023-11-23 01:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7578/">test-portal-acceptance-pullrequest(master)#7578</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7578/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2873">liferay-objects#2873</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2463903324">[master] ci:test:relevant - guilhermedcamacho &gt; liferay-objects - PR#2873 - 2023-11-22[15:19:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/14526/">publish-testray-report#14526</a><br/></div></div>