LPS-202859  Test fix| master
liferay-objects/liferay-portal pull request #2895
Opened 2023-11-28 15:07 UTC by leilanyaragao

Jira Issue: https://liferay.atlassian.net/browse/LPS-202859

2023-11-28 15:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-28 15:09 UTC, leilanyaragao commented
ci:test:sf

2023-11-28 15:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5b658dc75b04fc57bd0da2d4c5dbf7defa38ce62">5b658dc75b04fc57bd0da2d4c5dbf7defa38ce62</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/LPS-202859">LPS-202859</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/b04f77e0d34b6d69b7359980b53dfff7457e47d2">b04f77e0d34b6d69b7359980b53dfff7457e47d2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2922/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2922/jenkins-report.html">here</a>.</h5></details></html>

2023-11-28 15:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7809/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7809/jenkins-report.html">here</a>.</b></p>

2023-11-28 15:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2922/">test-portal-source-format#2922</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2922/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2895">liferay-objects#2895</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2466781477">[master] ci:test:sf - leilanyaragao &gt; liferay-objects - PR#2895 - 2023-11-28[07:07:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/21822/">publish-testray-report#21822</a><br/></div></div>

2023-11-28 15:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f5f7c2d638708fe438ed85b7acaf3d419ac1e6bc">f5f7c2d638708fe438ed85b7acaf3d419ac1e6bc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/LPS-202859">LPS-202859</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/b04f77e0d34b6d69b7359980b53dfff7457e47d2">b04f77e0d34b6d69b7359980b53dfff7457e47d2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7809/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7809/jenkins-report.html">here</a>.</h5></details></html>

2023-11-28 15:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7809/">test-portal-source-format#7809</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7809/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2895">liferay-objects#2895</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2466781708">[master] ci:test:sf - leilanyaragao &gt; liferay-objects - PR#2895 - 2023-11-28[07:09:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/29182/">publish-testray-report#29182</a><br/></div></div>

2023-11-28 18:07 UTC, leilanyaragao commented
ci:test:sf

2023-11-28 18:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5069/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5069/jenkins-report.html">here</a>.</b></p>

2023-11-28 18:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f5f7c2d638708fe438ed85b7acaf3d419ac1e6bc">f5f7c2d638708fe438ed85b7acaf3d419ac1e6bc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/LPS-202859">LPS-202859</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/aa6f97b98303e498bfe8318ef6892e59c7b59c28">aa6f97b98303e498bfe8318ef6892e59c7b59c28</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5069/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5069/jenkins-report.html">here</a>.</h5></details></html>

2023-11-28 18:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5069/">test-portal-source-format#5069</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5069/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2895">liferay-objects#2895</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2466876885">[master] ci:test:sf - leilanyaragao &gt; liferay-objects - PR#2895 - 2023-11-28[10:07:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/19457/">publish-testray-report#19457</a><br/></div></div>

2023-11-28 20:51 UTC, seltong requested changes

2023-11-28 20:51 UTC, seltong commented on modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/OpenAPIResourceTest.java
>  	private static Company _company;
if we apply the previous suggestion, please remove the `@DeleteAfterTestRun`

2023-11-28 21:51 UTC, leilanyaragao commented on modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/OpenAPIResourceTest.java
> +	public void setUp() throws Exception {
@seltong I tried this way, but it wasn't possible. I will talk to you on slack.

2023-11-29 13:16 UTC, seltong approved these changes
LGTM :tada:

2023-11-29 18:16 UTC, marcelabc approved these changes
LGTM 🎉

2023-11-29 18:16 UTC, marcelabc commented
ci:test:relevant

2023-11-29 19:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/10031/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10031/jenkins-report.html">here</a>.</b></p>

2023-11-29 23:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 4 out of 4 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 10 out of 13 jobs passed in 3 hours 30 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6849032411624640d37c4b08bbda963d6d6869fa">6849032411624640d37c4b08bbda963d6d6869fa</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c12b85af0da8864ec44b9b0052406ebb42372050">c12b85af0da8864ec44b9b0052406ebb42372050</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467695289">EE Development Acceptance (master) - 207 - 2023-11-29[08:40:54]</a></p><details><summary><strong>ci:test:stable - 4 out of 4 jobs PASSED</strong></summary><details><summary><strong>4 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 9 out of 13 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/10031/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/849861/"><strike>modules-integration-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843140/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843139/">modules-integration-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958720/"><strike>modules-integration-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773128/">modules-integration-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/450013/">modules-integration-mysql57-jdk8/0/5</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/684821/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/793552/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874423/">modules-unit-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/780550/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>unit-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830037/">unit-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958721/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10031/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at c12b85af0da8864ec44b9b0052406ebb42372050:</strong></summary><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/849861//consoleText">modules-integration-mysql57-jdk8/0/0</a><ol><li><details><summary><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/849861/testReport/com.liferay.object.rest.internal.resource.v1_0.test/SystemObjectRelatedObjectEntriesTest">com.liferay.object.rest.internal.resource.v1_0.test.SystemObjectRelatedObjectEntriesTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2467409973/history">Failed 20 of last 25</a></summary><div><ol><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/849861//testReport/com.liferay.object.rest.internal.resource.v1_0.test/SystemObjectRelatedObjectEntriesTest/testGetManyToManySystemObjectRelatedObjectEntries">testGetManyToManySystemObjectRelatedObjectEntries</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/849861/testReport/com.liferay.object.rest.internal.manager.v1_0.test/DefaultObjectEntryManagerImplTest">com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2467409967/history">Failed 25 of last 25</a></summary><div><ol><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/849861//testReport/com.liferay.object.rest.internal.manager.v1_0.test/DefaultObjectEntryManagerImplTest/testDeleteObjectEntry">testDeleteObjectEntry</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/849861/testReport/com.liferay.object.rest.internal.resource.v1_0.test/ObjectEntryResourceTest">com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryResourceTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2467409970/history">Failed 20 of last 25</a></summary><div><ol><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/849861//testReport/com.liferay.object.rest.internal.resource.v1_0.test/ObjectEntryResourceTest/testGetNestedFieldDetailsInRelationshipsWithSystemObjectDefinition">testGetNestedFieldDetailsInRelationshipsWithSystemObjectDefinition</a></li></ol></div></details></li><li>...</li></ol></div></li><li><div><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843140//consoleText">modules-integration-mysql57-jdk8/0/1</a><ol><li><details><summary><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843140/testReport/com.liferay.object.storage.salesforce.internal.rest.manager.v1_0.test/SalesforceObjectEntryManagerImplTest">com.liferay.object.storage.salesforce.internal.rest.manager.v1_0.test.SalesforceObjectEntryManagerImplTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2467409977/history">Failed 25 of last 25</a></summary><div><ol><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/843140//testReport/com.liferay.object.storage.salesforce.internal.rest.manager.v1_0.test/SalesforceObjectEntryManagerImplTest/classMethod">classMethod</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958720//consoleText">modules-integration-mysql57-jdk8/0/3</a><ol><li><details><summary><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958720/testReport/com.liferay.object.service.test/ObjectActionLocalServiceTest">com.liferay.object.service.test.ObjectActionLocalServiceTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2467410013/history">Failed 2 [...]

2023-11-29 23:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/10031/">test-portal-acceptance-pullrequest(master)#10031</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10031/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2895">liferay-objects#2895</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467804492">[master] ci:test:relevant - leilanyaragao &gt; liferay-objects - PR#2895 - 2023-11-29[11:36:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/23128/">publish-testray-report#23128</a><br/></div></div>

2023-11-30 11:01 UTC, carolmariaabb commented
ci:forward

2023-11-30 11:01 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/forward-pullrequest/912//consoleFull)

2023-11-30 11:02 UTC, closed without merging