LPS-200761 - Remove unwanted picklist entries during batch import
liferay-objects/liferay-portal pull request #2921
Opened 2023-12-05 18:00 UTC by G-Sa

Related to: [LPS-200761] (https://liferay.atlassian.net/browse/LPS-200761)

2023-12-05 18:00 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-12-05 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5078/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5078/jenkins-report.html">here</a>.</b></p>

2023-12-05 18:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7cc5a052e4017bee866e7159fa9b1605e02856d3">7cc5a052e4017bee866e7159fa9b1605e02856d3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/G-Sa/liferay-portal/tree/LPS-200761">LPS-200761</a><br/>Branch GIT ID: <a href="https://github.com/G-Sa/liferay-portal/commit/7d7a058ba4c816edc31314e9d9d7cd1c5c1b1335">7d7a058ba4c816edc31314e9d9d7cd1c5c1b1335</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5078/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5078/jenkins-report.html">here</a>.</h5></details></html>

2023-12-11 13:25 UTC, seltong requested changes

2023-12-11 13:25 UTC, seltong commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/dto/v1_0/util/ObjectFieldUtil.java
> +	private static void _addOrUpdateListTypeEntries(
My suggestion for the name of this method is `_addOrDeleteListTypeEntries`, what do you think?

2023-12-11 18:12 UTC, seltong commented
ci:test:sf

2023-12-11 18:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/839d8c833229e39af7aca40aae16059f4be25bee">839d8c833229e39af7aca40aae16059f4be25bee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/G-Sa/liferay-portal/tree/LPS-200761">LPS-200761</a><br/>Branch GIT ID: <a href="https://github.com/G-Sa/liferay-portal/commit/bf883763629c58b774f1784ec96c869b37ccf789">bf883763629c58b774f1784ec96c869b37ccf789</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5096/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5096/jenkins-report.html">here</a>.</h5></details></html>

2023-12-11 18:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5096/">test-portal-source-format#5096</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5096/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2921">liferay-objects#2921</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2472988937">[master] ci:test:sf - G-Sa &gt; liferay-objects - PR#2921 - 2023-12-11[10:12:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/19671/">publish-testray-report#19671</a><br/></div></div>

2023-12-13 18:21 UTC, marcelabc commented
Hey @carolmariaabb 
Could you review this PR, please? :smile:

2023-12-13 19:15 UTC, carolmariaabb requested changes

2023-12-13 19:15 UTC, carolmariaabb commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/dto/v1_0/util/ObjectFieldUtil.java
> +			List<String> serviceBuilderListTypeEntryKeys =
@G-Sa rename it to `listTypeEntryKeys`

2023-12-13 19:15 UTC, carolmariaabb commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/dto/v1_0/util/ObjectFieldUtil.java
> +			for (String key : serviceBuilderListTypeEntryKeys) {
@G-Sa rename it from `key` to `listTypeEntryKey`

2023-12-13 19:42 UTC, G-Sa commented on modules/apps/list-type/list-type-service/src/main/java/com/liferay/list/type/service/impl/ListTypeEntryLocalServiceImpl.java
> +		}
If i call the `listTypeEntryPersistence` to delete here, i'll also need to do the validation already done in the [original](https://github.com/liferay/liferay-portal/blob/master/modules/apps/list-type/list-type-service/src/main/java/com/liferay/list/type/service/impl/ListTypeEntryLocalServiceImpl.java#L83-L97) `deleteListTypeEntry` method.

Other methods in this class also delegate that responsibility to the original method, wouldn't this break the pattern?

2023-12-14 13:25 UTC, carolmariaabb commented
@G-Sa please see https://github.com/liferay-objects/liferay-portal/pull/2950

2023-12-14 13:25 UTC, closed without merging