LPS-202062 Send notification to user admin after reached maximum number of guest user object entry
liferay-objects/liferay-portal pull request #2954
Opened 2023-12-14 21:29 UTC by thallescezar

- LPS-197342 Scroll element into view
- LPS-185524 Replace low bar in languageId
- LPS-185524 Remove aria-label to non-interactive element
- LPS-185524 Add name attribute to locate
- LPS-185524 Adapt front-end tests
- LPS-185524 Modify locators to adapt new markup
- LPS-185524 Modify macros to adapt new markup
- LPS-185524 Modify cases to adapt new markup
- LRQA-84265 Remove unused targets
- LRQA-84265 Remove unused macros
- LPS-203611 Capture all the exceptions for later showing them in the interface
- LPS-203611 SF
- LPS-203645 Fix path
- LRAC-15200 Add a path to locate the name of the pages present on the sankey graphics
- LRAC-15200 Add a path to locate the name of the pages present in the popover
- LRAC-15200 Add to the test hover over the page name in sankey so the popover is displayed to validate the page name completely
- LRAC-15198 Test fix go directly to site page
- LRAC-15199 Search for the team attribute in the list of attributes
- LRAC-15178 Test fix api endpoint response
- LRAC-15182 Test fix remove second portal setup step
- LRAC-15179 Test fix remove unnecessary assertion from test
- LPS-203279 Avoid null pointer exception
- LRAC-15210 Skip unit tests that are failing after removal metal packages
- LRAC-15210 Fix experiment unit tests and add new ones
- LRAC-15210 Avoid to use date at unit test runtime
- LRAC-15210 Update snapshot for SearchableEntitiesTableModal after fix vertical scroll
- LRAC-15210 Fix typescript error
- LPS-203647 Misspelling correction
- LPS-200229 Resolve path traversals in Combo Servlet
- LPS-200229 Ignore multiple / inside paths in Combo Servlet
- LPS-200229 Sublime Sort
- LRAC-14468 changing to default faro users type to regular
- LPS-168512 - Change openWindow() for openModal() to focus upload button when modal is closed
- LPS-168512 - Change close modal call after update image
- LPS-203632 Remove the dependency with object-api by looking for some IF implementation with EditPage capability that the user is allowed to VIEW instead of use the objects services
- LPS-203632 SF remove unused param
- LPS-203632 Move getLayoutElementMapsListMap to FragmentCollectionManager
- LPS-203632 Move hideInputFragments to FragmentCollectionManager as a private method
- LPS-198764 Add CanChooseAIconOnItemAction test
- LPS-198764 Add CanChangeIconOnItemAction test
- LPS-198764 Add CanDeleteASelectedIconOnItemAction test
- LPS-198764 Add CanSeeRecycleAndChangeButtonAfterSelectAIconOnItemAction test
- LPS-198764 Add SearchIconFillsAutomaticallyOnItemAction test
- Revert "LPS-190915 Source formatting"
- Revert "LPS-190915 source-formatter: resolves and normalizes all recently changed files"
- LPS-203636 Removes ignore annotation
- LPS-203636 Fix tests
- LPS-190915 prep next
- POSHI-686 Update default poshi runner version
- POSHI-686 prep next
- POSHI-686 Update poshi-core version
- POSHI-686 prep next
- POSHI-686 LPS-190915 prep next
- LRAC-15205 Remove unused test dependencies
- LPS-203552 In case there is no context item then force a 404 error if the user is not logged in
- LPS-203552 Prevent discovering the DPT URLs using enumeration by responding a 404 error to non-logged user when tries to access to a draft
- LPS-203552 Adds an integration test to assert that a permission user can access both display page template layouts but the Guest user get not found error
- LPS-203559 Move logic to NotificationQueueEntryLocalServiceImpl in order to create a specific folder for each NotificationQueueEntry
- LPS-203559 Delete folder when deleting NotificationQueueEntry
- LPS-203559 Add integration test
- LPS-203587 Remove unused test dependency
- LPS-189573 Add email template files
- LPS-189573 Add email template fields configuration
- LPS-189573 Send email if same TOTP is used more than once
- LPS-189573 Add language keys
- LPS-189573 SF
- LPS-189573 Rename
- LPS-189573 Inline
- LPS-189573 Rename
- LPS-189573 gw buildLang
- LPS-189573 as used
- LPS-201520 Remove readOnly from linkedObjectDefinition in ObjectFolderItem
- LPS-201520 buildRest
- LPS-201520 remove list of folderItems from object folder update
- LPS-201520 buildService
- LPS-201520 Change ObjectFolderResource to manage list of objectDefinitions in object folder
- LPS-201520 Move creation of dependency ObjectDefinitions to Uncategorized object folder
- LPS-201520 Create ImportObjectFolder MVCAction
- LPS-201520 Fix test cases
- LPS-201520 Fix object folder export when there is a linked object definition
- LPS-201520 Add language key for failed object folder import
- LPS-201520 buildLang
- LPS-201520 Fix error message on failed object folder imports
- LPS-201520 as used
- LPS-201520 rename
- LPS-203383 Add permissions action as a drop-down item and as a quick action to the admin management toolbar
- LPS-203383 Add code to open permissions selection modal for the selected layouts
- LPS-203383 Add permissions action to available actions if the FF is enabled and if the user has the permission to perform that action
- LPS-203383 Add feature flag LPS-196847
- LPS-203714 Modify cases to make them stable
- LPS-203710 Correct behavior
- LPS-203711 Add property to enable feature
- LPS-197384 Update macro to configure import settings
- LPS-197384 Add macro to assert object definition
- LPS-197384 Apply macro to test
- LPS-197384 Add dependencies
- LPS-197384 Add test
- LPS-203705 Test fix for endpoint and Schema externalReferenceCode
- LPS-203613 revert some changes about share permission path
- LPS-203617 Update the path to go to notification
- LPS-203699 Update publications-as and publications-db suites
- LRQA-84265 Add targets back as they are still needed
- LPS-200661 Always display container folder name
- LPS-203124 Set the model's defaultLanguageId as languageId if it exists
- LPS-202858 Resolve access issues
- LPS-202858 Be more specific and avoid christmas tree effect
- LPS-202858 This statement is now lying
- LPS-202858 Requestors without view permission should not be told about the user existing
- LPS-202858 Fix SF
- LRAC-14955 update local image to version u104
- LRAC-14955 import petra lang package into bnd file
- LRAC-14955 add the header Provide-Capability into osb-faro-web bnd file in order to keep Faro languange working
- LRAC-14955 util class cannot be a reference
- LRAC-14955 allow virtual hosts to accorded to what we had in u78
- LRAC-14955 prevent privateKey and publicKey from being null
- LPS-193174 Add util to get service via snapshot, prepare for next
- LPS-193174 Apply to replace blocking ServiceProxyFactory usages
- LPS-193714 Directly use ModelResourcePermissionRegistryUtil to replace blocking ServiceProxyFactory usages
- LPS-193174 Remove methods return blocking ServiceProxyFactory in ModelResourcePermissionFactory and PortletResourcePermissionFactory
- LPS-193174 SF, sort
- LPS-193174 Semantic version
- LPS-203519 Update macro to fit the new behavior
- LPS-201877 Use UI to edit the the document
- LPS-203629 Stabilize the tests
- LPS-203623 Update macro to use correct path
- LPS-202537 Ignoring duplicated fields
- LPS-202537 This cannot be null now... is it a breaking change?
- LPS-202537 This was not prepared for random packages
- LPS-202537 Use GetterUtil instead
- LPS-202537 Use path instead, as the application name could be null if the ServletData is implemented manually
- LPS-202537 SF
- LPS-202537 Is this accurate?
- LRQA-82397 Fix test for running locally
- LRQA-82397 Modify test to assert tables are added to external data source
- LRQA-84516 Add NoErrorOnNodeStartupIfCacheManagerNotReady test
- LRQA-84516 Add option to skip success message assert to perform other action during execution
- LRAC-15226 Remove CustomEventsSettings#CustomEventIsShownInAC from acceptance tests
- LRQA-84518 Add CanChangeBundleSymbolicNameForDSModule test
- LRQA-84688 Wait for modal to close when adding portal instance in UI
- LPS-201226 Remove product team owned tests from upgrade test suite
- LPS-201226 Add test.properties file
- LPS-201226 Remove portal configuration tests [...]

2023-12-14 21:29 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-12-14 21:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/2344/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2344/jenkins-report.html">here</a>.</b></p>

2023-12-14 21:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6af76e46fccdeab086dc5da2bd0f08cbddbfa39a">6af76e46fccdeab086dc5da2bd0f08cbddbfa39a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPS-202062">LPS-202062</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/95eae1c5661a5b629d6b1e0bbcfcdc8aaa7a451c">95eae1c5661a5b629d6b1e0bbcfcdc8aaa7a451c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2344/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2344/jenkins-report.html">here</a>.</h5></details></html>

2023-12-14 21:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2344/">test-portal-source-format#2344</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2344/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2954">liferay-objects#2954</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2474731369">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#2954 - 2023-12-14[13:29:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/9923/">publish-testray-report#9923</a><br/></div></div>

2023-12-15 02:10 UTC, guilhermedcamacho requested changes
Hey @thallescezar , I left some comments, please take a look.
In addition to them, it would be nice to combine the last three commits into just one.

2023-12-15 02:10 UTC, guilhermedcamacho commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java
> +	private void _sendNotificationToAdminUsers(
I think we can rename this method to `_sendNotificationToInstanceAdministrators`

2023-12-15 02:10 UTC, guilhermedcamacho commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java
> +		TransactionInvokerUtil.invoke(
We must send all notifications in the same transaction, so move the administrator user IDs loop to the body of the TransactionInvokerUtil

2023-12-15 02:10 UTC, guilhermedcamacho commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java
> +			ObjectDefinition objectDefinition)
Please sort these parameters alphabetically

2023-12-15 20:20 UTC, thallescezar commented
ci:test:sf

2023-12-15 20:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/7319/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7319/jenkins-report.html">here</a>.</b></p>

2023-12-15 20:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fe21d146b828e552256af87f3d4c6ef6c3fd43f7">fe21d146b828e552256af87f3d4c6ef6c3fd43f7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPS-202062">LPS-202062</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/f4bcb37ab7be05a2e53dea3351656a8bdf614173">f4bcb37ab7be05a2e53dea3351656a8bdf614173</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7319/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7319/jenkins-report.html">here</a>.</h5></details></html>

2023-12-15 20:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7319/">test-portal-source-format#7319</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7319/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2954">liferay-objects#2954</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2475190885">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#2954 - 2023-12-15[12:20:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/28643/">publish-testray-report#28643</a><br/></div></div>

2023-12-19 13:15 UTC, thallescezar commented
ci:test:sf

2023-12-19 13:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6886/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6886/jenkins-report.html">here</a>.</b></p>

2023-12-19 13:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/06eeef7207154be1ba6c215c260f89565d6e7eca">06eeef7207154be1ba6c215c260f89565d6e7eca</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPS-202062">LPS-202062</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/c9dd005778dea1443fab0b36da3f3ec8fc679674">c9dd005778dea1443fab0b36da3f3ec8fc679674</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6886/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6886/jenkins-report.html">here</a>.</h5></details></html>

2023-12-19 13:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6886/">test-portal-source-format#6886</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6886/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2954">liferay-objects#2954</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2476469623">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#2954 - 2023-12-19[05:15:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/4101/">publish-testray-report#4101</a><br/></div></div>

2023-12-19 16:37 UTC, thallescezar commented
ci:test:relevant

2023-12-19 16:37 UTC, thallescezar commented
ci:test:object

2023-12-19 16:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11029/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11029/jenkins-report.html">here</a>.</b></p>

2023-12-19 16:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/4682/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4682/jenkins-report.html">here</a>.</b></p>

2023-12-19 19:17 UTC, guilhermedcamacho requested changes

2023-12-19 19:17 UTC, guilhermedcamacho commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectEntryServiceTest.java
> +					getDeliveredUserNotificationEvents(
For performance reasons, can we use the correlated method `getDeliveredUserNotificationEventsCount` here?

2023-12-19 19:17 UTC, guilhermedcamacho commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java
> +	private void _sendNotificationToAdminUsers(
Did you have a chance to rename this method?

2023-12-19 19:17 UTC, guilhermedcamacho commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java
> +			ObjectDefinition objectDefinition)
Did you have a chance to sort these parameters?

2023-12-19 19:17 UTC, guilhermedcamacho commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java
> +		TransactionInvokerUtil.invoke(
Did you have a chance to change this?

2023-12-19 19:17 UTC, guilhermedcamacho commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java
> +				Role role = _roleLocalService.getRole(
Did you have a chance to change this?

2023-12-19 19:17 UTC, guilhermedcamacho commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectEntryServiceTest.java
> +				_userNotificationLocalService.getUserNotificationEventsCount(
In the scenario above you used the _userNotificationLocalService.getDeliveredUserNotificationEvents method to check for notifications, so it seems to me that to maintain consistency you should also use the getDeliveredUserNotificationEventsCount method here, am I right?

2023-12-19 19:18 UTC, guilhermedcamacho commented
ci:stop

2023-12-19 19:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 403 out of 448 jobs passed in 2 hours 41 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/256">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_11029</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b3ead6aec5df0ba7948ec5c1ef36da0904385b66">b3ead6aec5df0ba7948ec5c1ef36da0904385b66</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/401e2fa3ed32b578dccd9ae073abcd4024bb7c94">401e2fa3ed32b578dccd9ae073abcd4024bb7c94</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2476519578">EE Development Acceptance (master) - 254 - 2023-12-19[01:45:58]</a></p><details><summary><strong>ci:test:object - 403 out of 448 jobs PASSED</strong></summary><div><h4>45 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11029/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801837/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495055/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/813325/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315915/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/848025/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334315/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/330819/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975165/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313591/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862856/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/469325/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/330545/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/330820/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/817209/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862859/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738516/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346605/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738517/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/779021/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/848029/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/330651/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/345888/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/892541/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973337/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973338/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334500/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975168/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320661/"><strike>functional-tomcat90-mysql57-jdk8/1/24</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862866/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/469334/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/756860/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870151/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703446/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315918/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975177/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/345893/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/813343/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/779019/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334506/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281317/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/785232/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a href="https [...]

2023-12-19 19:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11029/">test-portal-acceptance-pullrequest(master)#11029</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11029/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2954">liferay-objects#2954</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2476769435">[master] ci:test:object - thallescezar &gt; liferay-objects - PR#2954 - 2023-12-19[08:37:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/23890/">publish-testray-report#23890</a><br/></div></div>

2023-12-19 19:33 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 82 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b3ead6aec5df0ba7948ec5c1ef36da0904385b66">b3ead6aec5df0ba7948ec5c1ef36da0904385b66</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/4682/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4682/jenkins-report.html">here</a>.</b></p><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/4682/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/4682/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/4682/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-12-19 19:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/4682/">test-portal-acceptance-pullrequest(master)#4682</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4682/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2954">liferay-objects#2954</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2476772377">[master] ci:test:relevant - thallescezar &gt; liferay-objects - PR#2954 - 2023-12-19[08:37:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/9985/">publish-testray-report#9985</a><br/></div></div>

2023-12-19 20:09 UTC, thallescezar commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java
> +				Role role = _roleLocalService.getRole(
Didn't move it because I need that logic to check if all the admin users already received a notification.

2023-12-20 03:29 UTC, closed without merging

2023-12-20 03:29 UTC, guilhermedcamacho commented
See #2969