LPS-197871 Inconsistency in the Treeview sidebar
liferay-objects/liferay-portal pull request #2959
Opened 2023-12-18 14:29 UTC by Artartur

Related Issue: [LPS-197871](https://liferay.atlassian.net/browse/LPS-197871)

2023-12-18 14:30 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-12-18 14:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/7384/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7384/jenkins-report.html">here</a>.</b></p>

2023-12-18 14:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 15 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0cfcadcda31a5582e0248945f6d9472bd2d1dca2">0cfcadcda31a5582e0248945f6d9472bd2d1dca2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Artartur/liferay-portal/tree/LPS-197871">LPS-197871</a><br/>Branch GIT ID: <a href="https://github.com/Artartur/liferay-portal/commit/9f4e1e75f015e41553dac4aa5298861c68ea1a21">9f4e1e75f015e41553dac4aa5298861c68ea1a21</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7384/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7384/jenkins-report.html">here</a>.</h5></details></html>

2023-12-18 14:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7384/">test-portal-source-format#7384</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7384/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2959">liferay-objects#2959</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2475868891">[master] ci:test:sf - Artartur &gt; liferay-objects - PR#2959 - 2023-12-18[06:30:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/4085/">publish-testray-report#4085</a><br/></div></div>

2023-12-20 17:03 UTC, marcelabc commented
Hey @danvb112 
Could you review this PR, please? :smile:

2023-12-21 15:05 UTC, Artartur commented
ci:test:sf

2023-12-21 15:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5126/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5126/jenkins-report.html">here</a>.</b></p>

2023-12-21 15:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/85e3a009e7820b0ef6412770d8793935982a5179">85e3a009e7820b0ef6412770d8793935982a5179</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Artartur/liferay-portal/tree/LPS-197871">LPS-197871</a><br/>Branch GIT ID: <a href="https://github.com/Artartur/liferay-portal/commit/2dd2142737a561f6ec50d10c55378093771b3672">2dd2142737a561f6ec50d10c55378093771b3672</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5126/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5126/jenkins-report.html">here</a>.</h5></details></html>

2023-12-21 15:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5126/">test-portal-source-format#5126</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5126/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/2959">liferay-objects#2959</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2477935493">[master] ci:test:sf - Artartur &gt; liferay-objects - PR#2959 - 2023-12-21[07:05:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2477935493<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/19915/">publish-testray-report#19915</a><br/></div></div>

2023-12-28 20:02 UTC, rebsilva commented
just started reviewing :cherry_blossom:

2024-01-03 19:31 UTC, rebsilva requested changes
i've tested the PR and it is working fine, but some changes need to be made on the code. also this PR will conflict with this issue https://github.com/liferay-objects/liferay-portal/pull/2924 so i'll wait to make the changes and the rebase after this is on master

2024-01-03 19:31 UTC, rebsilva commented on modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ModelBuilder/LeftSidebar/LeftSidebar.scss
>  			.lfr-objects__model-builder-left-sidebar-show-folders-button {
also needs to change the color of the separator line bellow the _other folders_

2024-01-04 19:34 UTC, danvb112 commented on modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ModelBuilder/types.ts
> +	kebabOptions: any[];
Good catch @rebsilva! Thanks!

2024-01-04 19:40 UTC, danvb112 commented on modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ViewObjectDefinitions/objectDefinitionUtil.ts
> +				const newDeleteObjectDefinition = await deleteObjectDefinition({
Hey @rebsilva, I think we can put here and above `deletedObjectDefinition`, it makes more sense to me, what do you think?

2024-01-04 19:41 UTC, danvb112 commented on modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ViewObjectDefinitions/objectDefinitionUtil.ts
> +								deleteObjectDefinition: true,
@rebsilva, since here is a boolean state, to show the deleteObjectDefinition modal, I think this name is ok

2024-01-04 20:04 UTC, danvb112 commented
Sent to: https://github.com/liferay-objects/liferay-portal/pull/3006

2024-01-04 20:04 UTC, closed without merging

2024-01-05 12:23 UTC, rebsilva commented on modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ViewObjectDefinitions/objectDefinitionUtil.ts
> +								deleteObjectDefinition: true,
since it's a boolean state, makes sense to stay the way it is, thanks for letting me know!