LPS-205115 Update link on UserNotificationEvent to redirect user to System Settings.
liferay-objects/liferay-portal pull request #3028
Opened 2024-01-10 21:06 UTC by thallescezar

Related issue: https://liferay.atlassian.net/browse/LPS-205028

2024-01-10 21:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-01-10 21:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/5159/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/5159/jenkins-report.html">here</a>.</b></p>

2024-01-10 21:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4c26168fc6afe7e7b589a4be2f4537e2d7d0d7c1">4c26168fc6afe7e7b589a4be2f4537e2d7d0d7c1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPS-205115">LPS-205115</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/80b02bcd11ba928a5f5784cb3200a187e931f66c">80b02bcd11ba928a5f5784cb3200a187e931f66c</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/5159/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/5159/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/object/object-web/src/test/java/com/liferay/object/web/internal/notifications/ObjectUserNotificationsHandlerTest.java expected:&lt;...URLProvider.class);
     [java] [  private final ObjectDefinition _objectDefinition = Mockito.mock(
     [java]     ObjectDefinition.class);
     [java]   private ObjectUserNotificationsHandler _objectUserNotificationsHandler;
     [java]   private PortletURL _portletURL;
     [java]   private PortletURLBuilder.PortletURLStep _portletURLStep;
     [java]   private final RequestBackedPortletURLFactory
     [java]     _requestBackedPortletURLFactory = Mockito.mock(
     [java]       RequestBackedPortletURLFactory.class);
     [java]   private final ServiceContext _serviceContext = Mockito.mock(
     [java]     ServiceContext.class);]
     [java]   private final User...&gt; but was:&lt;...URLProvider.class);
     [java] [
     [java]   private final ObjectDefinition _objectDefinition = Mockito.mock(
     [java]     ObjectDefinition.class);
     [java] 
     [java]   private ObjectUserNotificationsHandler _objectUserNotificationsHandler;
     [java] 
     [java]   private PortletURL _portletURL;
     [java] 
     [java]   private PortletURLBuilder.PortletURLStep _portletURLStep;
     [java] 
     [java]   private final RequestBackedPortletURLFactory
     [java]     _requestBackedPortletURLFactory = Mockito.mock(
     [java]       RequestBackedPortletURLFactory.class);
     [java] 
     [java]   private final ServiceContext _serviceContext = Mockito.mock(
     [java]     ServiceContext.class);
     [java] ]
     [java]   private final User...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:458)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:291)
[stopwatch] [run.batch.test.action: 3:22.782 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-15/job/test-portal-source-format/5159//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240110131228940.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240110131228940.txt</pre></details></html>

2024-01-10 21:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/5159/">test-portal-source-format#5159</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/5159/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3028">liferay-objects#3028</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2486561909">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#3028 - 2024-01-10[13:06:54]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2486561909<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/4463/">publish-testray-report#4463</a><br/></div></div>

2024-01-10 21:31 UTC, thallescezar commented
ci:test:sf

2024-01-10 21:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/5154/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5154/jenkins-report.html">here</a>.</b></p>

2024-01-10 21:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4c26168fc6afe7e7b589a4be2f4537e2d7d0d7c1">4c26168fc6afe7e7b589a4be2f4537e2d7d0d7c1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPS-205115">LPS-205115</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/a315e65bbab4d056a0620c2e78b77c13487da6f2">a315e65bbab4d056a0620c2e78b77c13487da6f2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/5154/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5154/jenkins-report.html">here</a>.</h5></details></html>

2024-01-10 21:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/5154/">test-portal-source-format#5154</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5154/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3028">liferay-objects#3028</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2486570675">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#3028 - 2024-01-10[13:31:39]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2486570675<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/18905/">publish-testray-report#18905</a><br/></div></div>

2024-01-11 14:39 UTC, thallescezar commented
ci:test:object

2024-01-11 14:39 UTC, thallescezar commented
ci:test:relevant

2024-01-11 14:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9021/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9021/jenkins-report.html">here</a>.</b></p>

2024-01-11 14:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9023/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9023/jenkins-report.html">here</a>.</b></p>

2024-01-11 17:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 424 out of 450 jobs passed in 2 hours 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0629149307c6dae0e5a19c14b56365f90013ffeb">0629149307c6dae0e5a19c14b56365f90013ffeb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0629149307c6dae0e5a19c14b56365f90013ffeb">0629149307c6dae0e5a19c14b56365f90013ffeb</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2486789106">EE Development Acceptance (master) - 302 - 2024-01-10[16:49:52]</a></p><details><summary><strong>ci:test:object - 424 out of 450 jobs PASSED</strong></summary><div><h4>26 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9021/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/777549/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/490703/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/777548/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322130/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353009/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828740/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803372/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322745/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/819766/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/882467/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337714/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319535/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352640/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308729/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/819768/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280868/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995138/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/911774/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375597/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353419/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801643/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353011/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339193/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/297324/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320037/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322132/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762596/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/289228/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995147/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/329056/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280869/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/353423/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375601/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352643/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803382/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828745/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322749/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803371/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/518592/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/819782/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377472/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/723226/">functional-tomcat90-mysql57-jdk8/2/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/911785/">functional-tomcat90-mysql57-jdk8/2/14</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/777563/">functional-tomcat90-mysql57-jdk8/2/15</a></li><li><a href="https [...]

2024-01-11 17:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9021/">test-portal-acceptance-pullrequest(master)#9021</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9021/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3028">liferay-objects#3028</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2487011420">[master] ci:test:object - thallescezar &gt; liferay-objects - PR#3028 - 2024-01-11[06:39:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2487011420<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/18935/">publish-testray-report#18935</a><br/></div></div>

2024-01-11 18:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 31 out of 31 jobs passed</h3><h3>:x: ci:test:relevant - 367 out of 431 jobs passed in 3 hours 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0629149307c6dae0e5a19c14b56365f90013ffeb">0629149307c6dae0e5a19c14b56365f90013ffeb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0629149307c6dae0e5a19c14b56365f90013ffeb">0629149307c6dae0e5a19c14b56365f90013ffeb</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2486789106">EE Development Acceptance (master) - 302 - 2024-01-10[16:49:52]</a></p><details><summary><strong>ci:test:stable - 31 out of 31 jobs PASSED</strong></summary><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 367 out of 431 jobs PASSED</strong></summary><div><h4>64 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9023/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/911805/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339830/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339202/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/834868/"><strike>functional-smoke-tomcat90-db2115-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/308738/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/518617/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803464/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762708/"><strike>functional-smoke-tomcat90-oracle193-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/819788/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322204/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/868396/"><strike>functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/868415/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/834864/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762627/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/882496/">functional-tomcat90-mysql57-chrome100-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803402/">functional-tomcat90-mysql57-chrome100-jdk8/1/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828755/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/1/1</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352649/">functional-tomcat90-mysql57-chrome100-jdk8/1/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280874/">functional-tomcat90-mysql57-chrome100-jdk8/1/3</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343968/">functional-tomcat90-mysql57-chrome100-jdk8/1/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/801680/">functional-tomcat90-mysql57-chrome100-jdk8/1/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995168/">functional-tomcat90-mysql57-chrome100-jdk8/1/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/819797/">functional-tomcat90-mysql57-chrome100-jdk8/1/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/723244/">functional-tomcat90-mysql57-chrome100-jdk8/1/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/868408/">functional-tomcat90-mysql57-chrome100-jdk8/1/9</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/297330/">functional-tomcat90-mysql57-chrome100-jdk8/1/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803398/">functional-tomcat90-mysql57-chrome100-jdk8/1/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/518612/">functional-tomcat90-mysql57-chrome100-jdk8/1/12</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320045/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/1/13</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377473/">functional-tomcat90-mysql57-chrome100-jdk8/1/14</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343463/"><strike>functional-tomcat90-mysql57-chrome100-jdk8/1/15</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339201/">functional-tomcat90-mysql57-chrome100-jdk8/1/16</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375604/">functional-tomcat90-mysql57-chrome100-jdk8/1/17</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/882492/">functional-tomcat90-mysql57-chrome100-jdk8/1/18</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/337722/">functional-tomcat90-mysql57-chrome100-jdk8/1/19</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-accept [...]

2024-01-11 18:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9023/">test-portal-acceptance-pullrequest(master)#9023</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9023/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3028">liferay-objects#3028</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2487041683">[master] ci:test:relevant - thallescezar &gt; liferay-objects - PR#3028 - 2024-01-11[06:39:57]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2487041683<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/18937/">publish-testray-report#18937</a><br/></div></div>

2024-01-15 20:10 UTC, MarinhoFeliphe requested changes
Hey @thallescezar I've asked small changes, the most are related to unit tests where you've done a very nice job BTW, thanks for covering all cases of the class you changed I really appreciate this.

About the test try to create the verifications we've talked today.

Thanks for your hard work :tada:

2024-01-15 20:10 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/test/java/com/liferay/object/web/internal/notifications/ObjectUserNotificationsHandlerTest.java
> +	public void testGetLinkWhenNotificationIsRelatedToObjectEntries()
Rename to  `testGetLinkWhenObjectEntryHasNotDisplayPageFriendlyURL`

2024-01-15 20:10 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/test/java/com/liferay/object/web/internal/notifications/ObjectUserNotificationsHandlerTest.java
> +	public void testGetLinkWhenNotificationIsCreatedAfterGuestUserAddEntryThatExceedsLimits()
Rename this to `testGetLinkWhenGuestUserObjectEntrySubmissionsExceedsLimits`

2024-01-15 20:10 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/test/java/com/liferay/object/web/internal/notifications/ObjectUserNotificationsHandlerTest.java
> +					Mockito.mockStatic(PortalUtil.class)) {
Please do the same in the method above

2024-01-15 20:10 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/test/java/com/liferay/object/web/internal/notifications/ObjectUserNotificationsHandlerTest.java
> +				Assert.assertTrue(true);
Please do the same in the method above

2024-01-15 20:10 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/test/java/com/liferay/object/web/internal/notifications/ObjectUserNotificationsHandlerTest.java
> +				factoryUtilMockedStatic = Mockito.mockStatic(
Rename `factoryUtilMockedStatic` to `requestBackedPortletURLFactoryUtilMockedStatic`

Thanks!

2024-01-15 20:10 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/test/java/com/liferay/object/web/internal/notifications/ObjectUserNotificationsHandlerTest.java
> +	}
Hey @thallescezar please apply my suggestion below:

```java
	public void testGetLinkWhenObjectEntryHasDisplayPageFriendlyURL()
		throws Exception {

		Mockito.when(
			_assetDisplayPageFriendlyURLProvider.getFriendlyURL(
				Mockito.any(InfoItemReference.class),
				Mockito.any(ThemeDisplay.class))
		).thenReturn(
			"http://localhost:8080/web/l/54321"
		);

		Assert.assertEquals(
			"http://localhost:8080/web/l/54321",
			_objectUserNotificationsHandler.getLink(
				_userNotificationEvent, _serviceContext));
	}
```

Thanks for covering this case as well!

2024-01-15 20:10 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/notifications/ObjectUserNotificationsHandler.java
> +			"/configuration_admin/edit_configuration"
Hey @thallescezar keep `"/object_entries/edit_object_entry"` here,

Thank you!

2024-01-17 21:59 UTC, MarinhoFeliphe commented
Resent here: https://github.com/liferay-objects/liferay-portal/pull/3055

Nice job @thallescezar!! :tada:

2024-01-17 21:59 UTC, closed without merging