LPS-204337  Enable Navigation to the Options of the Panel Link and Account Restricted Field Using the Arrow Keys
liferay-objects/liferay-portal pull request #3078
Opened 2024-01-29 14:51 UTC by igor-franca

Related Issue: [LPS-204337](https://liferay.atlassian.net/browse/LPS-204337)

2024-01-29 14:51 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-01-29 14:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/2678/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2678/jenkins-report.html">here</a>.</b></p>

2024-01-29 14:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2678/">test-portal-source-format#2678</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2678/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3078">liferay-objects#3078</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2532136835">[master] ci:test:sf - igor-franca &gt; liferay-objects - PR#3078 - 2024-01-29[06:51:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2532136835<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/11532/">publish-testray-report#11532</a><br/></div></div>

2024-01-29 22:01 UTC, rebsilva commented
this will be reviewed after the model builder prioritization bugs

2024-02-02 12:52 UTC, marcelabc commented
Hey @danvb112, 
can you help and review this one?
I believe this would help a lot @rebsilva because she had some PRs to review :heart_decoration:

2024-02-02 13:14 UTC, rebsilva commented
i think maybe i'll have some time at the end of the day to review this, i'll let you know about it @danvb112; also thanks a lot @marcelabc for the help and concern! :purple_heart:

2024-02-06 20:00 UTC, danvb112 requested changes
Hey @igor-franca, I have one suggestion, fell free to ask me anything :smile:

2024-02-06 20:00 UTC, danvb112 commented on modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ObjectDetails/ScopeContainer.tsx
> -
Hey @igor-franca, I encountered a bug when trying to change the scope and link category of the panel multiple times using the keyboard, unfortunately this is a common problem with the Picker component, the best way to resolve this is to quickly remove the component from the screen and place it again, forcing the component to rerender. 

So I suggest you create a new state (`loadingPanelLinkSelect` for example) at the top of the component, and in the existing useEffet you can manage the state:


```tsx
	useEffect(() => {
		setPanelCategoryKey(
			values.scope === 'company' ? companies : sites,
			values.panelCategoryKey as string
		);

		setLoadingPanelLinkSelect(true);

		setTimeout(() => setLoadingPanelLinkSelect(false), 100);
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [values.scope, companies, sites]);
```

then add the state to make the condition here and place the loading indicator.

2024-02-08 22:44 UTC, igor-franca commented
ci:test:sf

2024-02-08 22:44 UTC, igor-franca commented
ci:stop

2024-02-08 22:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/6564/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/6564/jenkins-report.html">here</a>.</b></p>

2024-02-08 22:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7d2acf9f5135c7e3e5d6fcead88cfd2e9e5f19be">7d2acf9f5135c7e3e5d6fcead88cfd2e9e5f19be</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPS-204337">LPS-204337</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/f1f1f7da4a24bf7cc2616729e9cd4759662fa231">f1f1f7da4a24bf7cc2616729e9cd4759662fa231</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/6564/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/6564/jenkins-report.html">here</a>.</h5></details></html>

2024-02-08 22:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/6564/">test-portal-source-format#6564</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/6564/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3078">liferay-objects#3078</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2536701057">[master] ci:test:sf - igor-franca &gt; liferay-objects - PR#3078 - 2024-02-08[14:46:05]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2536701057<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/4903/">publish-testray-report#4903</a><br/></div></div>

2024-02-09 20:31 UTC, igor-franca commented
Hey, @danvb112. After clarifying some [doubts](https://liferay.slack.com/archives/C049XG98GQL/p1707334836231499) with the platform experience team, we discovered that it was a bug in Clay. And a fix has just been submitted. Therefore, this will be available in the next release. Does it make sense to add this workaround to the master? Since it will be available in the next release along with the Clay fix?

2024-02-15 18:19 UTC, igor-franca commented
As discussed [here](https://liferay.slack.com/archives/C049XG98GQL/p1707334836231499), an issue was identified in Clay, which has now been resolved. After the release of the next release of clay, this behavior should be fixed.

2024-02-15 18:19 UTC, closed without merging