LPD-15603 Get portalURL variable from http request
liferay-objects/liferay-portal pull request #3102
Opened 2024-02-06 14:42 UTC by devpedrotavares

Follow up on: https://github.com/brianchandotcom/liferay-portal/pull/146944

2024-02-06 14:42 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-02-06 14:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/8879/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8879/jenkins-report.html">here</a>.</b></p>

2024-02-06 14:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/eec70a72200c795a2f751b3cac78948855b8ba95">eec70a72200c795a2f751b3cac78948855b8ba95</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/devpedrotavares/liferay-portal/tree/LPD-15603">LPD-15603</a><br/>Branch GIT ID: <a href="https://github.com/devpedrotavares/liferay-portal/commit/40e74c38b3f43f18c5c36343eaec2d091ab29291">40e74c38b3f43f18c5c36343eaec2d091ab29291</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8879/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8879/jenkins-report.html">here</a>.</h5></details></html>

2024-02-06 14:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8879/">test-portal-source-format#8879</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8879/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3102">liferay-objects#3102</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535368492">[master] ci:test:sf - devpedrotavares &gt; liferay-objects - PR#3102 - 2024-02-06[06:43:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2535368492<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/34160/">publish-testray-report#34160</a><br/></div></div>

2024-02-06 18:19 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-02-06 18:19 UTC, marcelabc commented on modules/apps/object/object-service/src/main/java/com/liferay/object/internal/servlet/filter/ObjectActionContextFilter.java
> +public class ObjectActionContextFilter extends BaseFilter {
As we discussed on Slack, rename this class to `ObjectDefinitionRESTContextPathFilter`

2024-02-06 18:39 UTC, devpedrotavares commented
ci:test:sf

2024-02-06 18:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6985/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6985/jenkins-report.html">here</a>.</b></p>

2024-02-06 18:43 UTC, marcelabc approved these changes
LGTM 🎉

2024-02-06 18:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5cd9b9d7fb5332ad7593caa307e433a35796070">e5cd9b9d7fb5332ad7593caa307e433a35796070</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/devpedrotavares/liferay-portal/tree/LPD-15603">LPD-15603</a><br/>Branch GIT ID: <a href="https://github.com/devpedrotavares/liferay-portal/commit/4a63a062ba657de5a898c35b698a28492701b277">4a63a062ba657de5a898c35b698a28492701b277</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6985/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6985/jenkins-report.html">here</a>.</h5></details></html>

2024-02-06 18:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6985/">test-portal-source-format#6985</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6985/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3102">liferay-objects#3102</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535526344">[master] ci:test:sf - devpedrotavares &gt; liferay-objects - PR#3102 - 2024-02-06[10:39:29]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2535526344<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/4201/">publish-testray-report#4201</a><br/></div></div>

2024-02-06 19:03 UTC, devpedrotavares commented
ci:test:relevant

2024-02-06 19:03 UTC, devpedrotavares commented
ci:test:object

2024-02-07 11:11 UTC, marcelabc commented
ci:test:relevant

2024-02-07 11:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/8601/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8601/jenkins-report.html">here</a>.</b></p>

2024-02-07 11:17 UTC, marcelabc commented
ci:test:object

2024-02-07 11:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9332/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9332/jenkins-report.html">here</a>.</b></p>

2024-02-07 14:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/8601/">test-portal-acceptance-pullrequest(master)#8601</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8601/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3102">liferay-objects#3102</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535862192">[master] ci:test:relevant - devpedrotavares &gt; liferay-objects - PR#3102 - 2024-02-07[03:12:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2535862192<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/17494/">publish-testray-report#17494</a><br/></div></div>

2024-02-07 14:14 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 423 out of 448 jobs passed in 2 hours 56 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5cd9b9d7fb5332ad7593caa307e433a35796070">e5cd9b9d7fb5332ad7593caa307e433a35796070</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5cd9b9d7fb5332ad7593caa307e433a35796070">e5cd9b9d7fb5332ad7593caa307e433a35796070</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535608297">EE Development Acceptance (master) - 350 - 2024-02-06[08:41:44]</a></p><details><summary><strong>ci:test:object - 423 out of 448 jobs PASSED</strong></summary><div><h4>25 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9332/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334193/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519998/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/831319/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390946/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357173/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894219/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807158/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352937/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/925840/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/365371/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357992/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519997/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/306513/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/349148/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357995/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/306518/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352941/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/349149/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/341078/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357176/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334191/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390952/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/289572/"><strike>functional-tomcat90-mysql57-jdk8/1/19</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/365372/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357994/"><strike>functional-tomcat90-mysql57-jdk8/1/21</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/306517/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300422/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/349147/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300426/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300428/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/300427/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352949/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352948/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352950/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390960/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/289576/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334195/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/352936/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/520011/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023968/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320539/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807171/">functional-tomcat90-mysql57-jdk8/2/13</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807172/">functional-tomcat90-mysql57-jdk8/2/14</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388028/">functional-tomcat90-mysql57-jdk8/2/15</a>< [...]

2024-02-07 14:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9332/">test-portal-acceptance-pullrequest(master)#9332</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9332/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3102">liferay-objects#3102</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535869827">[master] ci:test:object - devpedrotavares &gt; liferay-objects - PR#3102 - 2024-02-07[03:17:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2535869827<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/19689/">publish-testray-report#19689</a><br/></div></div>

2024-02-07 16:15 UTC, devpedrotavares commented
ci:report:2535862192

2024-02-07 16:16 UTC, devpedrotavares commented
ci:report:2535869827

2024-02-07 16:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>2535862192</b>.</p><p>Job Link: <a href="https://test-1-29.liferay.com/job/generate-testray-csv/57/">generate-testray-csv</a></p>

2024-02-07 16:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>2535869827</b>.</p><p>Job Link: <a href="https://test-1-29.liferay.com/job/generate-testray-csv/58/">generate-testray-csv</a></p>

2024-02-07 16:18 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>2535869827</b>.</p><p>Job Link: <a href="https://test-1-29.liferay.com/job/generate-testray-csv/58/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-29.liferay.com/userContent/jobs/generate-testray-csv/builds/58/testray-results.csv">Testray CSV</a></p>

2024-02-07 16:19 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>2535862192</b>.</p><p>Job Link: <a href="https://test-1-29.liferay.com/job/generate-testray-csv/57/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-29.liferay.com/userContent/jobs/generate-testray-csv/builds/57/testray-results.csv">Testray CSV</a></p>

2024-02-07 16:25 UTC, devpedrotavares commented
ci:forward:force

2024-02-07 16:25 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-02-07 16:25 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-02-07 16:27 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-21.liferay.com/job/forward-pullrequest/537//consoleFull)

2024-02-07 16:27 UTC, closed without merging

2024-02-07 16:27 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/147032
[Console](https://test-1-21.liferay.com/job/forward-pullrequest/537//consoleFull)