[TS] LPD-18823 Add integration test
liferay-objects/liferay-portal pull request #3164
Opened 2024-03-13 15:47 UTC by evibudai

Hi Team,

https://liferay.atlassian.net/browse/LPD-18823

I'm sending the additional integration test to review.

Thanks!

2024-03-13 15:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/5578/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5578/jenkins-report.html">here</a>.</b></p>

2024-03-13 15:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/677c02b645bfe63027e738a7bbc62641a3e5cdbf">677c02b645bfe63027e738a7bbc62641a3e5cdbf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evibudai/liferay-portal/tree/LPD-18823-master-2">LPD-18823-master-2</a><br/>Branch GIT ID: <a href="https://github.com/evibudai/liferay-portal/commit/30f849aabf431495d9d9acbbbe98a3ba5575be9d">30f849aabf431495d9d9acbbbe98a3ba5575be9d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/5578/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5578/jenkins-report.html">here</a>.</h5></details></html>

2024-03-13 15:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/5578/">test-portal-source-format#5578</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5578/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3164">liferay-objects#3164</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2549525573">[master] ci:test:sf - evibudai &gt; liferay-objects - PR#3164 - 2024-03-13[08:47:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2549525573<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/20538/">publish-testray-report#20538</a><br/></div></div>

2024-03-13 18:07 UTC, G-Sa requested changes
Hey @evibudai i noticed these, can you take a look please?!

2024-03-14 13:50 UTC, G-Sa approved these changes
Lgtm :tada:

2024-03-14 14:55 UTC, carolmariaabb requested changes

2024-03-14 14:55 UTC, carolmariaabb commented on modules/apps/object/object-admin-rest-test/src/testIntegration/java/com/liferay/object/admin/rest/resource/v1_0/test/ObjectDefinitionResourceTest.java
> +
@evibudai please simply the code to:

```
// Account entry update with null objectDefinitionId2

accountEntryObjectDefinition.setExternalReferenceCode(
	RandomTestUtil.randomString());
accountEntryObjectDefinition.setTitleObjectFieldName(
	"type");

ObjectRelationship objectRelationship =
	accountEntryObjectDefinition.getObjectRelationships()[0];

objectRelationship.setObjectDefinitionId2((Long)null);

ObjectDefinition putAccountEntryObjectDefinition =
	objectDefinitionResource.putObjectDefinition(
		accountEntryObjectDefinition.getId(),
		accountEntryObjectDefinition);

Assert.assertEquals(
	accountEntryObjectDefinition.getExternalReferenceCode(),
	putAccountEntryObjectDefinition.getExternalReferenceCode());
Assert.assertEquals(
	accountEntryObjectDefinition.getTitleObjectFieldName(),
	putAccountEntryObjectDefinition.getTitleObjectFieldName());

objectRelationship =
	putAccountEntryObjectDefinition.getObjectRelationships()[0];

Assert.assertNotNull(objectRelationship.getObjectDefinitionId2());

```

My changes:
- I reused the existing variable `accountEntryObjectDefinition`. 
- I ordered alphabetically: `externalReferenceCode` before `titleObjectFieldName`. 
- In the `Assert.assertEquals`, we must place the expected result before the actual result.

Futhermore, after we do:

```
ObjectRelationship objectRelationship =
	accountEntryObjectDefinition.getObjectRelationships()[0];

objectRelationship.setObjectDefinitionId2((Long)null);
```
we don't need to do:

```
accountEntryObjectDefinition.setObjectRelationships(
	new ObjectRelationship[]{objectRelationship});
```

the `objectRelationship` is already the same object inside the `accountEntryObjectDefinition` object.

Thanks!

2024-03-18 13:10 UTC, evibudai commented
@carolmariaabb thanks for the review! I pushed the changes.

2024-03-18 13:22 UTC, carolmariaabb approved these changes

2024-03-18 13:22 UTC, carolmariaabb commented
ci:forward

2024-03-18 13:22 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-03-18 13:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/7050/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/7050/jenkins-report.html">here</a>.</b></p>

2024-03-18 13:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f50c77fb9bcd84b00452277340c59bf7684d3982">f50c77fb9bcd84b00452277340c59bf7684d3982</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evibudai/liferay-portal/tree/LPD-18823-master-2">LPD-18823-master-2</a><br/>Branch GIT ID: <a href="https://github.com/evibudai/liferay-portal/commit/a73f7aac4b9c35583e77374b4e29ed119401ddd1">a73f7aac4b9c35583e77374b4e29ed119401ddd1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/7050/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/7050/jenkins-report.html">here</a>.</h5></details></html>

2024-03-18 13:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/7050/">test-portal-source-format#7050</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/7050/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3164">liferay-objects#3164</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2551615468">[master] ci:test:sf - evibudai &gt; liferay-objects - PR#3164 - 2024-03-18[06:23:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2551615468<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/4267/">publish-testray-report#4267</a><br/></div></div>

2024-03-18 13:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5357/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5357/jenkins-report.html">here</a>.</b></p>

2024-03-18 15:17 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5357//consoleFull)

2024-03-18 15:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5357/">test-portal-acceptance-pullrequest(master)#5357</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5357/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3164">liferay-objects#3164</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2551693014">[master] ci:test:relevant - evibudai &gt; liferay-objects - PR#3164 - 2024-03-18[06:31:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2551693014<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/11764/">publish-testray-report#11764</a><br/></div></div>

2024-03-18 15:37 UTC, liferay-continuous-integration commented
Error has occurred while forwarding pull request to `brianchandotcom`.
Please try again later or contact the CI team for assistance.
See console log for details: [Full Console](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5357//consoleFullconsoleText)

2024-03-18 16:34 UTC, carolmariaabb commented
ci:forward

2024-03-19 10:43 UTC, carolmariaabb commented
ci:forward

2024-03-19 10:43 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-03-19 10:43 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-03-19 10:44 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/1617//consoleFull)

2024-03-19 10:46 UTC, closed without merging

2024-03-19 10:46 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/148321
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/1617//consoleFull)