LPD-20833 Increase pageSize limit to 2000 for Object Proxy Salesforce
liferay-objects/liferay-portal pull request #3179
Opened 2024-03-18 21:12 UTC by jairmedeiros

Related issue: https://liferay.atlassian.net/browse/LPD-20833

2024-03-18 21:12 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-03-18 21:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/2913/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2913/jenkins-report.html">here</a>.</b></p>

2024-03-18 21:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0dc1b57f064056dcdf4bdaed76cf565ed2e175f1">0dc1b57f064056dcdf4bdaed76cf565ed2e175f1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jairmedeiros/liferay-portal/tree/LPD-20835">LPD-20835</a><br/>Branch GIT ID: <a href="https://github.com/jairmedeiros/liferay-portal/commit/a34093f5d4b2ef78833ac9c55431ffe6eef9c18e">a34093f5d4b2ef78833ac9c55431ffe6eef9c18e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2913/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2913/jenkins-report.html">here</a>.</h5></details></html>

2024-03-18 21:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2913/">test-portal-source-format#2913</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2913/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3179">liferay-objects#3179</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2551877507">[master] ci:test:sf - jairmedeiros &gt; liferay-objects - PR#3179 - 2024-03-18[14:12:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2551877507<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/12030/">publish-testray-report#12030</a><br/></div></div>

2024-03-28 21:30 UTC, MarinhoFeliphe requested changes
Hey @jairmedeiros see my comments!

Thanks for your hard work! :tada:

2024-03-28 21:30 UTC, MarinhoFeliphe commented on modules/apps/object/object-storage-salesforce/src/main/java/com/liferay/object/storage/salesforce/internal/rest/manager/v1_0/SalesforceObjectEntryManagerImpl.java
> +	}
Hey @jairmedeiros since we're using this only in one place we can move this logic to the place we're using.

Thanks!

2024-03-28 21:30 UTC, MarinhoFeliphe commented on modules/apps/object/object-storage-salesforce/src/main/java/com/liferay/object/storage/salesforce/internal/rest/manager/v1_0/SalesforceObjectEntryManagerImpl.java
> +			Arrays.asList("OwnerId", "CreatedDate", "LastModifiedDate", "Id"));
@jairmedeiros can we sort this external reference codes?

2024-03-28 21:30 UTC, MarinhoFeliphe commented on modules/apps/object/object-storage-salesforce/src/main/java/com/liferay/object/storage/salesforce/internal/rest/manager/v1_0/SalesforceObjectEntryManagerImpl.java
> +		String objectFieldExternalReferenceCodes = StringUtil.merge(
Rename this variable to `objectFieldExternalReferenceCodesString`

Thanks!

2024-04-08 21:48 UTC, jpince commented
@MarinhoFeliphe can you or someone on the team please review Jair's changes? Thank you!

2024-04-08 22:42 UTC, MarinhoFeliphe requested changes
Hey @jpince I've reviewed, please see my comments,

Thank you!

2024-04-08 22:42 UTC, MarinhoFeliphe commented on modules/apps/object/object-storage-salesforce/src/main/java/com/liferay/object/storage/salesforce/internal/rest/manager/v1_0/SalesforceObjectEntryManagerImpl.java
> +	}
Hi @jpince,

These two methods (`_getObjectFieldByExternalReferenceCode` and `_getObjectFieldByName`) seems to not being used, could you please ask for someone remove it and resend?

Thank you!

2024-04-08 22:42 UTC, MarinhoFeliphe commented on modules/apps/object/object-storage-salesforce-test/src/testIntegration/java/com/liferay/object/storage/salesforce/internal/rest/manager/v1_0/test/SalesforceObjectEntryManagerImplTest.java
> +				"format(Due_date__c) FormattedDueDate"
Hi @jpince,

it seems to not being used as well, could you please remove@

Thanks!

2024-04-08 22:45 UTC, jpince commented
@kylembischof @ryanschuhler @thaynam can someone please review Feliphe's comments?

2024-04-17 19:09 UTC, MarinhoFeliphe commented
I'm closing this pull request, when the modifications are done please reopen and let know.

Thank you!

2024-04-17 19:09 UTC, closed without merging