LPD-17467 Importing Object - Custom State Flow doesn't resemble JSON file
liferay-objects/liferay-portal pull request #3233
Opened 2024-04-11 13:14 UTC by diogomelo09

2024-04-11 13:14 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-04-11 13:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3022/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3022/jenkins-report.html">here</a>.</b></p>

2024-04-11 13:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/da0175e6eb9c61af012cedeaf57411a1c8933ebd">da0175e6eb9c61af012cedeaf57411a1c8933ebd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/diogomelo09/liferay-portal/tree/LPD-17467">LPD-17467</a><br/>Branch GIT ID: <a href="https://github.com/diogomelo09/liferay-portal/commit/8b873fcd1290a3cc511ee85be5d1f0ef7741f797">8b873fcd1290a3cc511ee85be5d1f0ef7741f797</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3022/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3022/jenkins-report.html">here</a>.</h5></details></html>

2024-04-11 13:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3022/">test-portal-source-format#3022</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3022/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3233">liferay-objects#3233</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2560108026">[master] ci:test:sf - diogomelo09 &gt; liferay-objects - PR#3233 - 2024-04-11[06:14:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2560108026<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/12440/">publish-testray-report#12440</a><br/></div></div>

2024-04-11 20:28 UTC, linolaoj requested changes
Hi @diogomelo09, can we change the order of the if clause here to make it easier to read? (I mean avoiding the negative !)

2024-04-12 19:43 UTC, diogomelo09 commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/dto/v1_0/util/ObjectFieldSettingUtil.java
> +			if (!(objectFieldSetting.getValue() instanceof ObjectStateFlow)) {
Done!! :white_check_mark:

2024-04-12 21:30 UTC, linolaoj commented
ci:test:object

2024-04-15 15:33 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 428 out of 443 jobs passed in 2 hours 41 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/495">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1297401_9574</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8300a7a327213eff2813626cb359c3aa7d7ad4a4">8300a7a327213eff2813626cb359c3aa7d7ad4a4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/da0175e6eb9c61af012cedeaf57411a1c8933ebd">da0175e6eb9c61af012cedeaf57411a1c8933ebd</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2560115516">EE Development Acceptance (master) - 488 - 2024-04-11[00:38:15]</a></p><details><summary><strong>ci:test:object - 428 out of 443 jobs PASSED</strong></summary><div><h4>15 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/9574/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/391327/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804233/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/878451/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/860355/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/361012/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322452/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378533/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/363616/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/613130/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378534/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343300/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804230/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/363617/"><strike>functional-tomcat90-mysql57-jdk8/1/9</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/613131/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357142/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377045/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/917675/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343303/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804234/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378537/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/414201/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358377/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/386807/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357997/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/329098/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/362777/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/391326/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385349/">functional-tomcat90-mysql57-jdk8/1/24</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/417499/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357148/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385355/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/363628/">functional-tomcat90-mysql57-jdk8/2/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/414207/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/878459/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385356/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/980088/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377043/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/362776/">functional-tomcat90-mysql57-jdk8/2/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/613144/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/343311/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378547/">functional-tomcat90-mysql57-jdk8/2/12</a></li><li><a hre [...]

2024-04-15 15:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/9574/">test-portal-acceptance-pullrequest(master)#9574</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9574/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3233">liferay-objects#3233</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2560875783">[master] ci:test:object - diogomelo09 &gt; liferay-objects - PR#3233 - 2024-04-15[05:51:56]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2560875783<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/21230/">publish-testray-report#21230</a><br/></div></div>

2024-04-15 17:21 UTC, linolaoj commented
Hi @diogomelo09 can you please check the test PublishAPIApplication#CanGetPublishedStatusInResponse. If it is not related then you can forward the pr.

2024-05-15 21:55 UTC, rijema commented
New PR associated with the JIRA ticket.

2024-05-15 21:55 UTC, closed without merging