LPD-22496
liferay-objects/liferay-portal pull request #3249
Opened 2024-04-17 14:39 UTC by vngoliveira

[LPP-53445](https://liferay.atlassian.net/browse/LPP-53445)
[LPD-22496](https://liferay.atlassian.net/browse/LPD-22496)

2024-04-17 14:40 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-04-17 14:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2910/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2910/jenkins-report.html">here</a>.</b></p>

2024-04-17 14:44 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/72a3f310b17aca466fe2591e92b6f1db6cf4fcf2">72a3f310b17aca466fe2591e92b6f1db6cf4fcf2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-22496_">LPD-22496_</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/a057082272ba53b22778eb1a9afe1ced46abf003">a057082272ba53b22778eb1a9afe1ced46abf003</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2910/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2910/jenkins-report.html">here</a>.</h5><pre>Started by remote host 172.16.168.126
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building remotely on test-1-33-29 (slave-1) in workspace /opt/dev/projects/github/liferay-jenkins-ee
[liferay-jenkins-ee] \$ /bin/bash -e -x /tmp/jenkins16981699605475610719.sh
+ echo 'Initialize Jenkins slave node.'
Initialize Jenkins slave node.
+ cd /opt/dev/projects/github/liferay-jenkins-ee
+ curl -o ./_common.sh http://mirrors.lax.liferay.com/github.com/liferay/liferay-jenkins-ee/_common.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19349  100 19349    0     0  1715k      0 --:--:-- --:--:-- --:--:-- 1889k
+ source ./_common.sh
++ MAX_THREADS=1
++ [[ test-1-33-29.lax.liferay.com =~ cloud-.* ]]
++ [[ slave-1 test-1-33-29 =~ .*win.* ]]
++ ROOT_DIR=
++ GIT_REPOSITORIES_ROOT_DIR=/opt/dev/projects/github
++ JENKINS_REPO_PATH=/opt/dev/projects/github/liferay-jenkins-ee
+++ cat /opt/dev/projects/github/liferay-jenkins-ee/git-directories.json
++ GIT_DIRECTORIES_JSON_CONTENT='[
  \{
    "branch": "master",
    "name": "alloy-ui",
    "repository": "alloy-ui"
  \},
  \{
    "branch": "master-private",
    "name": "com-liferay-commerce-private",
    "repository": "com-liferay-commerce-private"
  \},
  \{
    "branch": "7.0.x",
    "name": "com-liferay-osb-asah-private",
    "repository": "com-liferay-osb-asah-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-customer-private",
    "repository": "com-liferay-osb-customer-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-faro-private",
    "repository": "com-liferay-osb-faro-private"
  \},
  \{
    "branch": "7.0.x-private",
    "name": "com-liferay-osb-lcs-private",
    "repository": "com-liferay-osb-lcs-private"
  \},
  \{
    "branch": "7.0.x-private",
    "name": "com-liferay-osb-loop-private",
    "repository": "com-liferay-osb-loop-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-testray-private",
    "repository": "com-liferay-osb-testray-private"
  \},
  \{
    "branch": "master",
    "name": "liferay-binaries-cache-2017",
    "repository": "liferay-binaries-cache-2017"
  \},
  \{
    "branch": "master",
    "name": "liferay-blade-samples",
    "repository": "liferay-blade-samples"
  \},
  \{
    "branch": "master",
    "name": "liferay-binaries-cache-2020",
    "repository": "liferay-binaries-cache-2020"
  \},
  \{
    "branch": "master",</pre></details></html>

2024-04-17 15:10 UTC, vngoliveira commented
ci:test:sf

2024-04-17 15:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/7648/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7648/jenkins-report.html">here</a>.</b></p>

2024-04-17 15:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/72a3f310b17aca466fe2591e92b6f1db6cf4fcf2">72a3f310b17aca466fe2591e92b6f1db6cf4fcf2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-22496_">LPD-22496_</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/41dc106715aaeb39bc39af621865f0f0d2811ab6">41dc106715aaeb39bc39af621865f0f0d2811ab6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7648/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7648/jenkins-report.html">here</a>.</h5><pre>Started by remote host 172.16.168.126
[EnvInject] - Loading node environment variables.
Building remotely on cloud-10-0-110-135 (slave-1) in workspace /opt/dev/projects/github/liferay-jenkins-ee
[liferay-jenkins-ee] \$ /bin/bash -e -x /tmp/jenkins7656751034202537539.sh
+ echo 'Initialize Jenkins slave node.'
Initialize Jenkins slave node.
+ cd /opt/dev/projects/github/liferay-jenkins-ee
+ curl -o ./_common.sh http://mirrors.lax.liferay.com/github.com/liferay/liferay-jenkins-ee/_common.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19349  100 19349    0     0  2258k      0 --:--:-- --:--:-- --:--:-- 2361k
+ source ./_common.sh
++ MAX_THREADS=1
++ [[ cloud-10-0-110-135.lax.liferay.com =~ cloud-.* ]]
++ MAX_THREADS=5
++ [[ cloud-10-0-110-135 slave-1 =~ .*win.* ]]
++ ROOT_DIR=
++ GIT_REPOSITORIES_ROOT_DIR=/opt/dev/projects/github
++ JENKINS_REPO_PATH=/opt/dev/projects/github/liferay-jenkins-ee
+++ cat /opt/dev/projects/github/liferay-jenkins-ee/git-directories.json
++ GIT_DIRECTORIES_JSON_CONTENT='[
  \{
    "branch": "master",
    "name": "alloy-ui",
    "repository": "alloy-ui"
  \},
  \{
    "branch": "master-private",
    "name": "com-liferay-commerce-private",
    "repository": "com-liferay-commerce-private"
  \},
  \{
    "branch": "7.0.x",
    "name": "com-liferay-osb-asah-private",
    "repository": "com-liferay-osb-asah-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-customer-private",
    "repository": "com-liferay-osb-customer-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-faro-private",
    "repository": "com-liferay-osb-faro-private"
  \},
  \{
    "branch": "7.0.x-private",
    "name": "com-liferay-osb-lcs-private",
    "repository": "com-liferay-osb-lcs-private"
  \},
  \{
    "branch": "7.0.x-private",
    "name": "com-liferay-osb-loop-private",
    "repository": "com-liferay-osb-loop-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-testray-private",
    "repository": "com-liferay-osb-testray-private"
  \},
  \{
    "branch": "master",
    "name": "liferay-binaries-cache-2017",
    "repository": "liferay-binaries-cache-2017"
  \},
  \{
    "branch": "master",
    "name": "liferay-blade-samples",
    "repository": "liferay-blade-samples"
  \},
  \{
    "branch": "master",
    "name": "liferay-binaries-cache-2020",
    "repository": "liferay-binaries-cache-2020"
  \},
  \{</pre></details></html>

2024-04-17 15:26 UTC, vngoliveira commented
ci:test:sf

2024-04-17 15:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2691/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2691/jenkins-report.html">here</a>.</b></p>

2024-04-17 15:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/72a3f310b17aca466fe2591e92b6f1db6cf4fcf2">72a3f310b17aca466fe2591e92b6f1db6cf4fcf2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-22496_">LPD-22496_</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/e956c6d56825ae1daf5286b698b080b7c37eb785">e956c6d56825ae1daf5286b698b080b7c37eb785</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2691/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2691/jenkins-report.html">here</a>.</h5><pre>Started by remote host 172.16.168.126
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building remotely on test-1-25-76 (slave-2) in workspace /opt/dev/projects/github/liferay-jenkins-ee
[liferay-jenkins-ee] \$ /bin/bash -e -x /tmp/jenkins14007484444617020202.sh
+ echo 'Initialize Jenkins slave node.'
Initialize Jenkins slave node.
+ cd /opt/dev/projects/github/liferay-jenkins-ee
+ curl -o ./_common.sh http://mirrors.lax.liferay.com/github.com/liferay/liferay-jenkins-ee/_common.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19349  100 19349    0     0  1391k      0 --:--:-- --:--:-- --:--:-- 1453k
+ source ./_common.sh
++ MAX_THREADS=1
++ [[ test-1-25-76.lax.liferay.com =~ cloud-.* ]]
++ [[ test-1-25-76 slave-2 =~ .*win.* ]]
++ ROOT_DIR=
++ GIT_REPOSITORIES_ROOT_DIR=/opt/dev/projects/github
++ JENKINS_REPO_PATH=/opt/dev/projects/github/liferay-jenkins-ee
+++ cat /opt/dev/projects/github/liferay-jenkins-ee/git-directories.json
++ GIT_DIRECTORIES_JSON_CONTENT='[
  \{
    "branch": "master",
    "name": "alloy-ui",
    "repository": "alloy-ui"
  \},
  \{
    "branch": "master-private",
    "name": "com-liferay-commerce-private",
    "repository": "com-liferay-commerce-private"
  \},
  \{
    "branch": "7.0.x",
    "name": "com-liferay-osb-asah-private",
    "repository": "com-liferay-osb-asah-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-customer-private",
    "repository": "com-liferay-osb-customer-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-faro-private",
    "repository": "com-liferay-osb-faro-private"
  \},
  \{
    "branch": "7.0.x-private",
    "name": "com-liferay-osb-lcs-private",
    "repository": "com-liferay-osb-lcs-private"
  \},
  \{
    "branch": "7.0.x-private",
    "name": "com-liferay-osb-loop-private",
    "repository": "com-liferay-osb-loop-private"
  \},
  \{
    "branch": "master",
    "name": "com-liferay-osb-testray-private",
    "repository": "com-liferay-osb-testray-private"
  \},
  \{
    "branch": "master",
    "name": "liferay-binaries-cache-2017",
    "repository": "liferay-binaries-cache-2017"
  \},
  \{
    "branch": "master",
    "name": "liferay-blade-samples",
    "repository": "liferay-blade-samples"
  \},
  \{
    "branch": "master",
    "name": "liferay-binaries-cache-2020",
    "repository": "liferay-binaries-cache-2020"
  \},
  \{
    "branch": "master",</pre></details></html>

2024-04-17 15:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2691/">test-portal-source-format#2691</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2691/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3249">liferay-objects#3249</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2561523618">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3249 - 2024-04-17[08:26:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2561523618<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/10877/">publish-testray-report#10877</a><br/></div></div>

2024-04-17 16:29 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-04-17 16:29 UTC, marcelabc commented on modules/apps/object/object-rest-impl/src/main/java/com/liferay/object/rest/internal/manager/v1_0/DefaultObjectEntryManagerImpl.java
> +					start, end, sorts, fields),
Can you inline the variable fields in this usage? Check SF, please.
(since there is only 1 use of the variable, we should inline it)

2024-04-17 17:22 UTC, vngoliveira commented
ci:test:sf

2024-04-17 17:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">here</a>.</b></p>

2024-04-17 17:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9782f6caf3b1b2e7165f62d140ec7a573bf512f5">9782f6caf3b1b2e7165f62d140ec7a573bf512f5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-22496_">LPD-22496_</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/85fbdc1488db953d9cc1088b12846adcd9c49a30">85fbdc1488db953d9cc1088b12846adcd9c49a30</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">here</a>.</h5></details></html>

2024-04-17 17:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format#4952</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3249">liferay-objects#3249</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2561580275">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3249 - 2024-04-17[10:23:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2561580275<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/19285/">publish-testray-report#19285</a><br/></div></div>

2024-04-18 01:01 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-04-18 13:43 UTC, vngoliveira commented
ci:test:sf

2024-04-18 13:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/4964/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4964/jenkins-report.html">here</a>.</b></p>

2024-04-18 13:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9bb99cce5d5e9bdd8c1d9facaa8ee230ba1a0d83">9bb99cce5d5e9bdd8c1d9facaa8ee230ba1a0d83</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-22496_">LPD-22496_</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/0040ff707135f0918aef365d33a7ce30d8d03d5a">0040ff707135f0918aef365d33a7ce30d8d03d5a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4964/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4964/jenkins-report.html">here</a>.</h5></details></html>

2024-04-18 13:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4964/">test-portal-source-format#4964</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4964/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3249">liferay-objects#3249</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2561810290">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3249 - 2024-04-18[06:43:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2561810290<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/19327/">publish-testray-report#19327</a><br/></div></div>

2024-04-18 17:25 UTC, vngoliveira commented
ci:test:sf

2024-04-18 17:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5393/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5393/jenkins-report.html">here</a>.</b></p>

2024-04-18 17:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9bb99cce5d5e9bdd8c1d9facaa8ee230ba1a0d83">9bb99cce5d5e9bdd8c1d9facaa8ee230ba1a0d83</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-22496_">LPD-22496_</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/f151a82a0cc64386a5600625a350af854f05baf2">f151a82a0cc64386a5600625a350af854f05baf2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5393/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5393/jenkins-report.html">here</a>.</h5></details></html>

2024-04-18 17:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5393/">test-portal-source-format#5393</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5393/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3249">liferay-objects#3249</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2561880178">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3249 - 2024-04-18[10:25:35]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2561880178<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/21304/">publish-testray-report#21304</a><br/></div></div>

2024-04-19 13:22 UTC, marcelabc commented
Just started reviewing :)

2024-04-19 15:54 UTC, marcelabc commented
resent: https://github.com/liferay-objects/liferay-portal/pull/3258

2024-04-19 15:54 UTC, closed without merging