LPD-23745 Refactor integration test
liferay-objects/liferay-portal pull request #3269
Opened 2024-04-23 15:23 UTC by evibudai

Hi Team,

Here's the PR that requested this change: https://github.com/brianchandotcom/liferay-portal/pull/149377#issuecomment-2063490111

2024-04-23 15:23 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-04-23 15:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/5014/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5014/jenkins-report.html">here</a>.</b></p>

2024-04-23 15:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evibudai/liferay-portal/tree/LPD-23745-master">LPD-23745-master</a><br/>Branch GIT ID: <a href="https://github.com/evibudai/liferay-portal/commit/8c433a4a7472d110c791f3fce6e8ce605460b146">8c433a4a7472d110c791f3fce6e8ce605460b146</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5014/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5014/jenkins-report.html">here</a>.</h5></details></html>

2024-04-23 15:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5014/">test-portal-source-format#5014</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5014/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3269">liferay-objects#3269</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562793745">[master] ci:test:sf - evibudai &gt; liferay-objects - PR#3269 - 2024-04-23[08:23:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562793745<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/19459/">publish-testray-report#19459</a><br/></div></div>

2024-04-23 16:35 UTC, G-Sa commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
>  		testExportImport(
I think we can remove this test case, as it is no longer the "base" test, it also removes one of the JSON

2024-04-23 17:57 UTC, G-Sa requested changes

2024-04-24 07:52 UTC, evibudai commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/BaseExportImportTestCase.java
> +			String actualFileName, String actualJSONString,
Okay, I'll change it, but this way the two signature will completely match.
I have to change something up.

```
public void testExportImport(
			String actualFileName, String expectedFileName,
			String externalReferenceCode, String name)
```
```
public void testExportImport(
			String actualJSONString, String expectedJSONString,
			String externalReferenceCode, String name)		
```

2024-04-24 13:29 UTC, G-Sa requested changes

2024-04-24 13:29 UTC, G-Sa commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
> +		JSONObjectDefinitionTestUtil.addLocalizedLabel(
For your test case, shouldnt this be a setLocalizedLabel? Since it should only have the german label and not the default english one?

2024-04-24 13:29 UTC, G-Sa commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
> +		JSONObjectDefinitionTestUtil.addLocalizedLabel(
Same here

2024-04-24 13:29 UTC, G-Sa commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
> +		JSONObjectDefinitionTestUtil.addLocalizedPluralLabel(
Same here

2024-04-24 13:29 UTC, G-Sa commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
> +			"externalReferenceCode", "TESTOBJECTDEFINITIONGERMAN"
Can you change to TESTOBJECTDEFINITIONINGERMAN so it is on pair with the definition name?

2024-04-24 14:05 UTC, evibudai commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
> +		JSONObjectDefinitionTestUtil.addLocalizedLabel(
same here too, so we need both labels

2024-04-24 14:05 UTC, evibudai commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
> +		JSONObjectDefinitionTestUtil.addLocalizedPluralLabel(
we need both labels

2024-04-24 19:02 UTC, carolmariaabb commented
@evibudai please see https://github.com/liferay-objects/liferay-portal/pull/3280

2024-04-24 19:02 UTC, closed without merging