LPD-21348 Update ObjectDefinition userId after user being deleted.
liferay-objects/liferay-portal pull request #3270
Opened 2024-04-23 18:29 UTC by thallescezar

Related issue: https://liferay.atlassian.net/browse/LPD-21348

2024-04-23 18:29 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-04-23 18:46 UTC, linolaoj approved these changes

2024-04-23 18:46 UTC, linolaoj commented
ci:forward

2024-04-23 18:46 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-04-23 18:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2926/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2926/jenkins-report.html">here</a>.</b></p>

2024-04-23 18:50 UTC, liferay-continuous-integration commented
ci:test:upgrade

Invoking upgrade test suite because an upgrade file has been modified.

2024-04-23 18:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPD-21348-2">LPD-21348-2</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/920e0e79c18ca451858553348ba2941c267c3dc7">920e0e79c18ca451858553348ba2941c267c3dc7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2926/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2926/jenkins-report.html">here</a>.</h5></details></html>

2024-04-23 18:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2926/">test-portal-source-format#2926</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2926/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562909166">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-23[11:47:04]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562909166<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/12500/">publish-testray-report#12500</a><br/></div></div>

2024-04-23 18:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>upgrade</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13184/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13184/jenkins-report.html">here</a>.</b></p>

2024-04-23 20:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 33 out of 33 jobs passed</h3><h3>:x: ci:test:relevant - 40 out of 46 jobs passed in 1 hour 41 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562627015">EE Development Acceptance (master) - 501 - 2024-04-22[12:38:53]</a></p><details><summary><strong>ci:test:stable - 33 out of 33 jobs PASSED</strong></summary><details><summary><strong>33 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 40 out of 46 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11685/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618702/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995857/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313272/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416579/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880987/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1088695/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/419958/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387787/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618705/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/324331/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379146/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380588/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313274/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/808760/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/881640/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985792/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862512/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/808761/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969509/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380589/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1088694/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985791/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416580/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618703/">modules-compile-jdk8/0/12</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/901762/"><strike>modules-integration-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985793/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1088696/">modules-integration-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/862179/"><strike>modules-integration-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/880986/">modules-integration-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969508/">modules-integration-mysql57-jdk8/0/5</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/618704/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924222/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/881639/"><strike>modules-semantic-versioning-jdk8/0/0</strike></a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/419956/"><strike>modules-unit-jdk8/0/0</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924221/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>patching-tool-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924220/">patching-tool-mysql57-jdk8/0/0</a></li></ul></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/969507/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1085997/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstr [...]

2024-04-23 20:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11685/">test-portal-acceptance-pullrequest(master)#11685</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11685/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562923795">[master] ci:test:relevant - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-23[11:47:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562923795<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/25484/">publish-testray-report#25484</a><br/></div></div>

2024-04-23 20:41 UTC, linolaoj commented
Hi @thallescezar, [SemanticVersioningTest](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/881639/testReport/com.liferay.semantic.versioning/SemanticVersioningTest) is related, we need to run the baseline task.

2024-04-23 21:15 UTC, linolaoj commented
ci:test:relevant

2024-04-23 21:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13184/">test-portal-acceptance-pullrequest(master)#13184</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13184/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>upgrade<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562950064">[master] ci:test:upgrade - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-23[11:57:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562950064<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/30700/">publish-testray-report#30700</a><br/></div></div>

2024-04-23 22:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/9353/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9353/jenkins-report.html">here</a>.</b></p>

2024-04-23 22:51 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0b5da7932c566b035937014adee4bf7c1d820463">0b5da7932c566b035937014adee4bf7c1d820463</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d56089f945aa90d7960108eba7f17186ac74963c">d56089f945aa90d7960108eba7f17186ac74963c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562627015">EE Development Acceptance (master) - 501 - 2024-04-22[12:38:53]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/9353/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9353/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/9353/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">thallescezar/LPD-21348-2</a></strong><pre>Unable to rebase master-temp-1713912612111 to master
Rebasing (1/8)
Rebasing (2/8)
Rebasing (3/8)
Rebasing (4/8)
Rebasing (5/8)
Rebasing (6/8)
Rebasing (7/8)
Rebasing (8/8)
error: could not apply 1535edfae7c51... LPD-21348 Baseline
Resolve all conflicts manually, mark them as resolved with
"git add/rm &lt;conflicted_files&gt;", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 1535edfae7c51... LPD-21348 Baseline</pre></p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/9353/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/9353/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/9353/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-04-24 13:01 UTC, linolaoj commented
Hi @thallescezar can you please rebase and resend, you might need to run the baseline again to rebase.

2024-04-24 13:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-04-24 13:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11692/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11692/jenkins-report.html">here</a>.</b></p>

2024-04-24 13:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5413/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5413/jenkins-report.html">here</a>.</b></p>

2024-04-24 13:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c808538beb5fcf685c8696719a287cc7c33b8af4">c808538beb5fcf685c8696719a287cc7c33b8af4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPD-21348-2">LPD-21348-2</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/09d16ae41e12204cbd92455d4d45ca08849ac1ac">09d16ae41e12204cbd92455d4d45ca08849ac1ac</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5413/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5413/jenkins-report.html">here</a>.</h5></details></html>

2024-04-24 13:18 UTC, liferay-continuous-integration commented
ci:test:upgrade

Invoking upgrade test suite because an upgrade file has been modified.

2024-04-24 13:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5413/">test-portal-source-format#5413</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5413/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563238875">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-24[06:15:17]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2563238875<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/21362/">publish-testray-report#21362</a><br/></div></div>

2024-04-24 16:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 33 out of 33 jobs passed</h3><h3>:x: ci:test:relevant - 41 out of 46 jobs passed in 2 hours 53 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/504">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_11692</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c808538beb5fcf685c8696719a287cc7c33b8af4">c808538beb5fcf685c8696719a287cc7c33b8af4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f5f1101d86b73e79f060f5fc21e0fd09ee8fe94">7f5f1101d86b73e79f060f5fc21e0fd09ee8fe94</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563150206">EE Development Acceptance (master) - 503 - 2024-04-23[16:38:09]</a></p><details><summary><strong>ci:test:stable - 33 out of 33 jobs PASSED</strong></summary><details><summary><strong>33 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 41 out of 46 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11692/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986436/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/881643/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089287/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379417/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/809493/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379419/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940678/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089292/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/809491/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388031/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420280/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089288/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/881641/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/863047/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902468/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902469/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388030/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089290/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1086922/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/619495/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/925037/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420278/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089289/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/809490/">modules-compile-jdk8/0/12</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/619540/"><strike>modules-integration-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986438/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/578472/">modules-integration-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986440/"><strike>modules-integration-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/578469/">modules-integration-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1086921/">modules-integration-mysql57-jdk8/0/5</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/619496/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089291/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/902467/">modules-semantic-versioning-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/619494/"><strike>modules-unit-jdk8/0/0</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/578470/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>patching-tool-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940676/">patching-tool-mysql57-jdk8/0/0</a></li></ul></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-accepta [...]

2024-04-24 16:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11692/">test-portal-acceptance-pullrequest(master)#11692</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11692/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563336615">[master] ci:test:relevant - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-24[06:15:15]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2563336615<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/25504/">publish-testray-report#25504</a><br/></div></div>

2024-04-25 13:19 UTC, linolaoj commented
Hi @thallescezar , can you please check if the test `com.liferay.object.storage.salesforce.internal.rest.manager.v1_0.test.SalesforceObjectEntryManagerImplTest.testGetObjectEntries` is related? If it is not we can forward force it.

2024-04-25 13:22 UTC, thallescezar commented
Going to check on it, @linolaoj

2024-04-25 14:15 UTC, thallescezar commented
ci:forward:force

2024-04-25 14:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-04-25 14:15 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-04-25 14:16 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1237//consoleFull)

2024-04-25 14:16 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/149673
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1237//consoleFull)

2024-04-29 21:22 UTC, linolaoj approved these changes

2024-04-29 21:22 UTC, linolaoj commented
ci:forward

2024-04-29 21:22 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-04-29 21:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5359/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5359/jenkins-report.html">here</a>.</b></p>

2024-04-29 21:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPD-21348-2">LPD-21348-2</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/0e867e9dd3cb95faf040cffa1620fffb9334603b">0e867e9dd3cb95faf040cffa1620fffb9334603b</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5359/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5359/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Test class 'com.liferay.object.internal.upgrade.v9_1_2.test.ObjectRelationshipUpgradeProcessTest' does not exist: ./modules/apps/object/object-service/src/main/java/com/liferay/object/internal/upgrade/v9_1_2/ObjectRelationshipUpgradeProcess.java (SourceCheck:JavaUpgradeMissingTestCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:469)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 2:12.931 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-10/job/test-portal-source-format/5359//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240429142847541.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240429142847541.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null103567994.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null421924560
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 234ms
[junitreport] Deleting: /tmp/null421924560
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 04-29-2024 14:28:51:723 PDT
[stopwatch] [run.batch.test.tear.down: 0.001 sec]</pre></details></html>

2024-04-29 21:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5359/">test-portal-source-format#5359</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5359/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564374514">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-29[14:24:24]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564374514<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/5580/">publish-testray-report#5580</a><br/></div></div>

2024-04-29 21:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4259/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4259/jenkins-report.html">here</a>.</b></p>

2024-04-29 22:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>upgrade</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9130/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9130/jenkins-report.html">here</a>.</b></p>

2024-04-30 00:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:upgrade - 373 out of 404 jobs passed in 2 hours 16 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/514">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1307401_9130</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c77921f49014810656a536569de9f1d02704bca7">c77921f49014810656a536569de9f1d02704bca7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564340664">EE Development Acceptance (master) - 512 - 2024-04-29[08:38:24]</a></p><details><summary><strong>ci:test:upgrade - 373 out of 404 jobs PASSED</strong></summary><div><h4>31 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9130/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-db2111-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928196/">functional-tomcat90-db2111-jdk8/0/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374728/">functional-tomcat90-db2111-jdk8/1/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622710/">functional-tomcat90-db2111-jdk8/1/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999111/">functional-tomcat90-db2111-jdk8/1/2</a></li></ul></li><li>functional-tomcat90-mariadb102-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989107/">functional-tomcat90-mariadb102-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092149/">functional-tomcat90-mariadb102-jdk8/1/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/421945/">functional-tomcat90-mariadb102-jdk8/1/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090250/">functional-tomcat90-mariadb102-jdk8/1/2</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989101/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866478/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928193/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622705/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/905069/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090243/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999104/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/905066/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866476/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928191/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884321/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622702/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812589/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943192/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989099/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973293/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884326/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380964/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418385/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/883985/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374724/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389675/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928195/"><strike>functional-tomcat90-mysql57-jdk8/1/16</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884325/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622706/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418384/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/421939/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/866479/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989102/">functional-tomcat90-mysql57-jdk8/1/22</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812592/">functional-tomcat90-mysql57-jdk8/1/23</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865246/">functional-tomcat90-mysql57-jdk8/1/24</a></li></ul></li><li>functional-tomcat90-mysql80-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884323/">functional-tomcat90-mysql80-jdk8/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test [...]

2024-04-30 00:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9130/">test-portal-acceptance-pullrequest(master)#9130</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9130/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>upgrade<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564418687">[master] ci:test:upgrade - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-29[15:01:41]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564418687<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/21830/">publish-testray-report#21830</a><br/></div></div>

2024-04-30 00:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 29 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 35 out of 42 jobs passed in 2 hours 60 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/514">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1327401_4259</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/aeda3bc570e35cd7182d6932e3e3d1cbd89e0032">aeda3bc570e35cd7182d6932e3e3d1cbd89e0032</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564429228">EE Development Acceptance (master) - 513 - 2024-04-29[12:39:35]</a></p><details><summary><strong>ci:test:stable - 29 out of 30 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928162/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928165/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973268/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973271/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380963/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090212/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389669/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943180/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315061/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418383/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943177/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973269/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989079/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943178/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943179/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1090211/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092119/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/382336/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989080/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865236/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928163/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973270/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989081/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865237/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315060/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989077/">playwright-compile-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380962/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389670/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943175/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943174/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 35 out of 42 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4259/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928162/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928165/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943173/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973268/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973271/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream [...]

2024-04-30 00:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4259/">test-portal-acceptance-pullrequest(master)#4259</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4259/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564443200">[master] ci:test:relevant - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-29[14:49:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564443200<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/32232/">publish-testray-report#32232</a><br/></div></div>

2024-04-30 18:23 UTC, linolaoj commented
ci:test:stable

2024-04-30 18:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9920/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9920/jenkins-report.html">here</a>.</b></p>

2024-04-30 19:44 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 29 out of 31 jobs passed in 1 hour 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f86f757d464b21667f98c8382385179aa2d20687">f86f757d464b21667f98c8382385179aa2d20687</a></p><details><summary><strong>ci:test:stable - 29 out of 31 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9920/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/867210/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989719/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865801/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091012/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928934/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943733/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989720/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/867212/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/813324/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973975/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091010/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943731/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/867211/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/623296/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581686/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092658/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989718/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973974/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091011/"><strike>modules-compile-jdk8/0/8</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885007/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581685/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/905545/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/581687/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1092659/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999635/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999634/">playwright-compile-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943732/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/813323/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943730/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/905544/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9920/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091011//consoleText">modules-compile-jdk8/0/8</a><pre>[beanshell] Author: CalumR23 &lt;searagan@gmail.com&gt;
[beanshell] Date:   Tue Nov 14 14:16:23 2023 -0800
[beanshell] 
[beanshell]     POSHI-667 Add property to bypass validation on resource jars
[beanshell] 
[beanshell] 
[beanshell] commit d965ef519ea18152ded1b74a4b3e5436986e918a
[beanshell] Author: Brian Chan &lt;brian.chan@liferay.com&gt;
[beanshell] Date:   Tue Apr 30 08:47:29 2024 -0300
[beanshell] 
[beanshell] 
[beanshell]     LPD-24472 SF
[beanshell] 
[beanshell] commit 7f30e96055826fc7971f3f6a424f75fbed1cd3b3
[beanshell] Author: Peter Shin &lt;peter.shin@liferay.com&gt;
[beanshell] Date:   Wed Apr 28 09:29:56 2021 -0500
[beanshell] 
[beanshell]     LPS-130464 Update lang builder to 1.0.42
[beanshell] 
[beanshell] Executing commands: git branch | grep \*
[beanshell] Executing commands: git clean -dfx
[beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
[beanshell] Executing commands: git log -n 1
[beanshell] Executing commands: git clean -dfx
[beanshell] 
[beanshell] commit dfa49a29124d25c1cd3f2ea831c11c1f0ce3eae0
[beanshell] Author: Liferay Continuous Integration &lt;continuous-integration@liferay.com&gt;
[beanshell] Date:   Tue Apr 30 02:43:38 2024 -0700
[beanshell] 
[beanshell]     Commit cache
[beanshell] 
[beanshell] Executing commands: git branch | grep \*
[beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
[beanshell] Executing commands: git log -n 1
[beanshell] 
[beanshell] commit deaa10590ac0ca70411b5e6bc0c0128543d53401
[beanshell] Author: Liferay Continuous Integration &lt;continuous-integration@liferay.com&gt;
[beanshell] Date:   Thu Apr 18 09:03:22 2024 -0700
[beanshell] 
[beanshell]     subrepo:ignore Update 'modules/dxp/a [...]

2024-04-30 19:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9920/">test-portal-acceptance-pullrequest(master)#9920</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9920/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>stable<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564712605">[master] ci:test:stable - thallescezar &gt; liferay-objects - PR#3270 - 2024-04-30[11:23:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564712605<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/21219/">publish-testray-report#21219</a><br/></div></div>

2024-04-30 20:22 UTC, linolaoj commented
Hi @thallescezar, we will need to add the upgrade step test. 
https://liferay.atlassian.net/wiki/spaces/ENGCOREUPGRADE/pages/1654719711/Upgrade+Development+Training#Testing

2024-05-02 14:55 UTC, linolaoj commented
ci:test:sf

2024-05-02 14:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6387/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6387/jenkins-report.html">here</a>.</b></p>

2024-05-02 14:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1937ffa818c283a79caa53f5ec8a0166e25c6fea">1937ffa818c283a79caa53f5ec8a0166e25c6fea</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thallescezar/liferay-portal/tree/LPD-21348-2">LPD-21348-2</a><br/>Branch GIT ID: <a href="https://github.com/thallescezar/liferay-portal/commit/8cb36a122c9dcbe58b96f52a604c1f2cae25cdf4">8cb36a122c9dcbe58b96f52a604c1f2cae25cdf4</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6387/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6387/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 7 formatting issues:
     [java] 1: Test class 'com.liferay.object.internal.upgrade.v9_1_2.test.ObjectRelationshipUpgradeProcessTest' does not exist: ./modules/apps/object/object-service/src/main/java/com/liferay/object/internal/upgrade/v9_1_2/ObjectRelationshipUpgradeProcess.java (SourceCheck:JavaUpgradeMissingTestCheck)
     [java] 2: Missing copyright, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/copyright_check.markdown: ./modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/upgrade/v9_1_2/ObjectRelationshipUpgradeProcessTest.java (SourceCheck:CopyrightCheck)
     [java] 3: Module integration test must be under a test subpackage, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/java_module_test_check.markdown: ./modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/upgrade/v9_1_2/ObjectRelationshipUpgradeProcessTest.java (SourceCheck:JavaModuleTestCheck)
     [java] 4: Missing author: ./modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/upgrade/v9_1_2/ObjectRelationshipUpgradeProcessTest.java 31 (Checkstyle:MissingAuthorCheck)
     [java] 5: Method '_assertObjectDefinitionUserId' throws unnecessary 'PortalException'. All methods calling '_assertObjectDefinitionUserId' throw 'Exception'., see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/exception_check.markdown: ./modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/upgrade/v9_1_2/ObjectRelationshipUpgradeProcessTest.java 73 (Checkstyle:ExceptionCheck)
     [java] 6: ./modules/apps/object/object-test/build.gradle expected:&lt;...roject(":apps:portal[-security-audit:portal-security-audit-api")
     [java]   testIntegrationImplementation project(":apps:portal-security-audit:portal-security-audit-event-generators-api")
     [java]   testIntegrationImplementation project(":apps:portal-security:portal-security-script-management-api")
     [java]   testIntegrationImplementation project(":apps:portal-security:portal-security-script-management-test-util")
     [java]   testIntegrationImplementation project(":apps:portal-vulcan:portal-vulcan-api")</pre></details></html>

2024-05-02 15:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6387/">test-portal-source-format#6387</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6387/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3270">liferay-objects#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2565063426">[master] ci:test:sf - thallescezar &gt; liferay-objects - PR#3270 - 2024-05-02[07:55:50]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2565063426<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/24886/">publish-testray-report#24886</a><br/></div></div>

2024-05-02 18:54 UTC, thallescezar commented
ci:test:sf

2024-05-02 19:03 UTC, thallescezar commented
ci:test:sf

2024-05-02 19:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9230/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9230/jenkins-report.html">here</a>.</b></p>

2024-05-07 13:21 UTC, gabrielwas requested changes
@thallescezar @linolaoj check my suggestions. Thx.

2024-05-07 13:21 UTC, gabrielwas commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/model/listener/test/UserModelListenerTest.java
> +			objectDefinition);
Use `_objectDefinitionLocalService.addCustomObjectDefinition` instead. Like https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectDefinitionLocalServiceTest.java#L1836-L1843

2024-05-07 13:21 UTC, gabrielwas commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/upgrade/v9_1_2/test/ObjectRelationshipUpgradeProcessTest.java
> +	private void _runUpgrade() throws Exception {
Method `_runUpgrade` not needed. Inline it

2024-05-07 13:21 UTC, gabrielwas commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/upgrade/v9_1_2/test/ObjectRelationshipUpgradeProcessTest.java
> +	private ObjectDefinition _addCustomObjectDefinition(
Method `_addCustomObjectDefinition` not needed. Inline it.

2024-05-07 13:21 UTC, gabrielwas commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/upgrade/v9_1_2/test/ObjectRelationshipUpgradeProcessTest.java
> +			"ObjectRelationshipUpgradeProcess";
Remember to rename the log when renaming the upgrade file

2024-05-07 13:21 UTC, gabrielwas commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/upgrade/v9_1_2/test/ObjectRelationshipUpgradeProcessTest.java
> +	private ObjectDefinition _publishCustomObjectDefinition(long userId)
Better to inline the method `_publishCustomObjectDefinition` also to follow the pattern we have in `ObjectDefinitionLocalServiceTest`

2024-05-07 19:28 UTC, thallescezar commented on modules/apps/object/object-service/src/main/java/com/liferay/object/internal/model/listener/UserModelListener.java
> +		if (Objects.equals(user.getScreenName(), "default-service-account")) {
Tested and worked fine. Removing it

2024-05-13 16:53 UTC, linolaoj commented
Hi, I'll rebase and resend with some changes for the test to compile.

2024-05-13 20:56 UTC, linolaoj commented
@rijema , I sent you a pr with a wip of my changes, can you please check it and send a new pr?

2024-05-13 20:56 UTC, closed without merging