LPD-23390 [Must Add] [P3] Automate LPP-48808
liferay-objects/liferay-portal pull request #3287
Opened 2024-04-26 14:04 UTC by pedro-oliveira446

[LPD-23390](https://liferay.atlassian.net/browse/LPD-23390)

2024-04-26 14:04 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-04-26 14:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3255/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3255/jenkins-report.html">here</a>.</b></p>

2024-04-26 14:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ef0de3a1e929d7352b75537f6ec1f00a6ec47051">ef0de3a1e929d7352b75537f6ec1f00a6ec47051</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-23390">LPD-23390</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/412fd46ac95181315e7aacef315e46595166cbcf">412fd46ac95181315e7aacef315e46595166cbcf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3255/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3255/jenkins-report.html">here</a>.</h5></details></html>

2024-04-26 14:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3255/">test-portal-source-format#3255</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3255/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3287">liferay-objects#3287</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2563906031">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3287 - 2024-04-26[07:04:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2563906031<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/13023/">publish-testray-report#13023</a><br/></div></div>

2024-04-26 19:42 UTC, cgmonte commented on modules/test/playwright/pages/object-web/object-action/ActionBuilderPage.ts
> +    async checkNotificationsVisible(notificationsName:string[]) {
Assertions don't belong to a page object, they belong to the test. A page object is a representation of the page and its functionalities. The action builder page does not provide a way for the user to check if notifications are visible. This is needed and done by the test only, and so it belongs there in the `spec.ts`.

2024-04-26 19:45 UTC, cgmonte commented on modules/test/playwright/pages/object-web/ViewObjectDefinitionsPage.ts
> +	async clickEditObjectDefinitionLink(objectDefinitionName: string) {
Sort this, it should come after `clickDefaultObjectFolder`.

2024-04-26 20:15 UTC, cgmonte commented on modules/test/playwright/fixtures/objectPagesTest.ts
>  const objectPagesTest = test.extend<{
Hey, we are mixing too much pages here, I guess. Model Builder pages and Edit Object Definition pages should have their own fixtures. Can you create a new one, like `editObjectDefinitionPagesTest.ts`?

2024-04-26 20:20 UTC, cgmonte commented on modules/test/playwright/tests/object-web/objectActions.spec.ts
> +        await actionBuilderPage.checkNotificationsVisible(names);
Bring the assertion of `checkNotificationsVisible` here, as mentioned before in another commit comment, assertions belong to the test.

2024-04-26 20:21 UTC, cgmonte requested changes
Hey @pedro-oliveira446, thanks for working on this! You work is really appreciated! I made some comments and requested some changes. Let me know what you think about them.

2024-04-29 19:59 UTC, pedro-oliveira446 commented
ci:test:sf

2024-04-29 20:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5570/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5570/jenkins-report.html">here</a>.</b></p>

2024-04-29 20:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/5716/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5716/jenkins-report.html">here</a>.</b></p>

2024-04-29 20:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/aeda3bc570e35cd7182d6932e3e3d1cbd89e0032">aeda3bc570e35cd7182d6932e3e3d1cbd89e0032</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-23390">LPD-23390</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/a25d554a24ac9b861cb013fa5b9ba8738b79324c">a25d554a24ac9b861cb013fa5b9ba8738b79324c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5570/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5570/jenkins-report.html">here</a>.</h5></details></html>

2024-04-29 20:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/aeda3bc570e35cd7182d6932e3e3d1cbd89e0032">aeda3bc570e35cd7182d6932e3e3d1cbd89e0032</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-23390">LPD-23390</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/a25d554a24ac9b861cb013fa5b9ba8738b79324c">a25d554a24ac9b861cb013fa5b9ba8738b79324c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/5716/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5716/jenkins-report.html">here</a>.</h5></details></html>

2024-04-29 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5570/">test-portal-source-format#5570</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5570/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3287">liferay-objects#3287</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564337711">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3287 - 2024-04-29[12:58:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564337711<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/21826/">publish-testray-report#21826</a><br/></div></div>

2024-04-29 20:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/5716/">test-portal-source-format#5716</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/5716/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3287">liferay-objects#3287</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564337756">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3287 - 2024-04-29[12:59:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564337756<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/21190/">publish-testray-report#21190</a><br/></div></div>

2024-04-30 18:14 UTC, cgmonte approved these changes
LGTM!

2024-04-30 20:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10563/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10563/jenkins-report.html">here</a>.</b></p>

2024-04-30 21:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:playwright - 2 out of 2 jobs passed in 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad9a41c8204eb253c2313bcf2e1fd25c610f80da">ad9a41c8204eb253c2313bcf2e1fd25c610f80da</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5fcda86691f6b1570c35842a00e89f92fa5cb082">5fcda86691f6b1570c35842a00e89f92fa5cb082</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564722990">EE Development Acceptance (master) - 515 - 2024-04-30[08:38:39]</a></p><details><summary><strong>ci:test:playwright - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10563/">test-portal-acceptance-pullrequest(master)</a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390152/">playwright-compile-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10563/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/10563/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/10563/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/10563/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-04-30 21:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10563/">test-portal-acceptance-pullrequest(master)#10563</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10563/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3287">liferay-objects#3287</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564743573">[master] ci:test:playwright - pedro-oliveira446 &gt; liferay-objects - PR#3287 - 2024-04-30[13:34:34]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564743573<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/21788/">publish-testray-report#21788</a><br/></div></div>

2024-05-02 11:13 UTC, pedro-oliveira446 commented
ci:test:playwright

2024-05-02 12:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 24 out of 30 jobs passed in 1 hour 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c3620f6b5b67d541654a02d625c55d680f3adefd">c3620f6b5b67d541654a02d625c55d680f3adefd</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c3620f6b5b67d541654a02d625c55d680f3adefd">c3620f6b5b67d541654a02d625c55d680f3adefd</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2565032794">EE Development Acceptance (master) - 519 - 2024-05-01[20:41:37]</a></p><details><summary><strong>ci:test:playwright - 24 out of 30 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/16588/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929817/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1093404/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814118/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929820/"><strike>playwright-js-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974787/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/868046/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091885/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/582472/"><strike>playwright-js-tomcat90-mysql57-jdk8/6/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974785/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/868044/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929818/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/624180/"><strike>playwright-js-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/868042/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974788/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/582473/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/990512/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929822/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1093405/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929821/">playwright-js-tomcat90-mysql57-jdk8/17/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/868043/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974784/"><strike>playwright-js-tomcat90-mysql57-jdk8/19/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1093402/">playwright-js-tomcat90-mysql57-jdk8/20/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/868045/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814116/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1091884/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974786/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929819/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1093403/">playwright-js-tomcat90-mysql57-jdk8/26/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814117/">playwright-js-tomcat90-mysql57-jdk8/27/0</a></li></ul></li></ul></div><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/16588/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929820//consoleText">playwright-js-tomcat90-mysql57-jdk8/2/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-37/test-portal-acceptance-pullrequest(master)/16588/playwright-js-tomcat90-mysql57-jdk8/2/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929820/testReport/commerce_commerceSpecificationFragment.spec/ts">commerce/commerceSpecificationFragment.spec.ts</a></summary><div><ol><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929820//testReport/commerce_commerceSpecificationFragment.spec/ts/LPD_13652_Product_specification_fragment_only_shows_correct_specifications">LPD-13652 Product specification fragment only shows correct specifications</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929820/testReport/commerce_commerceMiniCart.spec/ts">commerce/commerceMiniCart.spec.ts</a></summary><div><ol><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929820//testReport/commerce_commerceMiniCart.spec/ts/LPD_3496_Mini_cart_bundle_without_enough_quantity">LPD-3496 Mini cart bundle without enough quantity</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929820/testReport/commerce_commerce-product-content-search-web_specificationFacet.spec/ts">commerce/commerce-product-content-search-web/specificationFacet.spec.ts</a></summary><div><ol><li>< [...]

2024-05-02 13:12 UTC, pedro-oliveira446 commented
ci:forward:force

2024-05-02 13:12 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-05-02 13:12 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-36.liferay.com/job/forward-pullrequest/683//consoleFull)

2024-05-02 13:13 UTC, closed without merging