LPD-19239 Delete created object definitions at the end of the tests
liferay-objects/liferay-portal pull request #3292
Opened 2024-04-26 20:08 UTC by devpedrotavares

Related: [LPD-19239](https://liferay.atlassian.net/browse/LPD-19239)

2024-04-26 20:08 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-04-26 20:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6655/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6655/jenkins-report.html">here</a>.</b></p>

2024-04-26 20:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ef0de3a1e929d7352b75537f6ec1f00a6ec47051">ef0de3a1e929d7352b75537f6ec1f00a6ec47051</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/devpedrotavares/liferay-portal/tree/LPD-19239">LPD-19239</a><br/>Branch GIT ID: <a href="https://github.com/devpedrotavares/liferay-portal/commit/5696daa6c2d649e2272fe7c48826080ac8c4539e">5696daa6c2d649e2272fe7c48826080ac8c4539e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6655/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6655/jenkins-report.html">here</a>.</h5></details></html>

2024-04-26 20:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6655/">test-portal-source-format#6655</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6655/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3292">liferay-objects#3292</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564003452">[master] ci:test:sf - devpedrotavares &gt; liferay-objects - PR#3292 - 2024-04-26[13:09:05]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564003452<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/25560/">publish-testray-report#25560</a><br/></div></div>

2024-04-29 13:51 UTC, marcelabc approved these changes
LGTM 🎉

2024-04-29 13:52 UTC, marcelabc commented
ci:test:relevant

2024-04-29 15:13 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-04-29 15:13 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectEntryLocalServiceTest.java
> +
Can you delete `draftObjectDefinition` too?

2024-04-29 15:24 UTC, devpedrotavares commented
ci:test:sf

2024-04-29 17:12 UTC, marcelabc approved these changes
LGTM 🎉

2024-04-29 17:13 UTC, marcelabc commented
ci:test:relevant

2024-04-29 17:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/122784a218d337d4a64a2db924728dde18a54732">122784a218d337d4a64a2db924728dde18a54732</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2bee213557561fbd91a92b14e08a67574e8eeccb">2bee213557561fbd91a92b14e08a67574e8eeccb</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564217764">EE Development Acceptance (master) - 511 - 2024-04-28[16:38:22]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5692/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5692/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5692/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/5692/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/5692/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/5692/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-04-29 17:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5692/">test-portal-acceptance-pullrequest(master)#5692</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5692/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3292">liferay-objects#3292</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564317107">[master] ci:test:relevant - devpedrotavares &gt; liferay-objects - PR#3292 - 2024-04-29[10:13:24]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564317107<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/12570/">publish-testray-report#12570</a><br/></div></div>

2024-04-29 17:52 UTC, devpedrotavares commented
ci:test:relevant

2024-04-29 17:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4256/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4256/jenkins-report.html">here</a>.</b></p>

2024-04-29 19:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 4 out of 4 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 10 out of 13 jobs passed in 1 hour 57 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/122784a218d337d4a64a2db924728dde18a54732">122784a218d337d4a64a2db924728dde18a54732</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2bee213557561fbd91a92b14e08a67574e8eeccb">2bee213557561fbd91a92b14e08a67574e8eeccb</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564217764">EE Development Acceptance (master) - 511 - 2024-04-28[16:38:22]</a></p><details><summary><strong>ci:test:stable - 4 out of 4 jobs PASSED</strong></summary><details><summary><strong>4 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 9 out of 13 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4256/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299/"><strike>modules-integration-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942943/"><strike>modules-integration-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942942/">modules-integration-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580807/">modules-integration-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/580806/">modules-integration-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942940/">modules-integration-mysql57-jdk8/0/5</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942941/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/884058/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089918/"><strike>modules-unit-jdk8/0/0</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973006/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>unit-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089917/">unit-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/927875/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>9 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4256/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 2bee213557561fbd91a92b14e08a67574e8eeccb:</strong></summary><ol><li><div><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299//consoleText">modules-integration-mysql57-jdk8/0/0</a><ol><li><details><summary><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299/testReport/com.liferay.object.rest.internal.graphql.v1_0.test/ObjectDefinitionGraphQLTest">com.liferay.object.rest.internal.graphql.v1_0.test.ObjectDefinitionGraphQLTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2564229090/history">Failed 4 of last 18</a></summary><div><ol><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299//testReport/com.liferay.object.rest.internal.graphql.v1_0.test/ObjectDefinitionGraphQLTest/testGetObjectEntryWithLocalizedObjectField">testGetObjectEntryWithLocalizedObjectField</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299/testReport/com.liferay.object.rest.internal.manager.v1_0.test/DefaultObjectEntryManagerImplTest">com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2564229095/history">Failed 4 of last 18</a></summary><div><ol><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299//testReport/com.liferay.object.rest.internal.manager.v1_0.test/DefaultObjectEntryManagerImplTest/testGetObjectEntries">testGetObjectEntries</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299//testReport/com.liferay.object.rest.internal.manager.v1_0.test/DefaultObjectEntryManagerImplTest/testUpdateObjectEntry">testUpdateObjectEntry</a></li></ol></div></details></li><li><details><summary><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299/testReport/com.liferay.object.rest.internal.resource.v1_0.test/ObjectEntryResourceTest">com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryResourceTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2564229111/history">Failed 4 of last 18</a></summary><div><ol><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812299//testReport/com.liferay.object.rest.internal.resource.v1_0.test/ObjectEntryResourceTest/testGetObjectEntryWithLocalizedObjectField">testGetObjectEntryWithLocalizedObjectField</a></li></ol></div></details></li><li>...</li></ol></div></li><li><div><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942943//consoleText">modules-integration-mysql57-jdk8/0/1</a><ol><li><details><summary><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942943/testReport/com.liferay.object.storage.salesforce.internal.rest.manager.v1_0.test/SalesforceObjectEntryManagerImplTest">com.liferay.object.storage.salesforce.internal.rest.manager.v1_0.test.SalesforceObjectEntryManagerImplTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2564228833/history">Failed 11 of last 15</a></summary><div><ol><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942943//testReport/com.liferay.object.storage.salesforce.internal.rest.manager.v1_0.test/SalesforceObjectEntryManagerImplTest/testGetObjectEntries">testGetObjectEntries</a></li></ol></div></details></li></ol></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089918//consoleText">modules-unit-jdk8/0/0</a><ol><li><details><summary><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1089918/testReport/com.liferay.object.web.internal.info.item.provider/Object [...]

2024-04-30 10:46 UTC, carolmariaabb commented
ci:forward

2024-04-30 10:46 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-04-30 10:46 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:stable`

2024-04-30 10:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3285/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3285/jenkins-report.html">here</a>.</b></p>

2024-04-30 10:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cbc1e1ee4764ea2de2e3a88b151054d0321107a1">cbc1e1ee4764ea2de2e3a88b151054d0321107a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/devpedrotavares/liferay-portal/tree/LPD-19239">LPD-19239</a><br/>Branch GIT ID: <a href="https://github.com/devpedrotavares/liferay-portal/commit/c11f87641bb4e76977c50d2c2327f115b7c3195b">c11f87641bb4e76977c50d2c2327f115b7c3195b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3285/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3285/jenkins-report.html">here</a>.</h5></details></html>

2024-04-30 10:55 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-36.liferay.com/job/test-portal-source-format/3285//consoleFull)

2024-04-30 10:55 UTC, closed without merging

2024-04-30 10:56 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/149793
[Console](https://test-1-36.liferay.com/job/test-portal-source-format/3285//consoleFull)

2024-04-30 10:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3285/">test-portal-source-format#3285</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3285/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3292">liferay-objects#3292</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2564508348">[master] ci:test:sf - devpedrotavares &gt; liferay-objects - PR#3292 - 2024-04-30[03:46:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2564508348<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/13112/">publish-testray-report#13112</a><br/></div></div>