LPD-7839 Create a Test to Cover Navigate to Edit Object Definition Page
liferay-objects/liferay-portal pull request #3330
Opened 2024-05-10 14:51 UTC by igor-franca

Related [Ticket](https://liferay.atlassian.net/browse/LPD-25461)

2024-05-10 14:51 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-05-10 14:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/5258/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5258/jenkins-report.html">here</a>.</b></p>

2024-05-10 14:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPD-7839">LPD-7839</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/16ac59aba5833165b93d74a57ccf2e74c219f167">16ac59aba5833165b93d74a57ccf2e74c219f167</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5258/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5258/jenkins-report.html">here</a>.</h5></details></html>

2024-05-10 19:39 UTC, igor-franca commented on modules/test/playwright/tests/object-web/objectDefinitions.spec.ts
> +
[reference](https://playwright.dev/docs/pages#handling-new-pages)

2024-05-10 22:31 UTC, cgmonte requested changes
Hi @igor-franca, I only have a small request for change. Please, take look and let me known what you think. Thanks

2024-05-10 22:31 UTC, cgmonte commented on modules/test/playwright/tests/object-web/objectDefinitions.spec.ts
> +		const pagePromise = context.waitForEvent('page');
You only need to start waiting for this event right before calling `openPageViewButton.click():`. Then we would have something like this:
```
const pagePromise = context.waitForEvent('page');

await modelBuilderPage.openPageViewButton.click();

const editObjectDefinitionPage = await pagePromise;
```

2024-05-13 13:42 UTC, igor-franca commented
ci:test:sf

2024-05-13 13:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/5152/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5152/jenkins-report.html">here</a>.</b></p>

2024-05-13 13:44 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPD-7839">LPD-7839</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/cc35efc24c9337c087bc2e17441bbc5406942447">cc35efc24c9337c087bc2e17441bbc5406942447</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5152/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5152/jenkins-report.html">here</a>.</h5><pre>     [exec] Here are the highlights of this release:
     [exec]  - Support for running on Java 21
     [exec]  - Faster first use with Kotlin DSL
     [exec]  - Improved error and warning messages
     [exec] 
     [exec] For more details see https://docs.gradle.org/8.5/release-notes.html
     [exec] 
     [exec] To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.5/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
     [exec] Daemon will be stopped at the end of the build 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Could not resolve all files for configuration 'classpath'.
     [exec] &gt; Could not resolve com.liferay:com.liferay.gradle.util:1.0.49.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve com.liferay:com.liferay.gradle.util:1.0.49.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.gradle.util/1.0.49/com.liferay.gradle.util-1.0.49.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.gradle.util/1.0.49/com.liferay.gradle.util-1.0.49.pom'.
     [exec]             &gt; Got socket exception during request. It might be caused by SSL misconfiguration
     [exec]                &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/172.18.16.3] failed: Connection refused (Connection refused)
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration\$ArtifactResolveException: Could not resolve all files for configuration 'classpath'.
     [exec]   at org.gradle.api.internal.artifacts.ResolveExceptionContextualizer.mapFailure(ResolveExceptionContextualizer.java:81)
     [exec]   at org.gradle.api.internal.artifacts.ResolveExceptionContextualizer.mapFailures(ResolveExceptionContextualizer.java:60)
     [exec]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration\$DefaultResolutionHost.mapFailure(DefaultConfiguration.java:2310)</pre></details></html>

2024-05-13 14:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5152/">test-portal-source-format#5152</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5152/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3330">liferay-objects#3330</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2568170071">[master] ci:test:sf - igor-franca &gt; liferay-objects - PR#3330 - 2024-05-13[06:42:26]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2568170071<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/19958/">publish-testray-report#19958</a><br/></div></div>

2024-05-13 14:31 UTC, cgmonte approved these changes
LGTM!

2024-05-13 14:36 UTC, igor-franca commented
SF reported the following error:

```
     [exec] Caused by: java.net.ConnectException: Connection refused (Connection refused)
     [exec] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
     [exec] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
     [exec] 	... 245 more
```

I'll run it again and wait to check for this connection error.

2024-05-13 14:36 UTC, igor-franca commented
ci:test:sf

2024-05-13 14:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/5166/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5166/jenkins-report.html">here</a>.</b></p>

2024-05-13 14:39 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPD-7839">LPD-7839</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/cc35efc24c9337c087bc2e17441bbc5406942447">cc35efc24c9337c087bc2e17441bbc5406942447</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5166/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5166/jenkins-report.html">here</a>.</h5><pre>     [exec] Here are the highlights of this release:
     [exec]  - Support for running on Java 21
     [exec]  - Faster first use with Kotlin DSL
     [exec]  - Improved error and warning messages
     [exec] 
     [exec] For more details see https://docs.gradle.org/8.5/release-notes.html
     [exec] 
     [exec] To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.5/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
     [exec] Daemon will be stopped at the end of the build 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Could not resolve all files for configuration 'classpath'.
     [exec] &gt; Could not resolve com.liferay:com.liferay.gradle.util:1.0.49.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve com.liferay:com.liferay.gradle.util:1.0.49.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.gradle.util/1.0.49/com.liferay.gradle.util-1.0.49.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.gradle.util/1.0.49/com.liferay.gradle.util-1.0.49.pom'.
     [exec]             &gt; Got socket exception during request. It might be caused by SSL misconfiguration
     [exec]                &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/172.18.16.3] failed: Connection refused (Connection refused)
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration\$ArtifactResolveException: Could not resolve all files for configuration 'classpath'.
     [exec]   at org.gradle.api.internal.artifacts.ResolveExceptionContextualizer.mapFailure(ResolveExceptionContextualizer.java:81)
     [exec]   at org.gradle.api.internal.artifacts.ResolveExceptionContextualizer.mapFailures(ResolveExceptionContextualizer.java:60)
     [exec]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration\$DefaultResolutionHost.mapFailure(DefaultConfiguration.java:2310)</pre></details></html>

2024-05-13 14:44 UTC, igor-franca commented
> There appears to be an issue with Jenkins nodes connecting to repository-cdn. I’ve contacted IT . Hopefully they can resolve this issue soon.

-Peter Yoo, [here](https://liferay.slack.com/archives/C19PWQ74J/p1715610465771059?thread_ts=1715598586.723149&cid=C19PWQ74J)

2024-05-13 15:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5166/">test-portal-source-format#5166</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5166/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3330">liferay-objects#3330</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2568176208">[master] ci:test:sf - igor-franca &gt; liferay-objects - PR#3330 - 2024-05-13[07:36:40]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2568176208<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/19984/">publish-testray-report#19984</a><br/></div></div>

2024-05-13 18:53 UTC, igor-franca commented
ci:test:sf

2024-05-13 18:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/8579/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8579/jenkins-report.html">here</a>.</b></p>

2024-05-13 18:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPD-7839">LPD-7839</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/cc35efc24c9337c087bc2e17441bbc5406942447">cc35efc24c9337c087bc2e17441bbc5406942447</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8579/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8579/jenkins-report.html">here</a>.</h5></details></html>

2024-05-13 19:10 UTC, igor-franca commented
ci:test:playwright

2024-05-13 19:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13358/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13358/jenkins-report.html">here</a>.</b></p>

2024-05-13 20:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 28 out of 32 jobs passed in 1 hour 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2567814083">EE Development Acceptance (master) - 536 - 2024-05-10[08:38:08]</a></p><details><summary><strong>ci:test:playwright - 28 out of 32 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13358/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877836/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1102160/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1102161/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877838/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/590832/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983443/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380054/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/320598/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983442/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385862/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873490/"><strike>playwright-js-tomcat90-mysql57-jdk8/9/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/891265/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/938479/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1100898/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/893526/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/395752/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/427192/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/914037/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1102162/">playwright-js-tomcat90-mysql57-jdk8/17/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/951707/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007807/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/914036/">playwright-js-tomcat90-mysql57-jdk8/20/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/423235/"><strike>playwright-js-tomcat90-mysql57-jdk8/21/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1102159/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388111/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/427191/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007808/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/893525/">playwright-js-tomcat90-mysql57-jdk8/26/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877837/">playwright-js-tomcat90-mysql57-jdk8/27/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874000/">playwright-js-tomcat90-mysql57-jdk8/28/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873491/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li></ul></li></ul></div><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13358/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385862//consoleText">playwright-js-tomcat90-mysql57-jdk8/8/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-26/test-portal-acceptance-pullrequest(master)/13358/playwright-js-tomcat90-mysql57-jdk8/8/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385862/testReport/frontend-data-set-views-web_dateRangeFilters.spec/ts">frontend-data-set-views-web/dateRangeFilters.spec.ts</a></summary><div><ol><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385862//testReport/frontend-data-set-views-web_dateRangeFilters.spec/ts/When_creating_a_new_filter_in_DSM__date_time_field_is_available_for_selection__LPD_10754">When creating a new filter in DSM, date-time field is available for selection @LPD-10754</a></li></ol></div></details></li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 77ae292bf9d7fe847a8b5b237ca52f064cc67a8c:</strong></summary><ol><li><div><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873490//consoleText">playwright-js-tomcat90-mysql57-jdk8/9/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-0 [...]

2024-05-13 20:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13358/">test-portal-acceptance-pullrequest(master)#13358</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13358/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3330">liferay-objects#3330</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2568255721">[master] ci:test:playwright - igor-franca &gt; liferay-objects - PR#3330 - 2024-05-13[12:10:54]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2568255721<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/31088/">publish-testray-report#31088</a><br/></div></div>

2024-05-13 20:48 UTC, igor-franca commented
ci:forward

2024-05-13 20:48 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-05-13 20:50 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/forward-pullrequest/1025//consoleFull)

2024-05-13 20:50 UTC, closed without merging

2024-05-13 20:50 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/150268
[Console](https://test-1-29.liferay.com/job/forward-pullrequest/1025//consoleFull)