LPD-26164
liferay-objects/liferay-portal pull request #3361
Opened 2024-05-17 20:40 UTC by icgsbr

https://liferay.atlassian.net/browse/LPD-26164

2024-05-17 20:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6786/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6786/jenkins-report.html">here</a>.</b></p>

2024-05-17 20:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f7edb89c55414ddc679deb307d7101c9b0603e65">f7edb89c55414ddc679deb307d7101c9b0603e65</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/icgsbr/liferay-portal/tree/LPD-26164">LPD-26164</a><br/>Branch GIT ID: <a href="https://github.com/icgsbr/liferay-portal/commit/0317ef2f6da0547f74fcc9fa49e6ed0c199ce5ed">0317ef2f6da0547f74fcc9fa49e6ed0c199ce5ed</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6786/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6786/jenkins-report.html">here</a>.</h5></details></html>

2024-05-17 20:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6786/">test-portal-source-format#6786</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6786/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3361">liferay-objects#3361</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2570246714">[master] ci:test:sf - icgsbr &gt; liferay-objects - PR#3361 - 2024-05-17[13:41:16]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2570246714<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/25999/">publish-testray-report#25999</a><br/></div></div>

2024-05-20 12:19 UTC, carolmariaabb requested changes

2024-05-20 21:34 UTC, icgsbr commented
ci:test:sf

2024-05-20 21:35 UTC, icgsbr commented
ci:test:sf

2024-05-20 21:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5406/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5406/jenkins-report.html">here</a>.</b></p>

2024-05-20 21:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f7edb89c55414ddc679deb307d7101c9b0603e65">f7edb89c55414ddc679deb307d7101c9b0603e65</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/icgsbr/liferay-portal/tree/LPD-26164">LPD-26164</a><br/>Branch GIT ID: <a href="https://github.com/icgsbr/liferay-portal/commit/d3a20d34954840e2541bc7287b2d6cecfcca1f29">d3a20d34954840e2541bc7287b2d6cecfcca1f29</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5406/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5406/jenkins-report.html">here</a>.</h5></details></html>

2024-05-20 21:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5406/">test-portal-source-format#5406</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5406/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3361">liferay-objects#3361</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2570464984">[master] ci:test:sf - icgsbr &gt; liferay-objects - PR#3361 - 2024-05-20[14:38:05]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2570464984<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/5668/">publish-testray-report#5668</a><br/></div></div>

2024-05-21 11:43 UTC, carolmariaabb commented on modules/apps/object/object-rest-impl/src/main/java/com/liferay/object/rest/internal/odata/filter/expression/PredicateExpressionVisitorImpl.java
> +			}
@icgsbr I won't have time to review the test code for the next three days, so please **don't forward** this PR yet. However, it is okay to create a hotfix with this change. Thanks!

2024-05-23 17:49 UTC, carolmariaabb commented
@icgsbr please see https://github.com/liferay-objects/liferay-portal/pull/3381/

2024-05-23 17:49 UTC, closed without merging