LPD-26339 - Add default language labels missing during import
liferay-objects/liferay-portal pull request #3367
Opened 2024-05-20 19:12 UTC by G-Sa

Related to: [LPD-26339](https://liferay.atlassian.net/browse/LPD-26339)

2024-05-20 20:35 UTC, G-Sa commented
ci:test:sf

2024-05-20 20:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/7919/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7919/jenkins-report.html">here</a>.</b></p>

2024-05-20 20:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f7edb89c55414ddc679deb307d7101c9b0603e65">f7edb89c55414ddc679deb307d7101c9b0603e65</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/G-Sa/liferay-portal/tree/LPD-26339">LPD-26339</a><br/>Branch GIT ID: <a href="https://github.com/G-Sa/liferay-portal/commit/61b06befc2171476b97be8b6fc7ec728ccc8ce19">61b06befc2171476b97be8b6fc7ec728ccc8ce19</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7919/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7919/jenkins-report.html">here</a>.</h5></details></html>

2024-05-20 20:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7919/">test-portal-source-format#7919</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7919/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3367">liferay-objects#3367</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2570464111">[master] ci:test:sf - G-Sa &gt; liferay-objects - PR#3367 - 2024-05-20[13:35:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2570464111<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/31204/">publish-testray-report#31204</a><br/></div></div>

2024-05-20 20:53 UTC, marcelabc commented
Just started reviewing :)

2024-05-21 01:28 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-05-21 01:28 UTC, marcelabc commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/dto/v1_0/util/ObjectFieldUtil.java
> +		}
Please, use HashMap computeIfAbsent().

2024-05-21 01:28 UTC, marcelabc commented on modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/resource/v1_0/ObjectDefinitionResourceImpl.java
> +	}
We don't need this method. We can use computeIfAbsent() instead of this method in its usage.

2024-05-21 14:53 UTC, closed without merging

2024-05-21 14:54 UTC, carolmariaabb commented
https://github.com/liferay-objects/liferay-portal/pull/3371