LPD-19577 Create test for importing root model structures
liferay-objects/liferay-portal pull request #3375
Opened 2024-05-22 16:55 UTC by devpedrotavares

Follow up: https://github.com/brianchandotcom/liferay-portal/pull/150554

2024-05-22 16:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-05-22 16:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5503/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5503/jenkins-report.html">here</a>.</b></p>

2024-05-22 16:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b213d4e68ab87ca9c953a390cf2bc1e70fe03f14">b213d4e68ab87ca9c953a390cf2bc1e70fe03f14</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/devpedrotavares/liferay-portal/tree/LPD-19577_v2">LPD-19577_v2</a><br/>Branch GIT ID: <a href="https://github.com/devpedrotavares/liferay-portal/commit/77c335b4dd0ae613c75eba84ef37abfd8134722a">77c335b4dd0ae613c75eba84ef37abfd8134722a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5503/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5503/jenkins-report.html">here</a>.</h5></details></html>

2024-05-24 17:48 UTC, marcelabc commented
@carolmariaabb, even with the conflicts, can you suggest what you would do differently in this PR, please? 
And @devpedrotavares can do it together: rebase error and the improvements :+1:

2024-05-24 19:18 UTC, carolmariaabb requested changes

2024-05-24 19:18 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectFolderExportImportTest.java
>  		user = TestPropsValues.getUser();
@devpedrotavares reuse the existing `user`.. you don't need to do `user = TestPropsValues.getUser();`

2024-05-26 22:22 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
> +		String publishedObjectDefinitionJSON = jsonFactory.createJSONObject(
I prefer to maintain the prefix. Let's see...

2024-05-26 22:23 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/ObjectDefinitionExportImportTest.java
> +				"TESTOBJECTDEFINITION2"));
I think it is good to understand that the other object definition was created because of the relationship/root concept.

2024-05-26 22:26 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/portlet/action/test/BoundObjectDefinitionsExportImportTest.java
> +		String draftBoundObjectDefinitionsJSON = String.valueOf(
There is no need since we refactored the class.

2024-05-26 22:40 UTC, marcelabc commented
Thank you for all the suggestions, @carolmariaabb :heart: 

@devpedrotavares, please see https://github.com/liferay-objects/liferay-portal/pull/3385
cc: @G-Sa

2024-05-26 22:40 UTC, closed without merging