LPD-26861 make sure that a relationship field will not have its information processed before it is treated properly
liferay-objects/liferay-portal pull request #3386
Opened 2024-05-27 16:47 UTC by vngoliveira

[LPD-26861](https://liferay.atlassian.net/browse/LPD-26861)

2024-05-27 16:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-05-27 16:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7726/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7726/jenkins-report.html">here</a>.</b></p>

2024-05-27 16:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ef18447fb7969a9ab475fc6cda6f118b984742e2">ef18447fb7969a9ab475fc6cda6f118b984742e2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-26861">LPD-26861</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/3ce2a3c3593f9448b1b049035b9744cbb752737c">3ce2a3c3593f9448b1b049035b9744cbb752737c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7726/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7726/jenkins-report.html">here</a>.</h5></details></html>

2024-05-27 16:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7726/">test-portal-source-format#7726</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7726/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3386">liferay-objects#3386</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2572420388">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3386 - 2024-05-27[09:48:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2572420388<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4092/">publish-testray-report#4092</a><br/></div></div>

2024-05-27 17:59 UTC, carolmariaabb requested changes

2024-05-27 17:59 UTC, carolmariaabb commented on modules/apps/object/object-info-api/src/main/java/com/liferay/object/info/item/provider/util/ObjectEntryInfoItemValuesProviderUtil.java
>  				continue;
@vngoliveira we should include the info field value for relationship fields. Please try to fix the code where the NPE is happening. 

In the [SiteObjectScopeProviderImpl](https://github.com/liferay/liferay-portal/blob/bdae4717b6a049554992063ab13a1fb1035d1bac/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/scope/SiteObjectScopeProviderImpl.java#L35), you can try to do something like:

```
@Override
public long getGroupId(HttpServletRequest httpServletRequest)
	throws PortalException {

	ThemeDisplay themeDisplay =
		(ThemeDisplay)httpServletRequest.getAttribute(
			WebKeys.THEME_DISPLAY);

	if (themeDisplay != null) {
		return themeDisplay.getScopeGroupId();
	}

	ServiceContext serviceContext =
		ServiceContextThreadLocal.getServiceContext();

	if (serviceContext == null) {
		return 0;
	}

	return serviceContext.getScopeGroupId();
}
```

2024-05-27 17:59 UTC, carolmariaabb commented on modules/apps/object/object-info-api/src/main/java/com/liferay/object/info/item/provider/util/ObjectEntryInfoItemValuesProviderUtil.java
@vngoliveira please send the PR with an integration test

2024-05-28 17:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a17da301a6b8ebdd9732cefd922bfc317262b35f">a17da301a6b8ebdd9732cefd922bfc317262b35f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-26861">LPD-26861</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/6df4cffd4f0d91d02731b24a4c54fb60b87b7eba">6df4cffd4f0d91d02731b24a4c54fb60b87b7eba</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3413/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3413/jenkins-report.html">here</a>.</h5></details></html>

2024-05-28 17:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3413/">test-portal-source-format#3413</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3413/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3386">liferay-objects#3386</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2572769949">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3386 - 2024-05-28[10:26:50]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2572769949<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/13608/">publish-testray-report#13608</a><br/></div></div>

2024-05-29 11:36 UTC, carolmariaabb requested changes

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> +			_group.getGroupId());
@vngoliveira this variable is only used by one test: `testObjectEntryInfoItemFieldValuesProvider`.

That said, I see no reason to make it global and add it here in the `setUp` method.

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> +		_mockHttpServletRequest = new MockHttpServletRequest();
@vngoliveira this variable is only used by one test `testObjectEntryInfoItemFieldValuesProvider`.

That said, I see no reason to make it global and add it here in the `setUp` method.

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> -		ServiceContextThreadLocal.pushServiceContext(serviceContext);
@vngoliveira we still have the `ServiceContextThreadLocal.popServiceContext()` in the `tearDown` method. But you removed the `ServiceContextThreadLocal.pushServiceContext(serviceContext)` from the  `setUp` method.

That said, we also need remove the `ServiceContextThreadLocal.popServiceContext()` from the `tearDown` method and change the test to something like:

```
ServiceContextThreadLocal.pushServiceContext(serviceContext);

try {
   // all the logic
}
finally {
   ServiceContextThreadLocal.popServiceContext();
}

```

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> -		ServiceContextThreadLocal.pushServiceContext(serviceContext);
This way we guarantee that only what was "pushed" will be removed from the stack.

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> +		ServiceContextThreadLocal.pushServiceContext(_serviceContext);
@vngoliveira notice that you are calling the "push" method twice here. So you also need to call the "pop" twice.

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> +		// ThemeDisplay attribute
@vngoliveira simplify to `HttpServletRequest with null themeDisplay`

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> +		// ThemeDisplay attribute
@vngoliveira simplify to `HttpServletRequest with themeDisplay`

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> +	private void _assertValues(
@vngoliveira rename it to `_assertInfoFieldValues`

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> +			parentTextObjectFieldNameValue);
@vngoliveira inline:

```
_assertInfoFieldValues(
	fileEntry, infoItemFieldValuesProvider.getInfoItemFieldValues(objectEntry),
	objectAction, parentTextObjectFieldNameValue);
```

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> +			parentTextObjectFieldNameValue);
@vngoliveira inline:

```
_assertInfoFieldValues(
	fileEntry, infoItemFieldValuesProvider.getInfoItemFieldValues(objectEntry),
	objectAction, parentTextObjectFieldNameValue);
```

2024-05-29 11:36 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
@vngoliveira my suggestion:

```
@Test
public void testObjectEntryInfoItemFieldValuesProvider() throws Exception {
	FileEntry fileEntry = _dlAppLocalService.addFileEntry(
		null, TestPropsValues.getUserId(), _group.getGroupId(),
		DLFolderConstants.DEFAULT_PARENT_FOLDER_ID, "test.txt",
		ContentTypes.TEXT, RandomTestUtil.randomBytes(), null, null, null,
		ServiceContextTestUtil.getServiceContext(_group.getGroupId()));

	String parentTextObjectFieldNameValue = RandomTestUtil.randomString();

	ObjectEntry parentObjectEntry = _objectEntryLocalService.addObjectEntry(
		TestPropsValues.getUserId(), _group.getGroupId(),
		_parentObjectDefinition.getObjectDefinitionId(),
		HashMapBuilder.<String, Serializable>put(
			"parentTextObjectFieldName", parentTextObjectFieldNameValue
		).build(),
		ServiceContextTestUtil.getServiceContext());

	ObjectEntry objectEntry = _objectEntryLocalService.addObjectEntry(
		TestPropsValues.getUserId(), _group.getGroupId(),
		_childObjectDefinition.getObjectDefinitionId(),
		HashMapBuilder.<String, Serializable>put(
			"r_oneToManyRelationshipName_" +
				_parentObjectDefinition.getPKObjectFieldName(),
			parentObjectEntry.getObjectEntryId()
		).put(
			"attachmentObjectFieldName", fileEntry.getFileEntryId()
		).put(
			"picklistObjectFieldName", _listTypeEntryKey
		).build(),
		ServiceContextTestUtil.getServiceContext());

	ObjectAction objectAction = _objectActionLocalService.addObjectAction(
		RandomTestUtil.randomString(), TestPropsValues.getUserId(),
		objectEntry.getObjectDefinitionId(), true, StringPool.BLANK,
		RandomTestUtil.randomString(),
		LocalizedMapUtil.getLocalizedMap(RandomTestUtil.randomString()),
		LocalizedMapUtil.getLocalizedMap(RandomTestUtil.randomString()),
		RandomTestUtil.randomString(),
		ObjectActionExecutorConstants.KEY_WEBHOOK,
		ObjectActionTriggerConstants.KEY_STANDALONE,
		UnicodePropertiesBuilder.put(
			"url", RandomTestUtil.randomString()
		).build(),
		false);

	// HttpServletRequest with null themeDisplay

	_testObjectEntryInfoItemFieldValuesProvider(
		fileEntry, objectAction, objectEntry,
		parentTextObjectFieldNameValue, null);

	// HttpServletRequest with themeDisplay

	ThemeDisplay themeDisplay = new ThemeDisplay();

	themeDisplay.setCompany(
		_companyLocalService.getCompany(_group.getCompanyId()));
	themeDisplay.setLocale(LocaleUtil.getDefault());
	themeDisplay.setScopeGroupId(_group.getGroupId());
	themeDisplay.setSiteGroupId(_group.getGroupId());
	themeDisplay.setTimeZone(TimeZoneUtil.getDefault());
	themeDisplay.setUser(TestPropsValues.getUser());

	_testObjectEntryInfoItemFieldValuesProvider(
		fileEntry, objectAction, objectEntry,
		parentTextObjectFieldNameValue, themeDisplay);
}

private void _testObjectEntryInfoItemFieldValuesProvider(
		FileEntry fileEntry, ObjectAction objectAction,
		ObjectEntry objectEntry, String parentTextObjectFieldNameValue,
		ThemeDisplay themeDisplay)
	throws Exception {

	ServiceContext serviceContext =
		ServiceContextTestUtil.getServiceContext(_group.getGroupId());

	MockHttpServletRequest mockHttpServletRequest =
		new MockHttpServletRequest();

	mockHttpServletRequest.setAttribute(
		WebKeys.THEME_DISPLAY, themeDisplay);

	serviceContext.setRequest(mockHttpServletRequest);

	ServiceContextThreadLocal.pushServiceContext(serviceContext);

	try {
		InfoItemFieldValuesProvider<ObjectEntry>
			infoItemFieldValuesProvider =
				_infoItemServiceRegistry.getFirstInfoItemService(
					InfoItemFieldValuesProvider.class,
					_childObjectDefinition.getClassName());

		InfoItemFieldValues infoItemFieldValues =
			infoItemFieldValuesProvider.getInfoItemFieldValues(objectEntry);

		Assert.assertNotNull(infoItemFieldValues);

		InfoFieldValue<Object> infoLocalizedValue =
			infoItemFieldValues.getInfoFieldValue(objectAction.getName());

		Map<Locale, String> labelMap = objectAction.getLabelMap();

		for (Map.Entry<Locale, String> entry : labelMap.entrySet()) {
			Assert.assertEquals(
				entry.getValue(),
				infoLocalizedValue.getValue(entry.getKey()));
		}

		ObjectField objectField = _objectFieldLocalService.fetchObjectField(
			_childObjectDefinition.getObjectDefinitionId(),
			"attachmentObjectFieldName");

		InfoFieldValue<Object> downloadURLInfoFieldValue =
			infoItemFieldValues.getInfoFieldValue(
				objectField.getObjectFieldId() + "#downloadURL");

		Assert.assertEquals(
			HttpComponentsUtil.removeParameter(
				_dlURLHelper.getDownloadURL(
					fileEntry, fileEntry.getFileVersion(), null,
					StringPool.BLANK),
				"t"),
			HttpComponentsUtil.removeParameter(
				String.valueOf(downloadURLInfoFieldValue.getValue()), "t"));

		_assertInfoFieldValue(
			"#fileName", infoItemFieldValues, objectField,
			fileEntry.getFileName());
		_assertInfoFieldValue(
			"#mimeType", infoItemFieldValues, objectField,
			fileEntry.getMimeType());
		_assertInfoFieldValue(
			"#size", infoItemFieldValues, objectField, fileEntry.getSize());

		InfoFieldValue<Object> parentTextObjectFieldNameInfoFieldValue =
			infoItemFieldValues.getInfoFieldValue(
				"parentTextObjectFieldName");

		Assert.assertEquals(
			parentTextObjectFieldNameValue,
			parentTextObjectFieldNameInfoFieldValue.getValue());

		InfoFieldValue<Object> picklistObjectFieldNameInfoFieldValue =
			infoItemFieldValues.getInfoFieldValue(
				"picklistObjectFieldName");

		for (KeyLocalizedLabelPair keyLocalizedLabelPair :
				(ArrayList<KeyLocalizedLabelPair>)
					picklistObjectFieldNameInfoFieldValue.getValue()) {

			Assert.assertEquals(
				_listTypeEntryKey, keyLocalizedLabelPair.getKey());
		}
	}
	finally {
		ServiceContextThreadLocal.popServiceContext();
	}
}
```

2024-05-29 12:47 UTC, vngoliveira commented
ci:test:sf

2024-05-29 12:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3417/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3417/jenkins-report.html">here</a>.</b></p>

2024-05-29 12:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3417/">test-portal-source-format#3417</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3417/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3386">liferay-objects#3386</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573181423">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3386 - 2024-05-29[05:48:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2573181423<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/13615/">publish-testray-report#13615</a><br/></div></div>

2024-05-29 15:00 UTC, carolmariaabb requested changes

2024-05-29 15:00 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/info/item/provider/test/ObjectEntryInfoItemFieldValuesProviderTest.java
> -		ServiceContextThreadLocal.pushServiceContext(serviceContext);
@vngoliveira as explained, please also delete the `tearDown` method

2024-05-29 16:50 UTC, vngoliveira commented
ci:test:sf

2024-05-29 16:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3115/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3115/jenkins-report.html">here</a>.</b></p>

2024-05-29 16:57 UTC, carolmariaabb approved these changes

2024-05-29 16:57 UTC, carolmariaabb commented
ci:test:object

2024-05-29 16:57 UTC, carolmariaabb commented
ci:test:relevant

2024-05-29 17:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/6058/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6058/jenkins-report.html">here</a>.</b></p>

2024-05-29 17:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6308/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6308/jenkins-report.html">here</a>.</b></p>

2024-05-29 18:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 31 out of 31 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 42 out of 44 jobs passed in 1 hour 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/344689f54b5ede48c9610059aed6ca63f777ba41">344689f54b5ede48c9610059aed6ca63f777ba41</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d5e2598e28c11b5dcbf55e181bdbaea49eff3835">d5e2598e28c11b5dcbf55e181bdbaea49eff3835</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573267673">EE Development Acceptance (master) - 564 - 2024-05-29[04:38:01]</a></p><details><summary><strong>ci:test:stable - 31 out of 31 jobs PASSED</strong></summary><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 41 out of 44 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6308/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013152/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894466/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021159/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998731/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1118814/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/393899/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/393900/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431742/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1117411/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998735/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435193/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435191/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021161/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998732/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/604760/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1118813/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/604761/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021163/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431741/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013154/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998733/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/647268/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1117409/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021162/">modules-compile-jdk8/0/12</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998736/"><strike>modules-integration-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928657/">modules-integration-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1117412/">modules-integration-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013155/">modules-integration-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/647269/"><strike>modules-integration-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1118812/">modules-integration-mysql57-jdk8/0/5</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/882999/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998734/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/647267/">modules-semantic-versioning-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/604759/">modules-unit-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894465/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>patching-tool-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013153/">patching-tool-mysql57-jdk8/0/0</a></li></ul></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021160/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/647270/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435192/" [...]

2024-05-29 18:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6308/">test-portal-acceptance-pullrequest(master)#6308</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6308/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3386">liferay-objects#3386</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573386894">[master] ci:test:relevant - vngoliveira &gt; liferay-objects - PR#3386 - 2024-05-29[10:13:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2573386894<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/24220/">publish-testray-report#24220</a><br/></div></div>

2024-05-29 19:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 404 out of 442 jobs passed in 2 hours 5 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/565">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1337401_6058</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/344689f54b5ede48c9610059aed6ca63f777ba41">344689f54b5ede48c9610059aed6ca63f777ba41</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d5e2598e28c11b5dcbf55e181bdbaea49eff3835">d5e2598e28c11b5dcbf55e181bdbaea49eff3835</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573267673">EE Development Acceptance (master) - 564 - 2024-05-29[04:38:01]</a></p><details><summary><strong>ci:test:object - 404 out of 442 jobs PASSED</strong></summary><div><h4>38 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/6058/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431756/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/883023/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998759/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/345042/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/395567/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328795/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431753/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/404739/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/953509/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435204/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/345043/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/395568/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/338741/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/338744/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/901019/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013183/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928683/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1118841/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/404742/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/964222/"><strike>functional-tomcat90-mysql57-jdk8/1/16</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431755/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013182/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998761/">functional-tomcat90-mysql57-jdk8/1/19</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1118840/">functional-tomcat90-mysql57-jdk8/1/20</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328797/">functional-tomcat90-mysql57-jdk8/1/21</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021183/"><strike>functional-tomcat90-mysql57-jdk8/1/22</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/964221/"><strike>functional-tomcat90-mysql57-jdk8/1/23</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885908/"><strike>functional-tomcat90-mysql57-jdk8/1/24</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/839023/">functional-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/604795/">functional-tomcat90-mysql57-jdk8/2/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1118846/">functional-tomcat90-mysql57-jdk8/2/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328798/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/393915/">functional-tomcat90-mysql57-jdk8/2/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885919/">functional-tomcat90-mysql57-jdk8/2/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/953514/">functional-tomcat90-mysql57-jdk8/2/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/964234/">functional-tomcat90-mysql57-jdk8/2/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/928693/">functional-tomcat90-mysql57-jdk8/2/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998757/"><strike>functional-tomcat90-mysql57-jdk8/2/9</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431771/">functional-tomcat90-mysql57-jdk8/2/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/647312/">functional-tomcat90-mysql57-jdk8/2/11</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(maste [...]

2024-05-29 19:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/6058/">test-portal-acceptance-pullrequest(master)#6058</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6058/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3386">liferay-objects#3386</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573404577">[master] ci:test:object - vngoliveira &gt; liferay-objects - PR#3386 - 2024-05-29[10:10:26]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2573404577<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/13205/">publish-testray-report#13205</a><br/></div></div>

2024-05-29 19:48 UTC, carolmariaabb commented
ci:forward:force

2024-05-29 19:48 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-05-29 19:48 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-05-29 19:49 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/1306//consoleFull)

2024-05-29 19:49 UTC, closed without merging

2024-05-29 19:49 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/150812
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/1306//consoleFull)