LPD-27467
liferay-objects/liferay-portal pull request #3440
Opened 2024-06-11 14:54 UTC by G-Sa

Related to: [LPD-27467](https://liferay.atlassian.net/browse/LPD-27467)

2024-06-11 14:54 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-06-11 14:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/6322/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6322/jenkins-report.html">here</a>.</b></p>

2024-06-11 15:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9c71fb94ab8212d95c37a43c84f20cc95df0438b">9c71fb94ab8212d95c37a43c84f20cc95df0438b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/G-Sa/liferay-portal/tree/LPD-27467">LPD-27467</a><br/>Branch GIT ID: <a href="https://github.com/G-Sa/liferay-portal/commit/de6acab2cf477f9527d5f0b78de74e1c2ebbc60b">de6acab2cf477f9527d5f0b78de74e1c2ebbc60b</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/6322/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6322/jenkins-report.html">here</a>.</h5><pre>     [exec]   at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
     [exec]   at org.gradle.composite.internal.DefaultBuildController\$BuildOpRunnable.run(DefaultBuildController.java:198)
     [exec]   at org.gradle.internal.concurrent.ExecutorPolicy\$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]   at org.gradle.internal.concurrent.AbstractManagedExecutor\$1.run(AbstractManagedExecutor.java:47)
     [exec] 
     [exec] 
     [exec] BUILD FAILED in 1m 14s
     [echo] 
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;exec dir="/opt/dev/projects/github/liferay-portal/modules/test/playwright" executable="/opt/dev/projects/github/liferay-portal/gradlew" failonerror="true"&gt;
  &lt;arg value="--max-workers=4" /&gt;
  &lt;arg value="--no-daemon" /&gt;
  &lt;arg value="--profile" /&gt;
  &lt;arg value="--project-cache-dir=/opt/dev/projects/github/liferay-portal/.gradle" /&gt;
  &lt;arg value="--stacktrace" /&gt;
  &lt;arg value="-Dapp.server.parent.dir=/opt/dev/projects/github/liferay-portal/bundles" /&gt;
  &lt;arg value="-Dforced.cache.enabled=true" /&gt;
  &lt;arg value="-Dliferay.home=/opt/dev/projects/github/liferay-portal/bundles" /&gt;
  &lt;arg value="-Dorg.gradle.internal.http.connectionTimeout=120000" /&gt;
  &lt;arg value="-Dorg.gradle.internal.http.socketTimeout=120000" /&gt;
  &lt;arg line="packageRunCheckFormat" /&gt;
&lt;/exec&gt;
[stopwatch] [run.batch.test.action: 5:01.586 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:718: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:1026: Unable to execute Gradle task: packageRunCheckFormat.
      [get] Getting: http://test-1-5/job/test-portal-source-format/6322//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240611080139012.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240611080139012.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null277862444.properties</pre></details></html>

2024-06-11 15:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/6322/">test-portal-source-format#6322</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6322/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3440">liferay-objects#3440</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/14679411">[master] ci:test:sf - G-Sa &gt; liferay-objects - PR#3440 - 2024-06-11[07:54:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>14679411<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/3063/">publish-testray-report#3063</a><br/></div></div>

2024-06-11 16:37 UTC, G-Sa commented
ci:test:sf

2024-06-11 17:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/6326/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6326/jenkins-report.html">here</a>.</b></p>

2024-06-11 17:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0028e9ea6a713f318f9eef73ecdd2473c93e2f20">0028e9ea6a713f318f9eef73ecdd2473c93e2f20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/G-Sa/liferay-portal/tree/LPD-27467">LPD-27467</a><br/>Branch GIT ID: <a href="https://github.com/G-Sa/liferay-portal/commit/9c6ab9f0cff3ea8aea4bdec21f72151146a76e4f">9c6ab9f0cff3ea8aea4bdec21f72151146a76e4f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/6326/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6326/jenkins-report.html">here</a>.</h5></details></html>

2024-06-11 17:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/6326/">test-portal-source-format#6326</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6326/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3440">liferay-objects#3440</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/14849836">[master] ci:test:sf - G-Sa &gt; liferay-objects - PR#3440 - 2024-06-11[10:09:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>14849836<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/3065/">publish-testray-report#3065</a><br/></div></div>

2024-06-12 14:13 UTC, igor-franca requested changes
Hey @G-Sa, nice work! Just some comments 😄

2024-06-12 14:13 UTC, igor-franca commented on modules/test/playwright/tests/object-web/objectEntries.spec.ts
Hey @G-Sa, in short, I missed two things here.

First I realized that we don't use the concept of pages here, working on the process of increasing pages can make the process of writing new tests in the future faster. There are some locators used here that have already been implemented on the `ViewObjectEntriesPage` page.

Furthermore, we need to implement the clean up stage of your test. Here we create some entities like objectDefinition, user, role. And we need to delete these entities at the end of our test to prevent this from causing side effects in the next tests that will be executed in sequence.

2024-06-13 14:34 UTC, G-Sa commented on modules/test/playwright/helpers/ObjectAdminApiHelper.ts
> +		objectDefinition: DataObject
Using the ObjectDefinition interface here would require us to send way more information than its needed in this context, the code would grow from this
```
{
					active: false,
					externalReferenceCode: boundObjectDefinitionERC,
					label: {
						en_US: 'BoundObject',
					},
					name: 'BoundObject' + getRandomInt(),
					objectFields: [
						{
							DBType: 'String',
							businessType: 'Text',
							externalReferenceCode: 'text',
							indexed: true,
							indexedAsKeyword: true,
							label: {
								en_US: 'text',
							},
							name: 'text',
							required: false,
							system: false,
							type: 'String',
						},
					],
					panelCategoryKey: '',
					pluralLabel: {
						en_US: 'BoundObject',
					},
					rootObjectDefinitionExternalReferenceCode:
						rootObjectDefinitionERC,
					scope: 'company',
					status: {
						code: 2,
					},
					titleObjectFieldName: 'text',
				}
```

to this
```
{
					active: false,
					externalReferenceCode: boundObjectDefinitionERC,
					label: {
						en_US: 'BoundObject',
					},
					name: 'BoundObject' + getRandomInt(),
					objectFields: [
						{
							DBType: 'String',
							businessType: 'Text',
							externalReferenceCode: 'text',
							indexed: true,
							indexedAsKeyword: true,
							label: {
								en_US: 'text',
							},
							name: 'text',
							required: false,
							system: false,
							localized: false,
							readOnly: '',
							state: false
						},
					],
					panelCategoryKey: '',
					pluralLabel: {
						en_US: 'BoundObject',
					},
					rootObjectDefinitionExternalReferenceCode: rootObjectDefinitionERC,
					scope: 'company',
					status: {
						code: 2,
						label: '',
						label_i18n: ''
					},
					titleObjectFieldName: 'text',
					accountEntryRestricted: false,
					accountEntryRestrictedObjectFieldId: '',
					accountEntryRestrictedObjectFieldName: '',
					actions: undefined,
					dateCreated: '',
					dateModified: '',
					defaultLanguageId: 'ar_SA',
					enableCategorization: false,
					enableComments: false,
					enableLocalization: false,
					enableObjectEntryDraft: false,
					enableObjectEntryHistory: false,
					id: 0,
					objectActions: [],
					objectFolderExternalReferenceCode: '',
					objectLayouts: [],
					objectRelationships: [],
					objectViews: [],
					portlet: false,
					restContextPath: '',
					system: false,
					titleObjectFieldId: ''
				}
```

Wich i don't think its helpfull

2024-06-13 14:43 UTC, G-Sa commented on modules/test/playwright/tests/object-web/objectEntries.spec.ts
This user is from the `users-admin-demo` module, which is deployed at the start of the runs in CI (according to the playwright[ channel here](https://liferay.slack.com/archives/C06A59K5D46/p1712312909434259?thread_ts=1712312701.496309&cid=C06A59K5D46), so i dont think we should delete it on the cleanup phase.

The Object Definitions sadly cannot be deleted either because of the current limitations of Published Root Models, so they will only get deleted when the environment gets cleared entirely. This is the main reason behind the randomInt() necessity in their names.

Will add the deletion for the Role created

2024-06-13 14:50 UTC, G-Sa commented on modules/test/playwright/tests/object-web/objectEntries.spec.ts
Actually it appears that we do not have an API endpoint to deleting roles :sweat_smile:

2024-06-13 18:07 UTC, G-Sa commented
hey @igor-franca please take a second look when you are avaliable!

2024-06-13 18:56 UTC, igor-franca commented on modules/test/playwright/helpers/ObjectAdminApiHelper.ts
> +		objectDefinition: DataObject
So we can try use `Partial<ObjectDefinition>` to avoid send a property don't mapped in ObjectDefinitionDTO

2024-06-13 20:25 UTC, igor-franca requested changes

2024-06-13 20:25 UTC, igor-franca commented on modules/test/playwright/tests/object-web/objectEntries.spec.ts
> +		test.setTimeout(180000);
Hey @G-Sa, did you face some timeout issues when trying to run your test without this property?

2024-06-13 20:25 UTC, igor-franca commented on modules/test/playwright/tests/object-web/objectEntries.spec.ts
> +		// Clean up
Hey @G-Sa, we can think of other approaches to cleaning the data related to the root model, we can start a discussion about running these tests in another instance. We can also look for other suggestions related to this topic.

2024-06-13 20:25 UTC, igor-franca commented on modules/test/playwright/types/locators.d.ts
> + * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
Could you use the current year here? Thanks!

2024-06-20 13:53 UTC, G-Sa commented
ci:test:sf

2024-06-20 13:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5578/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5578/jenkins-report.html">here</a>.</b></p>

2024-06-20 13:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9f66856ed9d25029d096b0efcd5927358e8c0000">9f66856ed9d25029d096b0efcd5927358e8c0000</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/G-Sa/liferay-portal/tree/LPD-27467">LPD-27467</a><br/>Branch GIT ID: <a href="https://github.com/G-Sa/liferay-portal/commit/eee3ad449f2b6816a14a3fc074449d058b1a105c">eee3ad449f2b6816a14a3fc074449d058b1a105c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5578/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5578/jenkins-report.html">here</a>.</h5></details></html>

2024-06-20 14:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5578/">test-portal-source-format#5578</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5578/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3440">liferay-objects#3440</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/22235387">[master] ci:test:sf - G-Sa &gt; liferay-objects - PR#3440 - 2024-06-20[06:54:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>22235387<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/22049/">publish-testray-report#22049</a><br/></div></div>

2024-06-20 14:14 UTC, igor-franca requested changes
Good job @G-Sa, just a few details

2024-06-20 14:14 UTC, igor-franca commented on modules/test/playwright/tests/object-web/objectEntries.spec.ts
> +		// Clean up
Hey Sa, can you check the feasibility of creating a new instance?

2024-06-21 13:42 UTC, G-Sa commented
We will come back to this Test once we are able to implement either the isolatedInstance fixture or the delete functionality for published root models

2024-06-21 13:42 UTC, closed without merging