LPD-28108
liferay-objects/liferay-portal pull request #3475
Opened 2024-07-01 13:59 UTC by icgsbr

https://liferay.atlassian.net/browse/LPD-28108

2024-07-01 14:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3552/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3552/jenkins-report.html">here</a>.</b></p>

2024-07-01 14:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c5d35a713c67869772c2e2dca1d22a1be5f6892c">c5d35a713c67869772c2e2dca1d22a1be5f6892c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/icgsbr/liferay-portal/tree/LPD-28108">LPD-28108</a><br/>Branch GIT ID: <a href="https://github.com/icgsbr/liferay-portal/commit/3ce762e032d9f64c48e0d3250a6dc7627e9ed462">3ce762e032d9f64c48e0d3250a6dc7627e9ed462</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3552/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3552/jenkins-report.html">here</a>.</h5></details></html>

2024-07-01 14:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3552/">test-portal-source-format#3552</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3552/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3475">liferay-objects#3475</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/28692401">[master] ci:test:sf - icgsbr &gt; liferay-objects - PR#3475 - 2024-07-01[07:00:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>28692401<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/24536/">publish-testray-report#24536</a><br/></div></div>

2024-07-02 11:38 UTC, icgsbr commented
ci:test:sf

2024-07-08 20:03 UTC, rebsilva requested changes
since igor is on vacation, i will make the modifications and send the PR again, thanks! :star:

2024-07-09 10:57 UTC, rebsilva requested changes

2024-07-09 10:57 UTC, rebsilva commented on modules/test/playwright/pages/object-web/ViewObjectDefinitionsPage.ts
> +
maybe this should be in another page...investigate how the structure is presented today

2024-07-09 10:57 UTC, rebsilva commented on modules/test/playwright/pages/object-web/list-type/ListTypeDefinitionsPage.ts
> +		await this.page.frameLocator('iframe').getByRole('menuitem', { name: `${locationCode} Untranslated` });
maybe transform this into a function

2024-07-09 10:57 UTC, rebsilva commented on modules/test/playwright/tests/object-web/listTypeDefinitions.spec.ts
> +		await viewObjectDefinitionsPage.clickAddObjectField(objectDefinition.label['en_US'], 'Picklist', fieldLabel);
change `clickAddObjectField` to `addObjectField`

2024-07-09 12:27 UTC, rebsilva commented on modules/test/playwright/pages/dynamic-data-mapping-form-web/FormBuilderPage.ts
> +		this.selectFromList = page.getByRole('button', { name: 'Press enter to add Select from List field. Select from List Select options from a list.' });
this corresponds to the select from list field type on the forms sidebar; it's better to create a 
generic function where you pass the field type name or label and you get the field

2024-07-09 12:55 UTC, rebsilva commented on modules/test/playwright/pages/dynamic-data-mapping-form-web/FormBuilderPage.ts
> +		this.selectFromList = page.getByRole('button', { name: 'Press enter to add Select from List field. Select from List Select options from a list.' });
there is the `addFieldByDoubleClick` function already on `FormBuilderSidePanelPage`

2024-07-09 12:58 UTC, rebsilva commented on modules/test/playwright/pages/dynamic-data-mapping-form-web/FormBuilderPage.ts
> +		this.selectFromList = page.getByRole('button', { name: 'Press enter to add Select from List field. Select from List Select options from a list.' });
also just realized that this selector is not being used anywhere :thought_balloon:

2024-07-09 13:03 UTC, rebsilva commented on modules/test/playwright/pages/dynamic-data-mapping-form-web/FormBuilderSidePanelPage.ts
> +	async clickCloseButton() {
this is not being used anywhere, so remove it

2024-07-09 14:10 UTC, rebsilva commented on modules/test/playwright/pages/object-web/list-type/ListTypeDefinitionsPage.ts
> +		await this.savePicklistButton.waitFor({ state: 'visible' });
i think is better to wait for other element in the page instead of the save button, for example the basic info title

2024-07-15 17:56 UTC, rebsilva commented
new PR here https://github.com/liferay-objects/liferay-portal/pull/3511

2024-07-15 17:56 UTC, closed without merging