LPD-29610
liferay-objects/liferay-portal pull request #3571
Opened 2024-08-06 18:20 UTC by pedro-oliveira446

2024-08-06 18:20 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-08-06 18:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6023/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6023/jenkins-report.html">here</a>.</b></p>

2024-08-06 18:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0df485fb861c1d96f6a5e090c0a9a0fe4a022435">0df485fb861c1d96f6a5e090c0a9a0fe4a022435</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-29610">LPD-29610</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/18beb034f973978da1d1063cdad7d84be8b437b8">18beb034f973978da1d1063cdad7d84be8b437b8</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6023/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6023/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Incorrect commit message: Missing breaking change in commit messages when the major version bumps up: ./modules/apps/object/object-api/bnd.bnd (SourceCheck:BNDBreakingChangeCommitMessageCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:469)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:53.719 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-28/job/test-portal-source-format/6023//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240806112334949.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240806112334949.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1819320242.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1013195832
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 147ms
[junitreport] Deleting: /tmp/null1013195832
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 08-06-2024 11:23:37:560 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.</pre></details></html>

2024-08-06 19:11 UTC, pedro-oliveira446 commented
ci:test:sf

2024-08-06 19:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6032/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6032/jenkins-report.html">here</a>.</b></p>

2024-08-06 19:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc650a95c1e659bee637afd5726872f5dca4436e">bc650a95c1e659bee637afd5726872f5dca4436e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-29610">LPD-29610</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/2016808e167e2656d64a89bcd43479300556286d">2016808e167e2656d64a89bcd43479300556286d</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6032/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6032/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found formatting issue in SHA 23691f062435a836a06e44cc62a9b22223bcf845
     [java] The commit message should not start with whitespace
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:35)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1316)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:337)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:31.425 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-28/job/test-portal-source-format/6032//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240806121519432.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240806121519432.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1686509624.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1215587062
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 148ms
[junitreport] Deleting: /tmp/null1215587062
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 08-06-2024 12:15:22:007 PDT
[stopwatch] [run.batch.test.tear.down: 0.001 sec]</pre></details></html>

2024-08-06 19:22 UTC, pedro-oliveira446 commented
ci:test:sf

2024-08-06 19:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6033/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6033/jenkins-report.html">here</a>.</b></p>

2024-08-06 19:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc650a95c1e659bee637afd5726872f5dca4436e">bc650a95c1e659bee637afd5726872f5dca4436e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-29610">LPD-29610</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/f74b8aa09b88d0408683c06386d4385b91916505">f74b8aa09b88d0408683c06386d4385b91916505</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6033/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6033/jenkins-report.html">here</a>.</h5></details></html>

2024-08-06 19:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6023/">test-portal-source-format#6023</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6023/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/54423384">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-06[11:20:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>54423384<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/22822/">publish-testray-report#22822</a><br/></div></div>

2024-08-06 20:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6032/">test-portal-source-format#6032</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6032/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/54436089">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-06[12:12:08]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>54436089<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/22832/">publish-testray-report#22832</a><br/></div></div>

2024-08-06 20:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6033/">test-portal-source-format#6033</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6033/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/54436232">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-06[12:22:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>54436232<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/22834/">publish-testray-report#22834</a><br/></div></div>

2024-08-08 20:42 UTC, MarinhoFeliphe requested changes
Good job @pedro-oliveira446!!

see my comments

2024-08-09 13:15 UTC, pedro-oliveira446 commented
ci:test:sf

2024-08-09 13:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/6351/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6351/jenkins-report.html">here</a>.</b></p>

2024-08-09 13:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1caa9ea428eceea1c1e355aac0c3109c292b12ca">1caa9ea428eceea1c1e355aac0c3109c292b12ca</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-29610">LPD-29610</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/45c77a2f863a51a7acc8cae9d054c1c38bd9264c">45c77a2f863a51a7acc8cae9d054c1c38bd9264c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6351/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6351/jenkins-report.html">here</a>.</h5></details></html>

2024-08-09 13:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6351/">test-portal-source-format#6351</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6351/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/57317733">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-09[06:16:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>57317733<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/23358/">publish-testray-report#23358</a><br/></div></div>

2024-08-09 13:28 UTC, pedro-oliveira446 commented
ci:test:relevant

2024-08-09 13:28 UTC, pedro-oliveira446 commented
ci:test:object

2024-08-09 13:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11169/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11169/jenkins-report.html">here</a>.</b></p>

2024-08-09 13:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9848/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9848/jenkins-report.html">here</a>.</b></p>

2024-08-09 16:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 34 out of 38 jobs passed in 2 hours 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1caa9ea428eceea1c1e355aac0c3109c292b12ca">1caa9ea428eceea1c1e355aac0c3109c292b12ca</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/76041b96ce6b6cd7caf741a6da571a348a26801a">76041b96ce6b6cd7caf741a6da571a348a26801a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/55627233">EE Development Acceptance (master) - 722 - 2024-08-07[08:39:05]</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 34 out of 38 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11169/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008861/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929179/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1169081/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050035/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455506/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415867/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924777/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071065/">js-unit-jdk8/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/349982/">js-unit-jdk8/1/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/952245/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429028/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061772/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/952246/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071064/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455507/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415866/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/349983/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1175163/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924776/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/364688/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1169080/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416861/">modules-compile-jdk8/0/12</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1169082/"><strike>modules-integration-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/889759/">modules-integration-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706490/">modules-integration-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/651971/">modules-integration-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/889758/">modules-integration-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929180/"><strike>modules-integration-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706489/">modules-integration-mysql57-jdk8/0/6</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/946257/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1020287/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1020286/">modules-semantic-versioning-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071063/">modules-unit-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/651970/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/364689/"><strike>playwright-js-tomcat90-mysql57-jdk8/0/0</strike></a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/955409/">playwright-js-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050036/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>34 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11169/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptan [...]

2024-08-09 16:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11169/">test-portal-acceptance-pullrequest(master)#11169</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11169/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/57399832">[master] ci:test:relevant - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-09[06:28:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>57399832<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/25742/">publish-testray-report#25742</a><br/></div></div>

2024-08-09 16:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 321 out of 332 jobs passed in 3 hours 27 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1caa9ea428eceea1c1e355aac0c3109c292b12ca">1caa9ea428eceea1c1e355aac0c3109c292b12ca</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/76041b96ce6b6cd7caf741a6da571a348a26801a">76041b96ce6b6cd7caf741a6da571a348a26801a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/55627233">EE Development Acceptance (master) - 722 - 2024-08-07[08:39:05]</a></p><details><summary><strong>ci:test:object - 321 out of 332 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9848/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/409436/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1175169/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924782/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050041/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/651979/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071075/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061779/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929187/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008865/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416863/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/349984/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071069/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050037/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924778/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/955460/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/652024/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061775/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416866/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/978630/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1169091/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/955417/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455510/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415870/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/349988/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061784/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061785/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/955410/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071070/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929184/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1175166/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924779/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050038/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/889760/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/952253/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1071071/"><strike>functional-tomcat90-mysql57-jdk8/1/8</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061776/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/952260/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455508/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/415868/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706494/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/349986/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/416865/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008867/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929188/">functional-tomcat90-mysql5 [...]

2024-08-09 17:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9848/">test-portal-acceptance-pullrequest(master)#9848</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9848/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/57431063">[master] ci:test:object - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-09[06:28:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>57431063<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/23474/">publish-testray-report#23474</a><br/></div></div>

2024-08-12 14:38 UTC, MarinhoFeliphe approved these changes
LGTM!! :tada:

Well done, @pedro-oliveira446 just apply my suggestion and forward it.

2024-08-12 14:38 UTC, MarinhoFeliphe commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/object/entries/display/context/test/ObjectEntryDisplayContextTest.java
> +			"AA1", objectDefinitionAA.getObjectDefinitionId());
Hey @pedro-oliveira446, just rename all objectEntries of this hierarchy to `objectEntryAA1`, `objectEntryA1`, ..

thanks!

2024-08-12 14:49 UTC, pedro-oliveira446 commented
ci:test:sf

2024-08-12 14:49 UTC, pedro-oliveira446 commented
ci:test:relevant

2024-08-12 14:49 UTC, pedro-oliveira446 commented
ci:test:object

2024-08-12 14:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6592/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6592/jenkins-report.html">here</a>.</b></p>

2024-08-12 14:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10565/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10565/jenkins-report.html">here</a>.</b></p>

2024-08-12 14:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/5960/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5960/jenkins-report.html">here</a>.</b></p>

2024-08-12 14:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9c0861322b3e11faf06eadd4179a938ed05ea000">9c0861322b3e11faf06eadd4179a938ed05ea000</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-29610">LPD-29610</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/d87839e145b872f37bb7c2e5d4484fdaf2c554d7">d87839e145b872f37bb7c2e5d4484fdaf2c554d7</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5960/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5960/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/object/entries/display/context/test/ObjectEntryDisplayContextTest.java expected:&lt;...hor Pedro Leite
     [java]  */
     [java] []@FeatureFlags("LPS-1...&gt; but was:&lt;...hor Pedro Leite
     [java]  */
     [java] [
     [java] ]@FeatureFlags("LPS-1...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:469)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:36.032 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-40/job/test-portal-source-format/5960//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240812075301819.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240812075301819.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1630157031.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null129618321
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 170ms
[junitreport] Deleting: /tmp/null129618321
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 08-12-2024 07:53:04:317 PDT</pre></details></html>

2024-08-12 14:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5960/">test-portal-source-format#5960</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5960/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/58981668">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-12[07:49:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>58981668<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/22566/">publish-testray-report#22566</a><br/></div></div>

2024-08-12 16:17 UTC, pedro-oliveira446 commented
ci:test:sf

2024-08-12 16:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/3991/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3991/jenkins-report.html">here</a>.</b></p>

2024-08-12 16:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/01cfb04de66b52f32fda80bf6e2c1e80dd61c336">01cfb04de66b52f32fda80bf6e2c1e80dd61c336</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-29610">LPD-29610</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/e63abd09abf633bf72d33873045b781a5e6f4f13">e63abd09abf633bf72d33873045b781a5e6f4f13</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3991/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3991/jenkins-report.html">here</a>.</h5></details></html>

2024-08-12 16:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3991/">test-portal-source-format#3991</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3991/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/59043309">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-12[09:18:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>59043309<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/26444/">publish-testray-report#26444</a><br/></div></div>

2024-08-12 16:40 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 82 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.RuntimeException: java.io.FileNotFoundException: https://testray.liferay.com/o/oauth2/token
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9c0861322b3e11faf06eadd4179a938ed05ea000">9c0861322b3e11faf06eadd4179a938ed05ea000</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10565/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10565/jenkins-report.html">here</a>.</b></p><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/10565/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/10565/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/10565/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-08-12 16:40 UTC, pedro-oliveira446 commented
ci:test:relevant

2024-08-12 16:41 UTC, pedro-oliveira446 commented
ci:test:object

2024-08-12 16:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6588/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6588/jenkins-report.html">here</a>.</b></p>

2024-08-12 16:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6589/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6589/jenkins-report.html">here</a>.</b></p>

2024-08-12 18:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6592/">test-portal-acceptance-pullrequest(master)#6592</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6592/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/59083341">[master] ci:test:object - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-12[07:49:59]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>59083341<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/24829/">publish-testray-report#24829</a><br/></div></div>

2024-08-12 18:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 38 out of 39 jobs passed in 1 hour 48 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/01cfb04de66b52f32fda80bf6e2c1e80dd61c336">01cfb04de66b52f32fda80bf6e2c1e80dd61c336</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/87fe9e7e3702cad5a391906fe2cc59abb3a2632e">87fe9e7e3702cad5a391906fe2cc59abb3a2632e</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/58678738">EE Development Acceptance (master) - 729 - 2024-08-11[20:39:03]</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 37 out of 39 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6588/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458049/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947659/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429672/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021641/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456095/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458050/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/925770/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/953627/">js-unit-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1176577/">js-unit-jdk8/1/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429670/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1176573/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/925769/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/953626/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458048/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/891074/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/956610/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707938/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1176574/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021640/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1063067/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429671/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458047/">modules-compile-jdk8/0/12</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1170313/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979848/">modules-integration-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947661/">modules-integration-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010084/">modules-integration-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947660/">modules-integration-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/891073/">modules-integration-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/930312/">modules-integration-mysql57-jdk8/0/6</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1176576/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/653301/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-semantic-versioning-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/953625/">modules-semantic-versioning-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458046/">modules-unit-jdk8/0/0</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1176575/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/653300/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456094/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1063066/">playwright-js-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/891072/">unit-jdk8_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>37 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6588/jenkins-report.html">h [...]

2024-08-12 18:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6588/">test-portal-acceptance-pullrequest(master)#6588</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6588/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/59098551">[master] ci:test:relevant - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-12[09:41:05]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>59098551<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/14694/">publish-testray-report#14694</a><br/></div></div>

2024-08-12 20:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 325 out of 330 jobs passed in 3 hours 22 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/01cfb04de66b52f32fda80bf6e2c1e80dd61c336">01cfb04de66b52f32fda80bf6e2c1e80dd61c336</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9c0861322b3e11faf06eadd4179a938ed05ea000">9c0861322b3e11faf06eadd4179a938ed05ea000</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/59079716">EE Development Acceptance (master) - 730 - 2024-08-12[08:38:37]</a></p><details><summary><strong>ci:test:object - 325 out of 330 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6589/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/930329/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/953646/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707954/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021656/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010099/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/653317/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979866/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350576/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456097/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/365217/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429675/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350572/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021652/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/891086/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/953642/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979862/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/653312/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350579/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/653320/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010102/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357698/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458055/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1063083/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/417443/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456100/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1072418/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350573/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1170326/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979863/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/953643/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707951/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/891087/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1176586/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1170327/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1051414/"><strike>functional-tomcat90-mysql57-jdk8/1/8</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/653313/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1170331/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1176590/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947681/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1021658/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/891092/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/707956/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/979868/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1170330/">functional-tomcat90-mysql57-jdk8 [...]

2024-08-12 20:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6589/">test-portal-acceptance-pullrequest(master)#6589</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6589/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3571">liferay-objects#3571</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/59217917">[master] ci:test:object - pedro-oliveira446 &gt; liferay-objects - PR#3571 - 2024-08-12[09:41:15]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>59217917<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/14696/">publish-testray-report#14696</a><br/></div></div>

2024-08-12 20:56 UTC, pedro-oliveira446 commented
ci:forward

2024-08-12 20:56 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-08-12 20:56 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-08-12 20:56 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/1347//consoleFull)

2024-08-12 20:57 UTC, closed without merging

2024-08-12 20:57 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/153220
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/1347//consoleFull)