LPD-31544
liferay-objects/liferay-portal pull request #3605
Opened 2024-08-20 17:17 UTC by pedro-oliveira446

2024-08-20 17:24 UTC, pedro-oliveira446 commented
ci:test:sf

2024-08-20 17:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/6413/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6413/jenkins-report.html">here</a>.</b></p>

2024-08-20 17:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d8ee37e5514d3808e97d492c2e1cf24d8dcd5a00">d8ee37e5514d3808e97d492c2e1cf24d8dcd5a00</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-31544">LPD-31544</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/8b424a9c30e42d3c3ae86d79b61d7eca8056b030">8b424a9c30e42d3c3ae86d79b61d7eca8056b030</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6413/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6413/jenkins-report.html">here</a>.</h5></details></html>

2024-08-20 17:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6413/">test-portal-source-format#6413</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6413/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3605">liferay-objects#3605</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/66765348">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3605 - 2024-08-20[10:24:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>66765348<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/23607/">publish-testray-report#23607</a><br/></div></div>

2024-08-22 13:10 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-08-22 13:10 UTC, marcelabc commented on modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/ObjectEntryResourceTest.java
> +	public void testPostCustomObjectEntryWithNestedPermissions()
The concept of `nested` only exists in the `GET` method. In `POST/PUT/PATCH` is a property of the Object Entry.

Can you rename this method to testPostCustomObjectEntryWithPermissions please?

2024-08-22 13:10 UTC, marcelabc commented on modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/ObjectEntryResourceTest.java
> +	public void testPostCustomObjectEntryWithNestedPermissions()
rename the private method please.

2024-08-22 13:10 UTC, marcelabc commented on modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/ObjectEntryResourceTest.java
> +		throws Exception {
Can you rename it to: `JSONArray expectedPermissionsJSONArray, JSONObject objectEntryJSONObject` ?

2024-08-22 13:10 UTC, marcelabc commented on modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/ObjectEntryResourceTest.java
> +
Don't need this empty line because the order of the tests does not matter.

2024-08-22 13:17 UTC, marcelabc commented
Hey @pedro-oliveira446 

This [commit](https://github.com/liferay-objects/liferay-portal/pull/3605/commits/a254df8e74e44715ec44255766d1944a211af67f) should be squashed with the one that you introduce this change (this [commit](https://github.com/liferay-objects/liferay-portal/pull/3605/commits/40348abe3ce985a820d31e65ee537e633ae6417d)).
Since the reviewer can review the PR per commit, a change in the same class but in different commits can slow down the review process because the reviewer will stop writing a comment, and the exact suggestion is implemented in X commits later.

When you introduce a method or a new logic, the final version is expected to be in the same commit. Refuting the code and adding a new commit later can be harder to understand than if the developer sees the final version in a single commit. Did you get it?

I'm here if you'd like to talk about it.

When you refactor the code, please squash the commits.

2024-08-22 16:57 UTC, pedro-oliveira446 commented
ci:test:sf

2024-08-22 16:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/6116/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6116/jenkins-report.html">here</a>.</b></p>

2024-08-22 17:02 UTC, pedro-oliveira446 commented on modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/ObjectEntryResourceTest.java
> +				_objectDefinition1.getRESTContextPath(), Http.Method.POST));
Hey @marcelabc,

I made the changes, but I'm not sure if this file is following the same pattern.

2024-08-22 17:03 UTC, pedro-oliveira446 commented
Hey @marcelabc,

I made the changes you requested, and the PR looks much better now. 

Thank you!

2024-08-22 17:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6116/">test-portal-source-format#6116</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6116/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3605">liferay-objects#3605</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/69248552">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3605 - 2024-08-22[09:57:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>69248552<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/23702/">publish-testray-report#23702</a><br/></div></div>

2024-08-23 14:51 UTC, carolmariaabb commented
https://github.com/liferay-objects/liferay-portal/pull/3612

2024-08-23 14:51 UTC, closed without merging