LPD-34415 Fixing some Commerce order freemarker notification template terms that wasn't working
liferay-objects/liferay-portal pull request #3610
Opened 2024-08-22 20:18 UTC by victorKammerer

[LPD-34415](https://liferay.atlassian.net/browse/LPD-34415)

2024-08-22 20:18 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-08-22 20:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/6439/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6439/jenkins-report.html">here</a>.</b></p>

2024-08-22 20:21 UTC, victorKammerer commented
This commit will be added on @devpedrotavares  [PR (#3606)](https://github.com/liferay-objects/liferay-portal/pull/3606)

2024-08-22 20:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/40edc4b461b9199149870fd98b6c31721dcc015b">40edc4b461b9199149870fd98b6c31721dcc015b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorKammerer/liferay-portal/tree/LPD-34415">LPD-34415</a><br/>Branch GIT ID: <a href="https://github.com/victorKammerer/liferay-portal/commit/c15545e74853dbf6f4ef183a476d533b460af5a6">c15545e74853dbf6f4ef183a476d533b460af5a6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6439/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6439/jenkins-report.html">here</a>.</h5></details></html>

2024-08-22 20:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6439/">test-portal-source-format#6439</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6439/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3610">liferay-objects#3610</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/69370925">[master] ci:test:sf - victorKammerer &gt; liferay-objects - PR#3610 - 2024-08-22[13:18:27]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>69370925<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/23687/">publish-testray-report#23687</a><br/></div></div>

2024-08-26 13:53 UTC, MarinhoFeliphe approved these changes
LGTM!! :tada:

@victorKammerer good job, it is safe, I'm not sure if we have to send this to commerce team I believe we can just notify them.

2024-08-26 17:17 UTC, MarinhoFeliphe requested changes
Hey @victorKammerer please try to provide a test for this class covering only the fields you modified, see this example `JournalArticleInfoItemFieldValuesProviderTest`.

Thanks!

2024-08-26 17:17 UTC, MarinhoFeliphe commented on modules/apps/commerce/commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/info/item/provider/CommerceOrderInfoItemFieldValuesProvider.java
> +						CommerceOrderConstants.ORDER_STATUS_COMPLETED)));
Hey @victorKammerer in the `InfoFieldValue` above we already have the map for `CommerceOrderConstants.ORDER_STATUS_COMPLETED`, I believe we can just replace `CommerceOrderInfoItemFields.companyIdInfoField` with `CommerceOrderInfoItemFields.completedOrderStatusInfoField`

2024-08-26 17:17 UTC, MarinhoFeliphe commented on modules/apps/commerce/commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/info/item/provider/CommerceOrderInfoItemFieldValuesProvider.java
> +					commerceOrder.getTotalWithTaxAmount()));
@victorKammerer this statement should came after the one related to `commerceOrder.getTotalDiscountWithTaxAmount()` to keep the asc sorting

2024-08-28 16:22 UTC, MarinhoFeliphe approved these changes
LGTM!! :tada:

@victorKammerer please forward to commerce team and close this pull request.

Thanks!

2024-08-28 16:24 UTC, closed without merging

2024-08-28 16:24 UTC, MarinhoFeliphe commented
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/5311