LPD-34975
liferay-objects/liferay-portal pull request #3626
Opened 2024-08-30 01:29 UTC by igor-franca

Related [ticket](https://liferay.atlassian.net/browse/LPD-26429)

2024-08-30 01:29 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-08-30 01:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6107/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6107/jenkins-report.html">here</a>.</b></p>

2024-08-30 01:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5247bf2b42851b742a149b9a08d6de691802357">e5247bf2b42851b742a149b9a08d6de691802357</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPD-34975">LPD-34975</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/62a8b88e17ab4de3160ac9e0a928167c52ec1c0f">62a8b88e17ab4de3160ac9e0a928167c52ec1c0f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6107/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6107/jenkins-report.html">here</a>.</h5></details></html>

2024-08-30 01:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6107/">test-portal-source-format#6107</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6107/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3626">liferay-objects#3626</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/75110282">[master] ci:test:sf - igor-franca &gt; liferay-objects - PR#3626 - 2024-08-29[18:29:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>75110282<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/23151/">publish-testray-report#23151</a><br/></div></div>

2024-09-02 19:30 UTC, danvb112 requested changes
Hey @igor-franca, great job refactoring the code! I have some suggestions :smile:

2024-09-02 19:30 UTC, danvb112 commented on modules/test/playwright/tests/object-web/utils/asyncFilter.ts
> +}
Hey @igor-franca, as we talked personally, I created this [commit](https://github.com/danvb112/liferay-portal/commit/5af0cd144a1cc942cf87e9a4c0463e2bc94f3cc8) by extracting the logic of the async Filter and async Find functions into a generic class, so we can reuse this code in other places as well :smile:

2024-09-02 19:30 UTC, danvb112 commented on modules/test/playwright/tests/object-web/objectFields.spec.ts
> +		);
Hey @igor-franca, I think we can use the `AsyncArray` class here too, could you try?

2024-09-02 20:50 UTC, igor-franca commented on modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ModelBuilder/ObjectDefinitionNode/ObjectDefinitionNodeFields.tsx
> +					objectField.businessType &&
I completely agree

2024-09-02 22:10 UTC, igor-franca commented
I'm experiencing SF errors unrelated to these changes, I'll take a look tomorrow.

2024-09-03 22:17 UTC, igor-franca commented
resent [here](https://github.com/liferay-objects/liferay-portal/pull/3632)

2024-09-03 22:17 UTC, closed without merging