LPD-29349
liferay-objects/liferay-portal pull request #3630
Opened 2024-09-03 18:47 UTC by pedro-oliveira446

2024-09-03 18:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-09-03 18:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/8916/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8916/jenkins-report.html">here</a>.</b></p>

2024-09-03 18:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7a53bda1036adcab663c904f32073ca3f82c9e87">7a53bda1036adcab663c904f32073ca3f82c9e87</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-29349">LPD-29349</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/84220c00f3af5ab8bdac1bdc686f82cdd6f04ffe">84220c00f3af5ab8bdac1bdc686f82cdd6f04ffe</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8916/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8916/jenkins-report.html">here</a>.</h5></details></html>

2024-09-03 18:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8916/">test-portal-source-format#8916</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8916/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3630">liferay-objects#3630</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/79195552">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-objects - PR#3630 - 2024-09-03[11:47:28]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79195552<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/33644/">publish-testray-report#33644</a><br/></div></div>

2024-09-04 14:31 UTC, MarinhoFeliphe requested changes

2024-09-04 21:33 UTC, gabrielwas requested changes
@pedro-oliveira446  Any questions, fell free to reach me :)

2024-09-04 21:33 UTC, gabrielwas commented on modules/apps/object/object-rest-impl/src/main/java/com/liferay/object/rest/internal/manager/v1_0/DefaultObjectEntryManagerImpl.java
> +						}
Let's keep it as it is, for now, until we confirm with product.

2024-09-04 21:33 UTC, gabrielwas commented on modules/apps/object/object-rest-impl/src/main/java/com/liferay/object/rest/internal/manager/v1_0/DefaultObjectEntryManagerImpl.java
> +								"object entries!");
`ObjectFieldRelationshipTypeException` is scoped for the management of Object Relationships. In this case, better raising a ObjectEntryValuesException (we can create a new sub class in this case).

2024-09-04 21:33 UTC, gabrielwas commented on modules/apps/object/object-rest-impl/src/main/java/com/liferay/object/rest/internal/manager/v1_0/DefaultObjectEntryManagerImpl.java
> +				if ((objectRelationship != null) &&
Is there any chance for it to be null?

2024-09-04 21:33 UTC, gabrielwas commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryLocalServiceImpl.java
> +			else if (objectField.compareBusinessType(
@pedro-oliveira446 Why are we doing it here again (inside `insertIntoTable`) since we're doing it already inside `_toObjectValues` ?

2024-09-04 21:33 UTC, gabrielwas commented on modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/ObjectEntryResourceTest.java
> +		objectEntryJSONObject = JSONUtil.put(
Do we need to override this variable? Doesn't it have the same value it already has?

2024-09-05 15:38 UTC, samuelromeiro commented
Closing this PR because the issue is not going to be considered a bug anymore.

2024-09-05 15:38 UTC, closed without merging