LPD-35277
liferay-objects/liferay-portal pull request #3636
Opened 2024-09-04 19:50 UTC by vngoliveira

[LPD-35277](https://liferay.atlassian.net/browse/LPD-35277)

2024-09-04 19:50 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-09-04 19:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6413/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6413/jenkins-report.html">here</a>.</b></p>

2024-09-04 19:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1228820313b158d362387f446f853c2387b152ba">1228820313b158d362387f446f853c2387b152ba</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-35277">LPD-35277</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/3d2d09abebcfb980d0754cc0bdeebec90c1aa9db">3d2d09abebcfb980d0754cc0bdeebec90c1aa9db</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6413/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6413/jenkins-report.html">here</a>.</h5></details></html>

2024-09-04 19:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6413/">test-portal-source-format#6413</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6413/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3636">liferay-objects#3636</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/79598479">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3636 - 2024-09-04[12:50:35]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>79598479<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/23959/">publish-testray-report#23959</a><br/></div></div>

2024-09-05 20:50 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-09-05 20:50 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +			_objectRelationshipLocalService.getServiceRegistrations();
Rename to `serviceRegistrations`  please

2024-09-05 20:50 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +			objectRelationshipDefinition1ServiceRegistration =
Rename to `ObjectRelationshipServiceRegistration`

2024-09-05 20:50 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +				_objectRelationship.getObjectRelationshipId()));
Will the list be updated if we execute `_objectRelationshipLocalService.getServiceRegistrations()`?
If yes > It is better to execute the get method and assert that this ServiceRegistration is not in that map.

2024-09-05 20:50 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +		ObjectRelationship objectRelationshipDefinition2 =
Rename to `reverseObjectRelationship`

2024-09-05 20:50 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +				objectRelationshipDefinition2.getObjectRelationshipId()));
Will the list be updated if we execute _objectRelationshipLocalService.getServiceRegistrations()?
If yes > It is better to execute the get method and assert that this ServiceRegistration is not in that map.

2024-09-05 20:50 UTC, marcelabc commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectDisplayPageTemplates.testcase
> +
Can you remove this code from the buildService commit? This type of commit can only contain generated code.

2024-09-06 11:46 UTC, vngoliveira commented
ci:test:sf

2024-09-06 11:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10104/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10104/jenkins-report.html">here</a>.</b></p>

2024-09-06 11:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d57e0328a2a22e733a7dc062b41555ac515d4251">d57e0328a2a22e733a7dc062b41555ac515d4251</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-35277">LPD-35277</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/48663763d3fde900e8d3b937625678bb4511242d">48663763d3fde900e8d3b937625678bb4511242d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10104/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10104/jenkins-report.html">here</a>.</h5></details></html>

2024-09-06 11:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10104/">test-portal-source-format#10104</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10104/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3636">liferay-objects#3636</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/82589675">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3636 - 2024-09-06[04:46:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>82589675<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/38633/">publish-testray-report#38633</a><br/></div></div>

2024-09-06 18:53 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-09-06 18:53 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +			_objectRelationshipLocalService.getServiceRegistrations();
Why do we need to call the remove method if we execute the get method in the following line?
I think we can remove the line calling the remove method.

2024-09-06 18:53 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +		serviceRegistrations.remove(serviceRegistrationKey);
same observation. Please remove this line.

2024-09-06 19:36 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +		serviceRegistrations.remove(serviceRegistrationKey);
Please verify if it is possible to:

- assert that there is no related entry when asserting the _objectDefinition1:
```
_assertRelatedInfoCollectionProvider(
	_objectDefinition1, objectDefinition1ObjectEntry1,
	objectDefinition2ObjectEntry);
_assertRelatedInfoCollectionProvider(
	_objectDefinition1, objectDefinition1ObjectEntry2,
	objectDefinition2ObjectEntry);
```
- assert that there is related entries when asserting the _objectDefinition2:
```
_assertRelatedInfoCollectionProvider(
	_objectDefinition2, objectDefinition2ObjectEntry,
	objectDefinition1ObjectEntry1, objectDefinition1ObjectEntry2);
```

2024-09-06 19:37 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +		serviceRegistrations.remove(serviceRegistrationKey);
Please verify if it is possible to:

- assert that there is no related entry when asserting the _objectDefinition1:
```
_assertRelatedInfoCollectionProvider(
	_objectDefinition1, objectDefinition1ObjectEntry1,
	objectDefinition2ObjectEntry);
_assertRelatedInfoCollectionProvider(
	_objectDefinition1, objectDefinition1ObjectEntry2,
	objectDefinition2ObjectEntry);
```
- assert that there are no related entries when asserting the _objectDefinition2:
```
_assertRelatedInfoCollectionProvider(
	_objectDefinition2, objectDefinition2ObjectEntry,
	objectDefinition1ObjectEntry1, objectDefinition1ObjectEntry2);
```

2024-09-09 16:28 UTC, vngoliveira commented
ci:test:sf

2024-09-09 16:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2aa20937beaf1415ddacba4447d5aee553580e0d">2aa20937beaf1415ddacba4447d5aee553580e0d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-35277">LPD-35277</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/e1877f7e40f7072a783585ef6bcc672ec750ebab">e1877f7e40f7072a783585ef6bcc672ec750ebab</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6193/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6193/jenkins-report.html">here</a>.</h5></details></html>

2024-09-09 16:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6193/">test-portal-source-format#6193</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6193/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3636">liferay-objects#3636</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/5666806">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3636 - 2024-09-09[09:28:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>5666806<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/24019/">publish-testray-report#24019</a><br/></div></div>

2024-09-10 13:23 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-09-10 13:23 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +			serviceRegistrations.containsKey(serviceRegistrations));
I think this code is unnecessary. Can you remove it, please?

2024-09-10 13:23 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/internal/info/collection/provider/test/ManyToManyObjectRelationshipInfoCollectionProviderTest.java
> +			serviceRegistrations.containsKey(serviceRegistrations));
I think this code is unnecessary. Can you remove it, please?

2024-09-10 13:28 UTC, vngoliveira commented
ci:test:sf

2024-09-10 13:50 UTC, marcelabc approved these changes
LGTM 🎉

2024-09-10 13:50 UTC, marcelabc commented
ci:test:sf

2024-09-10 13:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/6546/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6546/jenkins-report.html">here</a>.</b></p>

2024-09-10 13:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8abf22818849fef022c9ecc16232b3d4ea835385">8abf22818849fef022c9ecc16232b3d4ea835385</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-35277">LPD-35277</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/bebdb9dbbefa7eba9e8c0894851f11f8a9d6f7e8">bebdb9dbbefa7eba9e8c0894851f11f8a9d6f7e8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6546/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6546/jenkins-report.html">here</a>.</h5></details></html>

2024-09-10 13:57 UTC, marcelabc commented
ci:test:relevant

2024-09-10 13:58 UTC, marcelabc commented
ci:test:object

2024-09-10 13:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6546/">test-portal-source-format#6546</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6546/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3636">liferay-objects#3636</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/6592841">[master] ci:test:sf - vngoliveira &gt; liferay-objects - PR#3636 - 2024-09-10[06:52:01]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>6592841<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/24125/">publish-testray-report#24125</a><br/></div></div>

2024-09-10 14:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10939/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10939/jenkins-report.html">here</a>.</b></p>

2024-09-10 14:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10940/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10940/jenkins-report.html">here</a>.</b></p>

2024-09-10 16:40 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 82 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8abf22818849fef022c9ecc16232b3d4ea835385">8abf22818849fef022c9ecc16232b3d4ea835385</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10939/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10939/jenkins-report.html">here</a>.</b></p><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/10939/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/10939/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/10939/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2024-09-10 16:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10939/">test-portal-acceptance-pullrequest(master)#10939</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10939/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3636">liferay-objects#3636</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/6967539">[master] ci:test:relevant - vngoliveira &gt; liferay-objects - PR#3636 - 2024-09-10[07:09:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>6967539<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/23548/">publish-testray-report#23548</a><br/></div></div>

2024-09-10 16:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10940/">test-portal-acceptance-pullrequest(master)#10940</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10940/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3636">liferay-objects#3636</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/6974268">[master] ci:test:object - vngoliveira &gt; liferay-objects - PR#3636 - 2024-09-10[07:09:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>6974268<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/23549/">publish-testray-report#23549</a><br/></div></div>

2024-09-10 17:27 UTC, marcelabc commented
ci:report:6967539

2024-09-10 17:30 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>6967539</b>.</p><p>Job Link: <a href="https://test-1-7.liferay.com/job/generate-testray-csv/90/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-7.liferay.com/userContent/jobs/generate-testray-csv/builds/90/testray-results-6967539.csv">testray-results-6967539.csv</a></p>

2024-09-10 17:32 UTC, marcelabc commented
ci:report:6974268

2024-09-10 17:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>6974268</b>.</p><p>Job Link: <a href="https://test-1-39.liferay.com/job/generate-testray-csv/422/">generate-testray-csv</a></p>

2024-09-10 17:34 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>6974268</b>.</p><p>Job Link: <a href="https://test-1-39.liferay.com/job/generate-testray-csv/422/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/422/testray-results-6974268.csv">testray-results-6974268.csv</a></p>

2024-09-10 17:40 UTC, marcelabc commented
There are no unique failures.

2024-09-10 17:40 UTC, marcelabc commented
ci:forward:force

2024-09-10 17:40 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-09-10 17:40 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-09-10 17:41 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1461//consoleFull)

2024-09-10 17:41 UTC, closed without merging

2024-09-10 17:41 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/154050
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1461//consoleFull)