LPD-2294 [Upgrade process] Drop views of the object definition dynamic tables from partitioned DB
liferay-objects/liferay-portal pull request #3645
Opened 2024-09-06 13:23 UTC by p-albuquerque

Related issue: https://issues.liferay.com/browse/LPD-2294

2024-09-06 13:23 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-09-06 13:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/7101/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7101/jenkins-report.html">here</a>.</b></p>

2024-09-06 13:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0603a57b4399ed2453adbba57431be2c33851342">0603a57b4399ed2453adbba57431be2c33851342</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/p-albuquerque/liferay-portal/tree/LPD-2294">LPD-2294</a><br/>Branch GIT ID: <a href="https://github.com/p-albuquerque/liferay-portal/commit/662506b7a11aa969ed47125b72be150f01bf7686">662506b7a11aa969ed47125b72be150f01bf7686</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7101/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7101/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Test class 'com.liferay.object.internal.upgrade.v9_2_2.test.SchemaUpgradeProcessTest' does not exist: ./modules/apps/object/object-service/src/main/java/com/liferay/object/internal/upgrade/v9_2_2/SchemaUpgradeProcess.java (SourceCheck:JavaUpgradeMissingTestCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:469)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:54.429 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-8/job/test-portal-source-format/7101//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240906062740048.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240906062740048.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1213895273.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2003661600
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 190ms
[junitreport] Deleting: /tmp/null2003661600
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 09-06-2024 06:27:43:791 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2024-09-06 13:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7101/">test-portal-source-format#7101</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7101/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3645">liferay-objects#3645</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/82680875">[master] ci:test:sf - p-albuquerque &gt; liferay-objects - PR#3645 - 2024-09-06[06:24:05]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>82680875<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/5029/">publish-testray-report#5029</a><br/></div></div>

2024-09-06 17:09 UTC, p-albuquerque commented
Thread opened about this:
https://liferay.slack.com/archives/C1SJ64S9X/p1725642335918789

2024-09-06 19:49 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

We can send our PR to the database team. I will check if this is necessary for you.

2024-09-06 19:49 UTC, marcelabc commented on modules/apps/object/object-service/src/main/java/com/liferay/object/internal/upgrade/v9_2_2/SchemaUpgradeProcess.java
> +			!DBPartition.isPartitionEnabled()) {
Can we sort the conditions?
**!DBPartition.isPartitionEnabled()** || (**companyId** == defaultCompanyId) ?

2024-09-09 10:46 UTC, achaparro commented
@marcelabc @p-albuquerque see:
https://liferay.slack.com/archives/CUQP9C673/p1725878476216579?thread_ts=1725630491.655429&cid=CUQP9C673

2024-09-09 11:51 UTC, closed without merging