LPD-36588 | LPD-36589 Unbind object definitions by updating the object relationship edge property
liferay-objects/liferay-portal pull request #3672
Opened 2024-09-19 19:22 UTC by carolmariaabb

2024-09-19 19:22 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-09-19 19:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3705/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3705/jenkins-report.html">here</a>.</b></p>

2024-09-19 19:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c770dac5641583e1f697047f7167af3cb1b3daac">c770dac5641583e1f697047f7167af3cb1b3daac</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/carolmariaabb/liferay-portal/tree/LPD-36589">LPD-36589</a><br/>Branch GIT ID: <a href="https://github.com/carolmariaabb/liferay-portal/commit/76d189d2e51881598b3d0e4e4803d7231b824088">76d189d2e51881598b3d0e4e4803d7231b824088</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3705/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3705/jenkins-report.html">here</a>.</h5></details></html>

2024-09-19 19:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3705/">test-portal-source-format#3705</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3705/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3672">liferay-objects#3672</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/16134737">[master] ci:test:sf - carolmariaabb &gt; liferay-objects - PR#3672 - 2024-09-19[12:22:36]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>16134737<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/25155/">publish-testray-report#25155</a><br/></div></div>

2024-09-20 11:45 UTC, carolmariaabb commented
ci:test:sf

2024-09-20 11:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/5726/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5726/jenkins-report.html">here</a>.</b></p>

2024-09-20 11:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6a89b23a684fd4bbd00f9d36f0114573a6d51aa6">6a89b23a684fd4bbd00f9d36f0114573a6d51aa6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/carolmariaabb/liferay-portal/tree/LPD-36589">LPD-36589</a><br/>Branch GIT ID: <a href="https://github.com/carolmariaabb/liferay-portal/commit/92f87527b2f258d0cc9725bd21d18f34eca886c8">92f87527b2f258d0cc9725bd21d18f34eca886c8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/5726/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5726/jenkins-report.html">here</a>.</h5></details></html>

2024-09-20 11:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/5726/">test-portal-source-format#5726</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5726/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-objects/liferay-portal/pull/3672">liferay-objects#3672</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/16857678">[master] ci:test:sf - carolmariaabb &gt; liferay-objects - PR#3672 - 2024-09-20[04:46:00]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>16857678<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/6472/">publish-testray-report#6472</a><br/></div></div>

2024-09-23 12:25 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-09-23 12:27 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectRelationshipLocalServiceTest.java
> +
Let's discuss a pattern for naming this situation :+1:

2024-09-24 14:35 UTC, closed without merging